// Code generated by ent, DO NOT EDIT.

package model

import (
	"go-wind-admin/app/server/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uint64) predicate.Model {
	return predicate.Model(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint64) predicate.Model {
	return predicate.Model(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint64) predicate.Model {
	return predicate.Model(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint64) predicate.Model {
	return predicate.Model(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint64) predicate.Model {
	return predicate.Model(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint64) predicate.Model {
	return predicate.Model(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint64) predicate.Model {
	return predicate.Model(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint64) predicate.Model {
	return predicate.Model(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint64) predicate.Model {
	return predicate.Model(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Model {
	return predicate.Model(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Model {
	return predicate.Model(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.Model {
	return predicate.Model(sql.FieldEQ(FieldDeletedAt, v))
}

// Remark applies equality check predicate on the "remark" field. It's identical to RemarkEQ.
func Remark(v string) predicate.Model {
	return predicate.Model(sql.FieldEQ(FieldRemark, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Model {
	return predicate.Model(sql.FieldEQ(FieldDescription, v))
}

// IsEnabled applies equality check predicate on the "is_enabled" field. It's identical to IsEnabledEQ.
func IsEnabled(v bool) predicate.Model {
	return predicate.Model(sql.FieldEQ(FieldIsEnabled, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Model {
	return predicate.Model(sql.FieldEQ(FieldName, v))
}

// Slug applies equality check predicate on the "slug" field. It's identical to SlugEQ.
func Slug(v string) predicate.Model {
	return predicate.Model(sql.FieldEQ(FieldSlug, v))
}

// DockerImageRef applies equality check predicate on the "docker_image_ref" field. It's identical to DockerImageRefEQ.
func DockerImageRef(v string) predicate.Model {
	return predicate.Model(sql.FieldEQ(FieldDockerImageRef, v))
}

// BaseFramework applies equality check predicate on the "base_framework" field. It's identical to BaseFrameworkEQ.
func BaseFramework(v string) predicate.Model {
	return predicate.Model(sql.FieldEQ(FieldBaseFramework, v))
}

// ReadmeText applies equality check predicate on the "readme_text" field. It's identical to ReadmeTextEQ.
func ReadmeText(v string) predicate.Model {
	return predicate.Model(sql.FieldEQ(FieldReadmeText, v))
}

// Downloads applies equality check predicate on the "downloads" field. It's identical to DownloadsEQ.
func Downloads(v int64) predicate.Model {
	return predicate.Model(sql.FieldEQ(FieldDownloads, v))
}

// Likes applies equality check predicate on the "likes" field. It's identical to LikesEQ.
func Likes(v int64) predicate.Model {
	return predicate.Model(sql.FieldEQ(FieldLikes, v))
}

// License applies equality check predicate on the "license" field. It's identical to LicenseEQ.
func License(v string) predicate.Model {
	return predicate.Model(sql.FieldEQ(FieldLicense, v))
}

// ModelSize applies equality check predicate on the "model_size" field. It's identical to ModelSizeEQ.
func ModelSize(v int64) predicate.Model {
	return predicate.Model(sql.FieldEQ(FieldModelSize, v))
}

// UUID applies equality check predicate on the "uuid" field. It's identical to UUIDEQ.
func UUID(v uuid.UUID) predicate.Model {
	return predicate.Model(sql.FieldEQ(FieldUUID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Model {
	return predicate.Model(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Model {
	return predicate.Model(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Model {
	return predicate.Model(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Model {
	return predicate.Model(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Model {
	return predicate.Model(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Model {
	return predicate.Model(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Model {
	return predicate.Model(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Model {
	return predicate.Model(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.Model {
	return predicate.Model(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.Model {
	return predicate.Model(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Model {
	return predicate.Model(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Model {
	return predicate.Model(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Model {
	return predicate.Model(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Model {
	return predicate.Model(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Model {
	return predicate.Model(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Model {
	return predicate.Model(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Model {
	return predicate.Model(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Model {
	return predicate.Model(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.Model {
	return predicate.Model(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.Model {
	return predicate.Model(sql.FieldNotNull(FieldUpdatedAt))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.Model {
	return predicate.Model(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.Model {
	return predicate.Model(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.Model {
	return predicate.Model(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.Model {
	return predicate.Model(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.Model {
	return predicate.Model(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.Model {
	return predicate.Model(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.Model {
	return predicate.Model(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.Model {
	return predicate.Model(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.Model {
	return predicate.Model(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.Model {
	return predicate.Model(sql.FieldNotNull(FieldDeletedAt))
}

// RemarkEQ applies the EQ predicate on the "remark" field.
func RemarkEQ(v string) predicate.Model {
	return predicate.Model(sql.FieldEQ(FieldRemark, v))
}

// RemarkNEQ applies the NEQ predicate on the "remark" field.
func RemarkNEQ(v string) predicate.Model {
	return predicate.Model(sql.FieldNEQ(FieldRemark, v))
}

// RemarkIn applies the In predicate on the "remark" field.
func RemarkIn(vs ...string) predicate.Model {
	return predicate.Model(sql.FieldIn(FieldRemark, vs...))
}

// RemarkNotIn applies the NotIn predicate on the "remark" field.
func RemarkNotIn(vs ...string) predicate.Model {
	return predicate.Model(sql.FieldNotIn(FieldRemark, vs...))
}

// RemarkGT applies the GT predicate on the "remark" field.
func RemarkGT(v string) predicate.Model {
	return predicate.Model(sql.FieldGT(FieldRemark, v))
}

// RemarkGTE applies the GTE predicate on the "remark" field.
func RemarkGTE(v string) predicate.Model {
	return predicate.Model(sql.FieldGTE(FieldRemark, v))
}

// RemarkLT applies the LT predicate on the "remark" field.
func RemarkLT(v string) predicate.Model {
	return predicate.Model(sql.FieldLT(FieldRemark, v))
}

// RemarkLTE applies the LTE predicate on the "remark" field.
func RemarkLTE(v string) predicate.Model {
	return predicate.Model(sql.FieldLTE(FieldRemark, v))
}

// RemarkContains applies the Contains predicate on the "remark" field.
func RemarkContains(v string) predicate.Model {
	return predicate.Model(sql.FieldContains(FieldRemark, v))
}

// RemarkHasPrefix applies the HasPrefix predicate on the "remark" field.
func RemarkHasPrefix(v string) predicate.Model {
	return predicate.Model(sql.FieldHasPrefix(FieldRemark, v))
}

// RemarkHasSuffix applies the HasSuffix predicate on the "remark" field.
func RemarkHasSuffix(v string) predicate.Model {
	return predicate.Model(sql.FieldHasSuffix(FieldRemark, v))
}

// RemarkIsNil applies the IsNil predicate on the "remark" field.
func RemarkIsNil() predicate.Model {
	return predicate.Model(sql.FieldIsNull(FieldRemark))
}

// RemarkNotNil applies the NotNil predicate on the "remark" field.
func RemarkNotNil() predicate.Model {
	return predicate.Model(sql.FieldNotNull(FieldRemark))
}

// RemarkEqualFold applies the EqualFold predicate on the "remark" field.
func RemarkEqualFold(v string) predicate.Model {
	return predicate.Model(sql.FieldEqualFold(FieldRemark, v))
}

// RemarkContainsFold applies the ContainsFold predicate on the "remark" field.
func RemarkContainsFold(v string) predicate.Model {
	return predicate.Model(sql.FieldContainsFold(FieldRemark, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Model {
	return predicate.Model(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Model {
	return predicate.Model(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Model {
	return predicate.Model(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Model {
	return predicate.Model(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Model {
	return predicate.Model(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Model {
	return predicate.Model(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Model {
	return predicate.Model(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Model {
	return predicate.Model(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Model {
	return predicate.Model(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Model {
	return predicate.Model(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Model {
	return predicate.Model(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Model {
	return predicate.Model(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Model {
	return predicate.Model(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Model {
	return predicate.Model(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Model {
	return predicate.Model(sql.FieldContainsFold(FieldDescription, v))
}

// TagsIsNil applies the IsNil predicate on the "tags" field.
func TagsIsNil() predicate.Model {
	return predicate.Model(sql.FieldIsNull(FieldTags))
}

// TagsNotNil applies the NotNil predicate on the "tags" field.
func TagsNotNil() predicate.Model {
	return predicate.Model(sql.FieldNotNull(FieldTags))
}

// IsEnabledEQ applies the EQ predicate on the "is_enabled" field.
func IsEnabledEQ(v bool) predicate.Model {
	return predicate.Model(sql.FieldEQ(FieldIsEnabled, v))
}

// IsEnabledNEQ applies the NEQ predicate on the "is_enabled" field.
func IsEnabledNEQ(v bool) predicate.Model {
	return predicate.Model(sql.FieldNEQ(FieldIsEnabled, v))
}

// IsEnabledIsNil applies the IsNil predicate on the "is_enabled" field.
func IsEnabledIsNil() predicate.Model {
	return predicate.Model(sql.FieldIsNull(FieldIsEnabled))
}

// IsEnabledNotNil applies the NotNil predicate on the "is_enabled" field.
func IsEnabledNotNil() predicate.Model {
	return predicate.Model(sql.FieldNotNull(FieldIsEnabled))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Model {
	return predicate.Model(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Model {
	return predicate.Model(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Model {
	return predicate.Model(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Model {
	return predicate.Model(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Model {
	return predicate.Model(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Model {
	return predicate.Model(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Model {
	return predicate.Model(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Model {
	return predicate.Model(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Model {
	return predicate.Model(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Model {
	return predicate.Model(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Model {
	return predicate.Model(sql.FieldHasSuffix(FieldName, v))
}

// NameIsNil applies the IsNil predicate on the "name" field.
func NameIsNil() predicate.Model {
	return predicate.Model(sql.FieldIsNull(FieldName))
}

// NameNotNil applies the NotNil predicate on the "name" field.
func NameNotNil() predicate.Model {
	return predicate.Model(sql.FieldNotNull(FieldName))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Model {
	return predicate.Model(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Model {
	return predicate.Model(sql.FieldContainsFold(FieldName, v))
}

// SlugEQ applies the EQ predicate on the "slug" field.
func SlugEQ(v string) predicate.Model {
	return predicate.Model(sql.FieldEQ(FieldSlug, v))
}

// SlugNEQ applies the NEQ predicate on the "slug" field.
func SlugNEQ(v string) predicate.Model {
	return predicate.Model(sql.FieldNEQ(FieldSlug, v))
}

// SlugIn applies the In predicate on the "slug" field.
func SlugIn(vs ...string) predicate.Model {
	return predicate.Model(sql.FieldIn(FieldSlug, vs...))
}

// SlugNotIn applies the NotIn predicate on the "slug" field.
func SlugNotIn(vs ...string) predicate.Model {
	return predicate.Model(sql.FieldNotIn(FieldSlug, vs...))
}

// SlugGT applies the GT predicate on the "slug" field.
func SlugGT(v string) predicate.Model {
	return predicate.Model(sql.FieldGT(FieldSlug, v))
}

// SlugGTE applies the GTE predicate on the "slug" field.
func SlugGTE(v string) predicate.Model {
	return predicate.Model(sql.FieldGTE(FieldSlug, v))
}

// SlugLT applies the LT predicate on the "slug" field.
func SlugLT(v string) predicate.Model {
	return predicate.Model(sql.FieldLT(FieldSlug, v))
}

// SlugLTE applies the LTE predicate on the "slug" field.
func SlugLTE(v string) predicate.Model {
	return predicate.Model(sql.FieldLTE(FieldSlug, v))
}

// SlugContains applies the Contains predicate on the "slug" field.
func SlugContains(v string) predicate.Model {
	return predicate.Model(sql.FieldContains(FieldSlug, v))
}

// SlugHasPrefix applies the HasPrefix predicate on the "slug" field.
func SlugHasPrefix(v string) predicate.Model {
	return predicate.Model(sql.FieldHasPrefix(FieldSlug, v))
}

// SlugHasSuffix applies the HasSuffix predicate on the "slug" field.
func SlugHasSuffix(v string) predicate.Model {
	return predicate.Model(sql.FieldHasSuffix(FieldSlug, v))
}

// SlugIsNil applies the IsNil predicate on the "slug" field.
func SlugIsNil() predicate.Model {
	return predicate.Model(sql.FieldIsNull(FieldSlug))
}

// SlugNotNil applies the NotNil predicate on the "slug" field.
func SlugNotNil() predicate.Model {
	return predicate.Model(sql.FieldNotNull(FieldSlug))
}

// SlugEqualFold applies the EqualFold predicate on the "slug" field.
func SlugEqualFold(v string) predicate.Model {
	return predicate.Model(sql.FieldEqualFold(FieldSlug, v))
}

// SlugContainsFold applies the ContainsFold predicate on the "slug" field.
func SlugContainsFold(v string) predicate.Model {
	return predicate.Model(sql.FieldContainsFold(FieldSlug, v))
}

// DockerImageRefEQ applies the EQ predicate on the "docker_image_ref" field.
func DockerImageRefEQ(v string) predicate.Model {
	return predicate.Model(sql.FieldEQ(FieldDockerImageRef, v))
}

// DockerImageRefNEQ applies the NEQ predicate on the "docker_image_ref" field.
func DockerImageRefNEQ(v string) predicate.Model {
	return predicate.Model(sql.FieldNEQ(FieldDockerImageRef, v))
}

// DockerImageRefIn applies the In predicate on the "docker_image_ref" field.
func DockerImageRefIn(vs ...string) predicate.Model {
	return predicate.Model(sql.FieldIn(FieldDockerImageRef, vs...))
}

// DockerImageRefNotIn applies the NotIn predicate on the "docker_image_ref" field.
func DockerImageRefNotIn(vs ...string) predicate.Model {
	return predicate.Model(sql.FieldNotIn(FieldDockerImageRef, vs...))
}

// DockerImageRefGT applies the GT predicate on the "docker_image_ref" field.
func DockerImageRefGT(v string) predicate.Model {
	return predicate.Model(sql.FieldGT(FieldDockerImageRef, v))
}

// DockerImageRefGTE applies the GTE predicate on the "docker_image_ref" field.
func DockerImageRefGTE(v string) predicate.Model {
	return predicate.Model(sql.FieldGTE(FieldDockerImageRef, v))
}

// DockerImageRefLT applies the LT predicate on the "docker_image_ref" field.
func DockerImageRefLT(v string) predicate.Model {
	return predicate.Model(sql.FieldLT(FieldDockerImageRef, v))
}

// DockerImageRefLTE applies the LTE predicate on the "docker_image_ref" field.
func DockerImageRefLTE(v string) predicate.Model {
	return predicate.Model(sql.FieldLTE(FieldDockerImageRef, v))
}

// DockerImageRefContains applies the Contains predicate on the "docker_image_ref" field.
func DockerImageRefContains(v string) predicate.Model {
	return predicate.Model(sql.FieldContains(FieldDockerImageRef, v))
}

// DockerImageRefHasPrefix applies the HasPrefix predicate on the "docker_image_ref" field.
func DockerImageRefHasPrefix(v string) predicate.Model {
	return predicate.Model(sql.FieldHasPrefix(FieldDockerImageRef, v))
}

// DockerImageRefHasSuffix applies the HasSuffix predicate on the "docker_image_ref" field.
func DockerImageRefHasSuffix(v string) predicate.Model {
	return predicate.Model(sql.FieldHasSuffix(FieldDockerImageRef, v))
}

// DockerImageRefIsNil applies the IsNil predicate on the "docker_image_ref" field.
func DockerImageRefIsNil() predicate.Model {
	return predicate.Model(sql.FieldIsNull(FieldDockerImageRef))
}

// DockerImageRefNotNil applies the NotNil predicate on the "docker_image_ref" field.
func DockerImageRefNotNil() predicate.Model {
	return predicate.Model(sql.FieldNotNull(FieldDockerImageRef))
}

// DockerImageRefEqualFold applies the EqualFold predicate on the "docker_image_ref" field.
func DockerImageRefEqualFold(v string) predicate.Model {
	return predicate.Model(sql.FieldEqualFold(FieldDockerImageRef, v))
}

// DockerImageRefContainsFold applies the ContainsFold predicate on the "docker_image_ref" field.
func DockerImageRefContainsFold(v string) predicate.Model {
	return predicate.Model(sql.FieldContainsFold(FieldDockerImageRef, v))
}

// JupyterCommandIsNil applies the IsNil predicate on the "jupyter_command" field.
func JupyterCommandIsNil() predicate.Model {
	return predicate.Model(sql.FieldIsNull(FieldJupyterCommand))
}

// JupyterCommandNotNil applies the NotNil predicate on the "jupyter_command" field.
func JupyterCommandNotNil() predicate.Model {
	return predicate.Model(sql.FieldNotNull(FieldJupyterCommand))
}

// VllmCommandIsNil applies the IsNil predicate on the "vllm_command" field.
func VllmCommandIsNil() predicate.Model {
	return predicate.Model(sql.FieldIsNull(FieldVllmCommand))
}

// VllmCommandNotNil applies the NotNil predicate on the "vllm_command" field.
func VllmCommandNotNil() predicate.Model {
	return predicate.Model(sql.FieldNotNull(FieldVllmCommand))
}

// CommandMappingIsNil applies the IsNil predicate on the "command_mapping" field.
func CommandMappingIsNil() predicate.Model {
	return predicate.Model(sql.FieldIsNull(FieldCommandMapping))
}

// CommandMappingNotNil applies the NotNil predicate on the "command_mapping" field.
func CommandMappingNotNil() predicate.Model {
	return predicate.Model(sql.FieldNotNull(FieldCommandMapping))
}

// EnvIsNil applies the IsNil predicate on the "env" field.
func EnvIsNil() predicate.Model {
	return predicate.Model(sql.FieldIsNull(FieldEnv))
}

// EnvNotNil applies the NotNil predicate on the "env" field.
func EnvNotNil() predicate.Model {
	return predicate.Model(sql.FieldNotNull(FieldEnv))
}

// PortsIsNil applies the IsNil predicate on the "ports" field.
func PortsIsNil() predicate.Model {
	return predicate.Model(sql.FieldIsNull(FieldPorts))
}

// PortsNotNil applies the NotNil predicate on the "ports" field.
func PortsNotNil() predicate.Model {
	return predicate.Model(sql.FieldNotNull(FieldPorts))
}

// WritablePathsIsNil applies the IsNil predicate on the "writable_paths" field.
func WritablePathsIsNil() predicate.Model {
	return predicate.Model(sql.FieldIsNull(FieldWritablePaths))
}

// WritablePathsNotNil applies the NotNil predicate on the "writable_paths" field.
func WritablePathsNotNil() predicate.Model {
	return predicate.Model(sql.FieldNotNull(FieldWritablePaths))
}

// BaseFrameworkEQ applies the EQ predicate on the "base_framework" field.
func BaseFrameworkEQ(v string) predicate.Model {
	return predicate.Model(sql.FieldEQ(FieldBaseFramework, v))
}

// BaseFrameworkNEQ applies the NEQ predicate on the "base_framework" field.
func BaseFrameworkNEQ(v string) predicate.Model {
	return predicate.Model(sql.FieldNEQ(FieldBaseFramework, v))
}

// BaseFrameworkIn applies the In predicate on the "base_framework" field.
func BaseFrameworkIn(vs ...string) predicate.Model {
	return predicate.Model(sql.FieldIn(FieldBaseFramework, vs...))
}

// BaseFrameworkNotIn applies the NotIn predicate on the "base_framework" field.
func BaseFrameworkNotIn(vs ...string) predicate.Model {
	return predicate.Model(sql.FieldNotIn(FieldBaseFramework, vs...))
}

// BaseFrameworkGT applies the GT predicate on the "base_framework" field.
func BaseFrameworkGT(v string) predicate.Model {
	return predicate.Model(sql.FieldGT(FieldBaseFramework, v))
}

// BaseFrameworkGTE applies the GTE predicate on the "base_framework" field.
func BaseFrameworkGTE(v string) predicate.Model {
	return predicate.Model(sql.FieldGTE(FieldBaseFramework, v))
}

// BaseFrameworkLT applies the LT predicate on the "base_framework" field.
func BaseFrameworkLT(v string) predicate.Model {
	return predicate.Model(sql.FieldLT(FieldBaseFramework, v))
}

// BaseFrameworkLTE applies the LTE predicate on the "base_framework" field.
func BaseFrameworkLTE(v string) predicate.Model {
	return predicate.Model(sql.FieldLTE(FieldBaseFramework, v))
}

// BaseFrameworkContains applies the Contains predicate on the "base_framework" field.
func BaseFrameworkContains(v string) predicate.Model {
	return predicate.Model(sql.FieldContains(FieldBaseFramework, v))
}

// BaseFrameworkHasPrefix applies the HasPrefix predicate on the "base_framework" field.
func BaseFrameworkHasPrefix(v string) predicate.Model {
	return predicate.Model(sql.FieldHasPrefix(FieldBaseFramework, v))
}

// BaseFrameworkHasSuffix applies the HasSuffix predicate on the "base_framework" field.
func BaseFrameworkHasSuffix(v string) predicate.Model {
	return predicate.Model(sql.FieldHasSuffix(FieldBaseFramework, v))
}

// BaseFrameworkIsNil applies the IsNil predicate on the "base_framework" field.
func BaseFrameworkIsNil() predicate.Model {
	return predicate.Model(sql.FieldIsNull(FieldBaseFramework))
}

// BaseFrameworkNotNil applies the NotNil predicate on the "base_framework" field.
func BaseFrameworkNotNil() predicate.Model {
	return predicate.Model(sql.FieldNotNull(FieldBaseFramework))
}

// BaseFrameworkEqualFold applies the EqualFold predicate on the "base_framework" field.
func BaseFrameworkEqualFold(v string) predicate.Model {
	return predicate.Model(sql.FieldEqualFold(FieldBaseFramework, v))
}

// BaseFrameworkContainsFold applies the ContainsFold predicate on the "base_framework" field.
func BaseFrameworkContainsFold(v string) predicate.Model {
	return predicate.Model(sql.FieldContainsFold(FieldBaseFramework, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v Type) predicate.Model {
	return predicate.Model(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v Type) predicate.Model {
	return predicate.Model(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...Type) predicate.Model {
	return predicate.Model(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...Type) predicate.Model {
	return predicate.Model(sql.FieldNotIn(FieldType, vs...))
}

// TypeIsNil applies the IsNil predicate on the "type" field.
func TypeIsNil() predicate.Model {
	return predicate.Model(sql.FieldIsNull(FieldType))
}

// TypeNotNil applies the NotNil predicate on the "type" field.
func TypeNotNil() predicate.Model {
	return predicate.Model(sql.FieldNotNull(FieldType))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Model {
	return predicate.Model(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Model {
	return predicate.Model(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Model {
	return predicate.Model(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Model {
	return predicate.Model(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusIsNil applies the IsNil predicate on the "status" field.
func StatusIsNil() predicate.Model {
	return predicate.Model(sql.FieldIsNull(FieldStatus))
}

// StatusNotNil applies the NotNil predicate on the "status" field.
func StatusNotNil() predicate.Model {
	return predicate.Model(sql.FieldNotNull(FieldStatus))
}

// ReadmeTextEQ applies the EQ predicate on the "readme_text" field.
func ReadmeTextEQ(v string) predicate.Model {
	return predicate.Model(sql.FieldEQ(FieldReadmeText, v))
}

// ReadmeTextNEQ applies the NEQ predicate on the "readme_text" field.
func ReadmeTextNEQ(v string) predicate.Model {
	return predicate.Model(sql.FieldNEQ(FieldReadmeText, v))
}

// ReadmeTextIn applies the In predicate on the "readme_text" field.
func ReadmeTextIn(vs ...string) predicate.Model {
	return predicate.Model(sql.FieldIn(FieldReadmeText, vs...))
}

// ReadmeTextNotIn applies the NotIn predicate on the "readme_text" field.
func ReadmeTextNotIn(vs ...string) predicate.Model {
	return predicate.Model(sql.FieldNotIn(FieldReadmeText, vs...))
}

// ReadmeTextGT applies the GT predicate on the "readme_text" field.
func ReadmeTextGT(v string) predicate.Model {
	return predicate.Model(sql.FieldGT(FieldReadmeText, v))
}

// ReadmeTextGTE applies the GTE predicate on the "readme_text" field.
func ReadmeTextGTE(v string) predicate.Model {
	return predicate.Model(sql.FieldGTE(FieldReadmeText, v))
}

// ReadmeTextLT applies the LT predicate on the "readme_text" field.
func ReadmeTextLT(v string) predicate.Model {
	return predicate.Model(sql.FieldLT(FieldReadmeText, v))
}

// ReadmeTextLTE applies the LTE predicate on the "readme_text" field.
func ReadmeTextLTE(v string) predicate.Model {
	return predicate.Model(sql.FieldLTE(FieldReadmeText, v))
}

// ReadmeTextContains applies the Contains predicate on the "readme_text" field.
func ReadmeTextContains(v string) predicate.Model {
	return predicate.Model(sql.FieldContains(FieldReadmeText, v))
}

// ReadmeTextHasPrefix applies the HasPrefix predicate on the "readme_text" field.
func ReadmeTextHasPrefix(v string) predicate.Model {
	return predicate.Model(sql.FieldHasPrefix(FieldReadmeText, v))
}

// ReadmeTextHasSuffix applies the HasSuffix predicate on the "readme_text" field.
func ReadmeTextHasSuffix(v string) predicate.Model {
	return predicate.Model(sql.FieldHasSuffix(FieldReadmeText, v))
}

// ReadmeTextIsNil applies the IsNil predicate on the "readme_text" field.
func ReadmeTextIsNil() predicate.Model {
	return predicate.Model(sql.FieldIsNull(FieldReadmeText))
}

// ReadmeTextNotNil applies the NotNil predicate on the "readme_text" field.
func ReadmeTextNotNil() predicate.Model {
	return predicate.Model(sql.FieldNotNull(FieldReadmeText))
}

// ReadmeTextEqualFold applies the EqualFold predicate on the "readme_text" field.
func ReadmeTextEqualFold(v string) predicate.Model {
	return predicate.Model(sql.FieldEqualFold(FieldReadmeText, v))
}

// ReadmeTextContainsFold applies the ContainsFold predicate on the "readme_text" field.
func ReadmeTextContainsFold(v string) predicate.Model {
	return predicate.Model(sql.FieldContainsFold(FieldReadmeText, v))
}

// DownloadsEQ applies the EQ predicate on the "downloads" field.
func DownloadsEQ(v int64) predicate.Model {
	return predicate.Model(sql.FieldEQ(FieldDownloads, v))
}

// DownloadsNEQ applies the NEQ predicate on the "downloads" field.
func DownloadsNEQ(v int64) predicate.Model {
	return predicate.Model(sql.FieldNEQ(FieldDownloads, v))
}

// DownloadsIn applies the In predicate on the "downloads" field.
func DownloadsIn(vs ...int64) predicate.Model {
	return predicate.Model(sql.FieldIn(FieldDownloads, vs...))
}

// DownloadsNotIn applies the NotIn predicate on the "downloads" field.
func DownloadsNotIn(vs ...int64) predicate.Model {
	return predicate.Model(sql.FieldNotIn(FieldDownloads, vs...))
}

// DownloadsGT applies the GT predicate on the "downloads" field.
func DownloadsGT(v int64) predicate.Model {
	return predicate.Model(sql.FieldGT(FieldDownloads, v))
}

// DownloadsGTE applies the GTE predicate on the "downloads" field.
func DownloadsGTE(v int64) predicate.Model {
	return predicate.Model(sql.FieldGTE(FieldDownloads, v))
}

// DownloadsLT applies the LT predicate on the "downloads" field.
func DownloadsLT(v int64) predicate.Model {
	return predicate.Model(sql.FieldLT(FieldDownloads, v))
}

// DownloadsLTE applies the LTE predicate on the "downloads" field.
func DownloadsLTE(v int64) predicate.Model {
	return predicate.Model(sql.FieldLTE(FieldDownloads, v))
}

// DownloadsIsNil applies the IsNil predicate on the "downloads" field.
func DownloadsIsNil() predicate.Model {
	return predicate.Model(sql.FieldIsNull(FieldDownloads))
}

// DownloadsNotNil applies the NotNil predicate on the "downloads" field.
func DownloadsNotNil() predicate.Model {
	return predicate.Model(sql.FieldNotNull(FieldDownloads))
}

// LikesEQ applies the EQ predicate on the "likes" field.
func LikesEQ(v int64) predicate.Model {
	return predicate.Model(sql.FieldEQ(FieldLikes, v))
}

// LikesNEQ applies the NEQ predicate on the "likes" field.
func LikesNEQ(v int64) predicate.Model {
	return predicate.Model(sql.FieldNEQ(FieldLikes, v))
}

// LikesIn applies the In predicate on the "likes" field.
func LikesIn(vs ...int64) predicate.Model {
	return predicate.Model(sql.FieldIn(FieldLikes, vs...))
}

// LikesNotIn applies the NotIn predicate on the "likes" field.
func LikesNotIn(vs ...int64) predicate.Model {
	return predicate.Model(sql.FieldNotIn(FieldLikes, vs...))
}

// LikesGT applies the GT predicate on the "likes" field.
func LikesGT(v int64) predicate.Model {
	return predicate.Model(sql.FieldGT(FieldLikes, v))
}

// LikesGTE applies the GTE predicate on the "likes" field.
func LikesGTE(v int64) predicate.Model {
	return predicate.Model(sql.FieldGTE(FieldLikes, v))
}

// LikesLT applies the LT predicate on the "likes" field.
func LikesLT(v int64) predicate.Model {
	return predicate.Model(sql.FieldLT(FieldLikes, v))
}

// LikesLTE applies the LTE predicate on the "likes" field.
func LikesLTE(v int64) predicate.Model {
	return predicate.Model(sql.FieldLTE(FieldLikes, v))
}

// LikesIsNil applies the IsNil predicate on the "likes" field.
func LikesIsNil() predicate.Model {
	return predicate.Model(sql.FieldIsNull(FieldLikes))
}

// LikesNotNil applies the NotNil predicate on the "likes" field.
func LikesNotNil() predicate.Model {
	return predicate.Model(sql.FieldNotNull(FieldLikes))
}

// LicenseEQ applies the EQ predicate on the "license" field.
func LicenseEQ(v string) predicate.Model {
	return predicate.Model(sql.FieldEQ(FieldLicense, v))
}

// LicenseNEQ applies the NEQ predicate on the "license" field.
func LicenseNEQ(v string) predicate.Model {
	return predicate.Model(sql.FieldNEQ(FieldLicense, v))
}

// LicenseIn applies the In predicate on the "license" field.
func LicenseIn(vs ...string) predicate.Model {
	return predicate.Model(sql.FieldIn(FieldLicense, vs...))
}

// LicenseNotIn applies the NotIn predicate on the "license" field.
func LicenseNotIn(vs ...string) predicate.Model {
	return predicate.Model(sql.FieldNotIn(FieldLicense, vs...))
}

// LicenseGT applies the GT predicate on the "license" field.
func LicenseGT(v string) predicate.Model {
	return predicate.Model(sql.FieldGT(FieldLicense, v))
}

// LicenseGTE applies the GTE predicate on the "license" field.
func LicenseGTE(v string) predicate.Model {
	return predicate.Model(sql.FieldGTE(FieldLicense, v))
}

// LicenseLT applies the LT predicate on the "license" field.
func LicenseLT(v string) predicate.Model {
	return predicate.Model(sql.FieldLT(FieldLicense, v))
}

// LicenseLTE applies the LTE predicate on the "license" field.
func LicenseLTE(v string) predicate.Model {
	return predicate.Model(sql.FieldLTE(FieldLicense, v))
}

// LicenseContains applies the Contains predicate on the "license" field.
func LicenseContains(v string) predicate.Model {
	return predicate.Model(sql.FieldContains(FieldLicense, v))
}

// LicenseHasPrefix applies the HasPrefix predicate on the "license" field.
func LicenseHasPrefix(v string) predicate.Model {
	return predicate.Model(sql.FieldHasPrefix(FieldLicense, v))
}

// LicenseHasSuffix applies the HasSuffix predicate on the "license" field.
func LicenseHasSuffix(v string) predicate.Model {
	return predicate.Model(sql.FieldHasSuffix(FieldLicense, v))
}

// LicenseIsNil applies the IsNil predicate on the "license" field.
func LicenseIsNil() predicate.Model {
	return predicate.Model(sql.FieldIsNull(FieldLicense))
}

// LicenseNotNil applies the NotNil predicate on the "license" field.
func LicenseNotNil() predicate.Model {
	return predicate.Model(sql.FieldNotNull(FieldLicense))
}

// LicenseEqualFold applies the EqualFold predicate on the "license" field.
func LicenseEqualFold(v string) predicate.Model {
	return predicate.Model(sql.FieldEqualFold(FieldLicense, v))
}

// LicenseContainsFold applies the ContainsFold predicate on the "license" field.
func LicenseContainsFold(v string) predicate.Model {
	return predicate.Model(sql.FieldContainsFold(FieldLicense, v))
}

// ModelSizeEQ applies the EQ predicate on the "model_size" field.
func ModelSizeEQ(v int64) predicate.Model {
	return predicate.Model(sql.FieldEQ(FieldModelSize, v))
}

// ModelSizeNEQ applies the NEQ predicate on the "model_size" field.
func ModelSizeNEQ(v int64) predicate.Model {
	return predicate.Model(sql.FieldNEQ(FieldModelSize, v))
}

// ModelSizeIn applies the In predicate on the "model_size" field.
func ModelSizeIn(vs ...int64) predicate.Model {
	return predicate.Model(sql.FieldIn(FieldModelSize, vs...))
}

// ModelSizeNotIn applies the NotIn predicate on the "model_size" field.
func ModelSizeNotIn(vs ...int64) predicate.Model {
	return predicate.Model(sql.FieldNotIn(FieldModelSize, vs...))
}

// ModelSizeGT applies the GT predicate on the "model_size" field.
func ModelSizeGT(v int64) predicate.Model {
	return predicate.Model(sql.FieldGT(FieldModelSize, v))
}

// ModelSizeGTE applies the GTE predicate on the "model_size" field.
func ModelSizeGTE(v int64) predicate.Model {
	return predicate.Model(sql.FieldGTE(FieldModelSize, v))
}

// ModelSizeLT applies the LT predicate on the "model_size" field.
func ModelSizeLT(v int64) predicate.Model {
	return predicate.Model(sql.FieldLT(FieldModelSize, v))
}

// ModelSizeLTE applies the LTE predicate on the "model_size" field.
func ModelSizeLTE(v int64) predicate.Model {
	return predicate.Model(sql.FieldLTE(FieldModelSize, v))
}

// ModelSizeIsNil applies the IsNil predicate on the "model_size" field.
func ModelSizeIsNil() predicate.Model {
	return predicate.Model(sql.FieldIsNull(FieldModelSize))
}

// ModelSizeNotNil applies the NotNil predicate on the "model_size" field.
func ModelSizeNotNil() predicate.Model {
	return predicate.Model(sql.FieldNotNull(FieldModelSize))
}

// UUIDEQ applies the EQ predicate on the "uuid" field.
func UUIDEQ(v uuid.UUID) predicate.Model {
	return predicate.Model(sql.FieldEQ(FieldUUID, v))
}

// UUIDNEQ applies the NEQ predicate on the "uuid" field.
func UUIDNEQ(v uuid.UUID) predicate.Model {
	return predicate.Model(sql.FieldNEQ(FieldUUID, v))
}

// UUIDIn applies the In predicate on the "uuid" field.
func UUIDIn(vs ...uuid.UUID) predicate.Model {
	return predicate.Model(sql.FieldIn(FieldUUID, vs...))
}

// UUIDNotIn applies the NotIn predicate on the "uuid" field.
func UUIDNotIn(vs ...uuid.UUID) predicate.Model {
	return predicate.Model(sql.FieldNotIn(FieldUUID, vs...))
}

// UUIDGT applies the GT predicate on the "uuid" field.
func UUIDGT(v uuid.UUID) predicate.Model {
	return predicate.Model(sql.FieldGT(FieldUUID, v))
}

// UUIDGTE applies the GTE predicate on the "uuid" field.
func UUIDGTE(v uuid.UUID) predicate.Model {
	return predicate.Model(sql.FieldGTE(FieldUUID, v))
}

// UUIDLT applies the LT predicate on the "uuid" field.
func UUIDLT(v uuid.UUID) predicate.Model {
	return predicate.Model(sql.FieldLT(FieldUUID, v))
}

// UUIDLTE applies the LTE predicate on the "uuid" field.
func UUIDLTE(v uuid.UUID) predicate.Model {
	return predicate.Model(sql.FieldLTE(FieldUUID, v))
}

// UUIDIsNil applies the IsNil predicate on the "uuid" field.
func UUIDIsNil() predicate.Model {
	return predicate.Model(sql.FieldIsNull(FieldUUID))
}

// UUIDNotNil applies the NotNil predicate on the "uuid" field.
func UUIDNotNil() predicate.Model {
	return predicate.Model(sql.FieldNotNull(FieldUUID))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Model) predicate.Model {
	return predicate.Model(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Model) predicate.Model {
	return predicate.Model(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Model) predicate.Model {
	return predicate.Model(sql.NotPredicates(p))
}
