// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	servicev1 "go-wind-admin/api/gen/go/tenant/service/v1"
	"go-wind-admin/app/server/service/internal/data/ent/inference"
	"go-wind-admin/app/server/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// InferenceUpdate is the builder for updating Inference entities.
type InferenceUpdate struct {
	config
	hooks     []Hook
	mutation  *InferenceMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the InferenceUpdate builder.
func (_u *InferenceUpdate) Where(ps ...predicate.Inference) *InferenceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *InferenceUpdate) SetUpdatedAt(v time.Time) *InferenceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *InferenceUpdate) SetNillableUpdatedAt(v *time.Time) *InferenceUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *InferenceUpdate) ClearUpdatedAt() *InferenceUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *InferenceUpdate) SetDeletedAt(v time.Time) *InferenceUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *InferenceUpdate) SetNillableDeletedAt(v *time.Time) *InferenceUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *InferenceUpdate) ClearDeletedAt() *InferenceUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetRemark sets the "remark" field.
func (_u *InferenceUpdate) SetRemark(v string) *InferenceUpdate {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *InferenceUpdate) SetNillableRemark(v *string) *InferenceUpdate {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *InferenceUpdate) ClearRemark() *InferenceUpdate {
	_u.mutation.ClearRemark()
	return _u
}

// SetDescription sets the "description" field.
func (_u *InferenceUpdate) SetDescription(v string) *InferenceUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *InferenceUpdate) SetNillableDescription(v *string) *InferenceUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *InferenceUpdate) ClearDescription() *InferenceUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetTags sets the "tags" field.
func (_u *InferenceUpdate) SetTags(v []string) *InferenceUpdate {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *InferenceUpdate) AppendTags(v []string) *InferenceUpdate {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *InferenceUpdate) ClearTags() *InferenceUpdate {
	_u.mutation.ClearTags()
	return _u
}

// SetIsEnabled sets the "is_enabled" field.
func (_u *InferenceUpdate) SetIsEnabled(v bool) *InferenceUpdate {
	_u.mutation.SetIsEnabled(v)
	return _u
}

// SetNillableIsEnabled sets the "is_enabled" field if the given value is not nil.
func (_u *InferenceUpdate) SetNillableIsEnabled(v *bool) *InferenceUpdate {
	if v != nil {
		_u.SetIsEnabled(*v)
	}
	return _u
}

// ClearIsEnabled clears the value of the "is_enabled" field.
func (_u *InferenceUpdate) ClearIsEnabled() *InferenceUpdate {
	_u.mutation.ClearIsEnabled()
	return _u
}

// SetStatus sets the "status" field.
func (_u *InferenceUpdate) SetStatus(v inference.Status) *InferenceUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *InferenceUpdate) SetNillableStatus(v *inference.Status) *InferenceUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *InferenceUpdate) ClearStatus() *InferenceUpdate {
	_u.mutation.ClearStatus()
	return _u
}

// SetModelID sets the "model_id" field.
func (_u *InferenceUpdate) SetModelID(v uint64) *InferenceUpdate {
	_u.mutation.ResetModelID()
	_u.mutation.SetModelID(v)
	return _u
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (_u *InferenceUpdate) SetNillableModelID(v *uint64) *InferenceUpdate {
	if v != nil {
		_u.SetModelID(*v)
	}
	return _u
}

// AddModelID adds value to the "model_id" field.
func (_u *InferenceUpdate) AddModelID(v int64) *InferenceUpdate {
	_u.mutation.AddModelID(v)
	return _u
}

// ClearModelID clears the value of the "model_id" field.
func (_u *InferenceUpdate) ClearModelID() *InferenceUpdate {
	_u.mutation.ClearModelID()
	return _u
}

// SetModelName sets the "model_name" field.
func (_u *InferenceUpdate) SetModelName(v string) *InferenceUpdate {
	_u.mutation.SetModelName(v)
	return _u
}

// SetNillableModelName sets the "model_name" field if the given value is not nil.
func (_u *InferenceUpdate) SetNillableModelName(v *string) *InferenceUpdate {
	if v != nil {
		_u.SetModelName(*v)
	}
	return _u
}

// ClearModelName clears the value of the "model_name" field.
func (_u *InferenceUpdate) ClearModelName() *InferenceUpdate {
	_u.mutation.ClearModelName()
	return _u
}

// SetImage sets the "image" field.
func (_u *InferenceUpdate) SetImage(v string) *InferenceUpdate {
	_u.mutation.SetImage(v)
	return _u
}

// SetNillableImage sets the "image" field if the given value is not nil.
func (_u *InferenceUpdate) SetNillableImage(v *string) *InferenceUpdate {
	if v != nil {
		_u.SetImage(*v)
	}
	return _u
}

// ClearImage clears the value of the "image" field.
func (_u *InferenceUpdate) ClearImage() *InferenceUpdate {
	_u.mutation.ClearImage()
	return _u
}

// SetReplicas sets the "replicas" field.
func (_u *InferenceUpdate) SetReplicas(v int32) *InferenceUpdate {
	_u.mutation.ResetReplicas()
	_u.mutation.SetReplicas(v)
	return _u
}

// SetNillableReplicas sets the "replicas" field if the given value is not nil.
func (_u *InferenceUpdate) SetNillableReplicas(v *int32) *InferenceUpdate {
	if v != nil {
		_u.SetReplicas(*v)
	}
	return _u
}

// AddReplicas adds value to the "replicas" field.
func (_u *InferenceUpdate) AddReplicas(v int32) *InferenceUpdate {
	_u.mutation.AddReplicas(v)
	return _u
}

// SetMinReplicas sets the "min_replicas" field.
func (_u *InferenceUpdate) SetMinReplicas(v int32) *InferenceUpdate {
	_u.mutation.ResetMinReplicas()
	_u.mutation.SetMinReplicas(v)
	return _u
}

// SetNillableMinReplicas sets the "min_replicas" field if the given value is not nil.
func (_u *InferenceUpdate) SetNillableMinReplicas(v *int32) *InferenceUpdate {
	if v != nil {
		_u.SetMinReplicas(*v)
	}
	return _u
}

// AddMinReplicas adds value to the "min_replicas" field.
func (_u *InferenceUpdate) AddMinReplicas(v int32) *InferenceUpdate {
	_u.mutation.AddMinReplicas(v)
	return _u
}

// ClearMinReplicas clears the value of the "min_replicas" field.
func (_u *InferenceUpdate) ClearMinReplicas() *InferenceUpdate {
	_u.mutation.ClearMinReplicas()
	return _u
}

// SetMaxReplicas sets the "max_replicas" field.
func (_u *InferenceUpdate) SetMaxReplicas(v int32) *InferenceUpdate {
	_u.mutation.ResetMaxReplicas()
	_u.mutation.SetMaxReplicas(v)
	return _u
}

// SetNillableMaxReplicas sets the "max_replicas" field if the given value is not nil.
func (_u *InferenceUpdate) SetNillableMaxReplicas(v *int32) *InferenceUpdate {
	if v != nil {
		_u.SetMaxReplicas(*v)
	}
	return _u
}

// AddMaxReplicas adds value to the "max_replicas" field.
func (_u *InferenceUpdate) AddMaxReplicas(v int32) *InferenceUpdate {
	_u.mutation.AddMaxReplicas(v)
	return _u
}

// ClearMaxReplicas clears the value of the "max_replicas" field.
func (_u *InferenceUpdate) ClearMaxReplicas() *InferenceUpdate {
	_u.mutation.ClearMaxReplicas()
	return _u
}

// SetPort sets the "port" field.
func (_u *InferenceUpdate) SetPort(v int32) *InferenceUpdate {
	_u.mutation.ResetPort()
	_u.mutation.SetPort(v)
	return _u
}

// SetNillablePort sets the "port" field if the given value is not nil.
func (_u *InferenceUpdate) SetNillablePort(v *int32) *InferenceUpdate {
	if v != nil {
		_u.SetPort(*v)
	}
	return _u
}

// AddPort adds value to the "port" field.
func (_u *InferenceUpdate) AddPort(v int32) *InferenceUpdate {
	_u.mutation.AddPort(v)
	return _u
}

// SetCommand sets the "command" field.
func (_u *InferenceUpdate) SetCommand(v []string) *InferenceUpdate {
	_u.mutation.SetCommand(v)
	return _u
}

// AppendCommand appends value to the "command" field.
func (_u *InferenceUpdate) AppendCommand(v []string) *InferenceUpdate {
	_u.mutation.AppendCommand(v)
	return _u
}

// ClearCommand clears the value of the "command" field.
func (_u *InferenceUpdate) ClearCommand() *InferenceUpdate {
	_u.mutation.ClearCommand()
	return _u
}

// SetArgs sets the "args" field.
func (_u *InferenceUpdate) SetArgs(v []string) *InferenceUpdate {
	_u.mutation.SetArgs(v)
	return _u
}

// AppendArgs appends value to the "args" field.
func (_u *InferenceUpdate) AppendArgs(v []string) *InferenceUpdate {
	_u.mutation.AppendArgs(v)
	return _u
}

// ClearArgs clears the value of the "args" field.
func (_u *InferenceUpdate) ClearArgs() *InferenceUpdate {
	_u.mutation.ClearArgs()
	return _u
}

// SetEnv sets the "env" field.
func (_u *InferenceUpdate) SetEnv(v map[string]string) *InferenceUpdate {
	_u.mutation.SetEnv(v)
	return _u
}

// ClearEnv clears the value of the "env" field.
func (_u *InferenceUpdate) ClearEnv() *InferenceUpdate {
	_u.mutation.ClearEnv()
	return _u
}

// SetURL sets the "url" field.
func (_u *InferenceUpdate) SetURL(v string) *InferenceUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *InferenceUpdate) SetNillableURL(v *string) *InferenceUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// ClearURL clears the value of the "url" field.
func (_u *InferenceUpdate) ClearURL() *InferenceUpdate {
	_u.mutation.ClearURL()
	return _u
}

// SetAuthToken sets the "auth_token" field.
func (_u *InferenceUpdate) SetAuthToken(v string) *InferenceUpdate {
	_u.mutation.SetAuthToken(v)
	return _u
}

// SetNillableAuthToken sets the "auth_token" field if the given value is not nil.
func (_u *InferenceUpdate) SetNillableAuthToken(v *string) *InferenceUpdate {
	if v != nil {
		_u.SetAuthToken(*v)
	}
	return _u
}

// ClearAuthToken clears the value of the "auth_token" field.
func (_u *InferenceUpdate) ClearAuthToken() *InferenceUpdate {
	_u.mutation.ClearAuthToken()
	return _u
}

// SetQuota sets the "quota" field.
func (_u *InferenceUpdate) SetQuota(v *servicev1.Quota) *InferenceUpdate {
	_u.mutation.SetQuota(v)
	return _u
}

// ClearQuota clears the value of the "quota" field.
func (_u *InferenceUpdate) ClearQuota() *InferenceUpdate {
	_u.mutation.ClearQuota()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *InferenceUpdate) SetStartedAt(v time.Time) *InferenceUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *InferenceUpdate) SetNillableStartedAt(v *time.Time) *InferenceUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *InferenceUpdate) ClearStartedAt() *InferenceUpdate {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *InferenceUpdate) SetFinishedAt(v time.Time) *InferenceUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *InferenceUpdate) SetNillableFinishedAt(v *time.Time) *InferenceUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *InferenceUpdate) ClearFinishedAt() *InferenceUpdate {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetLastActivityTime sets the "last_activity_time" field.
func (_u *InferenceUpdate) SetLastActivityTime(v time.Time) *InferenceUpdate {
	_u.mutation.SetLastActivityTime(v)
	return _u
}

// SetNillableLastActivityTime sets the "last_activity_time" field if the given value is not nil.
func (_u *InferenceUpdate) SetNillableLastActivityTime(v *time.Time) *InferenceUpdate {
	if v != nil {
		_u.SetLastActivityTime(*v)
	}
	return _u
}

// ClearLastActivityTime clears the value of the "last_activity_time" field.
func (_u *InferenceUpdate) ClearLastActivityTime() *InferenceUpdate {
	_u.mutation.ClearLastActivityTime()
	return _u
}

// SetBillingDurationSec sets the "billing_duration_sec" field.
func (_u *InferenceUpdate) SetBillingDurationSec(v int64) *InferenceUpdate {
	_u.mutation.ResetBillingDurationSec()
	_u.mutation.SetBillingDurationSec(v)
	return _u
}

// SetNillableBillingDurationSec sets the "billing_duration_sec" field if the given value is not nil.
func (_u *InferenceUpdate) SetNillableBillingDurationSec(v *int64) *InferenceUpdate {
	if v != nil {
		_u.SetBillingDurationSec(*v)
	}
	return _u
}

// AddBillingDurationSec adds value to the "billing_duration_sec" field.
func (_u *InferenceUpdate) AddBillingDurationSec(v int64) *InferenceUpdate {
	_u.mutation.AddBillingDurationSec(v)
	return _u
}

// SetUsageCPUSeconds sets the "usage_cpu_seconds" field.
func (_u *InferenceUpdate) SetUsageCPUSeconds(v int64) *InferenceUpdate {
	_u.mutation.ResetUsageCPUSeconds()
	_u.mutation.SetUsageCPUSeconds(v)
	return _u
}

// SetNillableUsageCPUSeconds sets the "usage_cpu_seconds" field if the given value is not nil.
func (_u *InferenceUpdate) SetNillableUsageCPUSeconds(v *int64) *InferenceUpdate {
	if v != nil {
		_u.SetUsageCPUSeconds(*v)
	}
	return _u
}

// AddUsageCPUSeconds adds value to the "usage_cpu_seconds" field.
func (_u *InferenceUpdate) AddUsageCPUSeconds(v int64) *InferenceUpdate {
	_u.mutation.AddUsageCPUSeconds(v)
	return _u
}

// SetUsageGpuSeconds sets the "usage_gpu_seconds" field.
func (_u *InferenceUpdate) SetUsageGpuSeconds(v int64) *InferenceUpdate {
	_u.mutation.ResetUsageGpuSeconds()
	_u.mutation.SetUsageGpuSeconds(v)
	return _u
}

// SetNillableUsageGpuSeconds sets the "usage_gpu_seconds" field if the given value is not nil.
func (_u *InferenceUpdate) SetNillableUsageGpuSeconds(v *int64) *InferenceUpdate {
	if v != nil {
		_u.SetUsageGpuSeconds(*v)
	}
	return _u
}

// AddUsageGpuSeconds adds value to the "usage_gpu_seconds" field.
func (_u *InferenceUpdate) AddUsageGpuSeconds(v int64) *InferenceUpdate {
	_u.mutation.AddUsageGpuSeconds(v)
	return _u
}

// SetUsageReplicaSeconds sets the "usage_replica_seconds" field.
func (_u *InferenceUpdate) SetUsageReplicaSeconds(v int64) *InferenceUpdate {
	_u.mutation.ResetUsageReplicaSeconds()
	_u.mutation.SetUsageReplicaSeconds(v)
	return _u
}

// SetNillableUsageReplicaSeconds sets the "usage_replica_seconds" field if the given value is not nil.
func (_u *InferenceUpdate) SetNillableUsageReplicaSeconds(v *int64) *InferenceUpdate {
	if v != nil {
		_u.SetUsageReplicaSeconds(*v)
	}
	return _u
}

// AddUsageReplicaSeconds adds value to the "usage_replica_seconds" field.
func (_u *InferenceUpdate) AddUsageReplicaSeconds(v int64) *InferenceUpdate {
	_u.mutation.AddUsageReplicaSeconds(v)
	return _u
}

// SetExpirationMinutes sets the "expiration_minutes" field.
func (_u *InferenceUpdate) SetExpirationMinutes(v int64) *InferenceUpdate {
	_u.mutation.ResetExpirationMinutes()
	_u.mutation.SetExpirationMinutes(v)
	return _u
}

// SetNillableExpirationMinutes sets the "expiration_minutes" field if the given value is not nil.
func (_u *InferenceUpdate) SetNillableExpirationMinutes(v *int64) *InferenceUpdate {
	if v != nil {
		_u.SetExpirationMinutes(*v)
	}
	return _u
}

// AddExpirationMinutes adds value to the "expiration_minutes" field.
func (_u *InferenceUpdate) AddExpirationMinutes(v int64) *InferenceUpdate {
	_u.mutation.AddExpirationMinutes(v)
	return _u
}

// Mutation returns the InferenceMutation object of the builder.
func (_u *InferenceUpdate) Mutation() *InferenceMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InferenceUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InferenceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InferenceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InferenceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InferenceUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := inference.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Inference.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Replicas(); ok {
		if err := inference.ReplicasValidator(v); err != nil {
			return &ValidationError{Name: "replicas", err: fmt.Errorf(`ent: validator failed for field "Inference.replicas": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Quota(); ok {
		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "quota", err: fmt.Errorf(`ent: validator failed for field "Inference.quota": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *InferenceUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *InferenceUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *InferenceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(inference.Table, inference.Columns, sqlgraph.NewFieldSpec(inference.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(inference.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(inference.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(inference.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(inference.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(inference.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(inference.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(inference.FieldRemark, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(inference.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(inference.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(inference.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, inference.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(inference.FieldTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.IsEnabled(); ok {
		_spec.SetField(inference.FieldIsEnabled, field.TypeBool, value)
	}
	if _u.mutation.IsEnabledCleared() {
		_spec.ClearField(inference.FieldIsEnabled, field.TypeBool)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(inference.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(inference.FieldStatus, field.TypeEnum)
	}
	if value, ok := _u.mutation.ModelID(); ok {
		_spec.SetField(inference.FieldModelID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedModelID(); ok {
		_spec.AddField(inference.FieldModelID, field.TypeUint64, value)
	}
	if _u.mutation.ModelIDCleared() {
		_spec.ClearField(inference.FieldModelID, field.TypeUint64)
	}
	if value, ok := _u.mutation.ModelName(); ok {
		_spec.SetField(inference.FieldModelName, field.TypeString, value)
	}
	if _u.mutation.ModelNameCleared() {
		_spec.ClearField(inference.FieldModelName, field.TypeString)
	}
	if value, ok := _u.mutation.Image(); ok {
		_spec.SetField(inference.FieldImage, field.TypeString, value)
	}
	if _u.mutation.ImageCleared() {
		_spec.ClearField(inference.FieldImage, field.TypeString)
	}
	if value, ok := _u.mutation.Replicas(); ok {
		_spec.SetField(inference.FieldReplicas, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedReplicas(); ok {
		_spec.AddField(inference.FieldReplicas, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.MinReplicas(); ok {
		_spec.SetField(inference.FieldMinReplicas, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedMinReplicas(); ok {
		_spec.AddField(inference.FieldMinReplicas, field.TypeInt32, value)
	}
	if _u.mutation.MinReplicasCleared() {
		_spec.ClearField(inference.FieldMinReplicas, field.TypeInt32)
	}
	if value, ok := _u.mutation.MaxReplicas(); ok {
		_spec.SetField(inference.FieldMaxReplicas, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedMaxReplicas(); ok {
		_spec.AddField(inference.FieldMaxReplicas, field.TypeInt32, value)
	}
	if _u.mutation.MaxReplicasCleared() {
		_spec.ClearField(inference.FieldMaxReplicas, field.TypeInt32)
	}
	if value, ok := _u.mutation.Port(); ok {
		_spec.SetField(inference.FieldPort, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedPort(); ok {
		_spec.AddField(inference.FieldPort, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Command(); ok {
		_spec.SetField(inference.FieldCommand, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCommand(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, inference.FieldCommand, value)
		})
	}
	if _u.mutation.CommandCleared() {
		_spec.ClearField(inference.FieldCommand, field.TypeJSON)
	}
	if value, ok := _u.mutation.Args(); ok {
		_spec.SetField(inference.FieldArgs, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedArgs(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, inference.FieldArgs, value)
		})
	}
	if _u.mutation.ArgsCleared() {
		_spec.ClearField(inference.FieldArgs, field.TypeJSON)
	}
	if value, ok := _u.mutation.Env(); ok {
		_spec.SetField(inference.FieldEnv, field.TypeJSON, value)
	}
	if _u.mutation.EnvCleared() {
		_spec.ClearField(inference.FieldEnv, field.TypeJSON)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(inference.FieldURL, field.TypeString, value)
	}
	if _u.mutation.URLCleared() {
		_spec.ClearField(inference.FieldURL, field.TypeString)
	}
	if value, ok := _u.mutation.AuthToken(); ok {
		_spec.SetField(inference.FieldAuthToken, field.TypeString, value)
	}
	if _u.mutation.AuthTokenCleared() {
		_spec.ClearField(inference.FieldAuthToken, field.TypeString)
	}
	if value, ok := _u.mutation.Quota(); ok {
		_spec.SetField(inference.FieldQuota, field.TypeJSON, value)
	}
	if _u.mutation.QuotaCleared() {
		_spec.ClearField(inference.FieldQuota, field.TypeJSON)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(inference.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(inference.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(inference.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(inference.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastActivityTime(); ok {
		_spec.SetField(inference.FieldLastActivityTime, field.TypeTime, value)
	}
	if _u.mutation.LastActivityTimeCleared() {
		_spec.ClearField(inference.FieldLastActivityTime, field.TypeTime)
	}
	if value, ok := _u.mutation.BillingDurationSec(); ok {
		_spec.SetField(inference.FieldBillingDurationSec, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBillingDurationSec(); ok {
		_spec.AddField(inference.FieldBillingDurationSec, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UsageCPUSeconds(); ok {
		_spec.SetField(inference.FieldUsageCPUSeconds, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUsageCPUSeconds(); ok {
		_spec.AddField(inference.FieldUsageCPUSeconds, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UsageGpuSeconds(); ok {
		_spec.SetField(inference.FieldUsageGpuSeconds, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUsageGpuSeconds(); ok {
		_spec.AddField(inference.FieldUsageGpuSeconds, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UsageReplicaSeconds(); ok {
		_spec.SetField(inference.FieldUsageReplicaSeconds, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUsageReplicaSeconds(); ok {
		_spec.AddField(inference.FieldUsageReplicaSeconds, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ExpirationMinutes(); ok {
		_spec.SetField(inference.FieldExpirationMinutes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedExpirationMinutes(); ok {
		_spec.AddField(inference.FieldExpirationMinutes, field.TypeInt64, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{inference.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InferenceUpdateOne is the builder for updating a single Inference entity.
type InferenceUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *InferenceMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *InferenceUpdateOne) SetUpdatedAt(v time.Time) *InferenceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *InferenceUpdateOne) SetNillableUpdatedAt(v *time.Time) *InferenceUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *InferenceUpdateOne) ClearUpdatedAt() *InferenceUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *InferenceUpdateOne) SetDeletedAt(v time.Time) *InferenceUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *InferenceUpdateOne) SetNillableDeletedAt(v *time.Time) *InferenceUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *InferenceUpdateOne) ClearDeletedAt() *InferenceUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetRemark sets the "remark" field.
func (_u *InferenceUpdateOne) SetRemark(v string) *InferenceUpdateOne {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *InferenceUpdateOne) SetNillableRemark(v *string) *InferenceUpdateOne {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *InferenceUpdateOne) ClearRemark() *InferenceUpdateOne {
	_u.mutation.ClearRemark()
	return _u
}

// SetDescription sets the "description" field.
func (_u *InferenceUpdateOne) SetDescription(v string) *InferenceUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *InferenceUpdateOne) SetNillableDescription(v *string) *InferenceUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *InferenceUpdateOne) ClearDescription() *InferenceUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetTags sets the "tags" field.
func (_u *InferenceUpdateOne) SetTags(v []string) *InferenceUpdateOne {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *InferenceUpdateOne) AppendTags(v []string) *InferenceUpdateOne {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *InferenceUpdateOne) ClearTags() *InferenceUpdateOne {
	_u.mutation.ClearTags()
	return _u
}

// SetIsEnabled sets the "is_enabled" field.
func (_u *InferenceUpdateOne) SetIsEnabled(v bool) *InferenceUpdateOne {
	_u.mutation.SetIsEnabled(v)
	return _u
}

// SetNillableIsEnabled sets the "is_enabled" field if the given value is not nil.
func (_u *InferenceUpdateOne) SetNillableIsEnabled(v *bool) *InferenceUpdateOne {
	if v != nil {
		_u.SetIsEnabled(*v)
	}
	return _u
}

// ClearIsEnabled clears the value of the "is_enabled" field.
func (_u *InferenceUpdateOne) ClearIsEnabled() *InferenceUpdateOne {
	_u.mutation.ClearIsEnabled()
	return _u
}

// SetStatus sets the "status" field.
func (_u *InferenceUpdateOne) SetStatus(v inference.Status) *InferenceUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *InferenceUpdateOne) SetNillableStatus(v *inference.Status) *InferenceUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *InferenceUpdateOne) ClearStatus() *InferenceUpdateOne {
	_u.mutation.ClearStatus()
	return _u
}

// SetModelID sets the "model_id" field.
func (_u *InferenceUpdateOne) SetModelID(v uint64) *InferenceUpdateOne {
	_u.mutation.ResetModelID()
	_u.mutation.SetModelID(v)
	return _u
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (_u *InferenceUpdateOne) SetNillableModelID(v *uint64) *InferenceUpdateOne {
	if v != nil {
		_u.SetModelID(*v)
	}
	return _u
}

// AddModelID adds value to the "model_id" field.
func (_u *InferenceUpdateOne) AddModelID(v int64) *InferenceUpdateOne {
	_u.mutation.AddModelID(v)
	return _u
}

// ClearModelID clears the value of the "model_id" field.
func (_u *InferenceUpdateOne) ClearModelID() *InferenceUpdateOne {
	_u.mutation.ClearModelID()
	return _u
}

// SetModelName sets the "model_name" field.
func (_u *InferenceUpdateOne) SetModelName(v string) *InferenceUpdateOne {
	_u.mutation.SetModelName(v)
	return _u
}

// SetNillableModelName sets the "model_name" field if the given value is not nil.
func (_u *InferenceUpdateOne) SetNillableModelName(v *string) *InferenceUpdateOne {
	if v != nil {
		_u.SetModelName(*v)
	}
	return _u
}

// ClearModelName clears the value of the "model_name" field.
func (_u *InferenceUpdateOne) ClearModelName() *InferenceUpdateOne {
	_u.mutation.ClearModelName()
	return _u
}

// SetImage sets the "image" field.
func (_u *InferenceUpdateOne) SetImage(v string) *InferenceUpdateOne {
	_u.mutation.SetImage(v)
	return _u
}

// SetNillableImage sets the "image" field if the given value is not nil.
func (_u *InferenceUpdateOne) SetNillableImage(v *string) *InferenceUpdateOne {
	if v != nil {
		_u.SetImage(*v)
	}
	return _u
}

// ClearImage clears the value of the "image" field.
func (_u *InferenceUpdateOne) ClearImage() *InferenceUpdateOne {
	_u.mutation.ClearImage()
	return _u
}

// SetReplicas sets the "replicas" field.
func (_u *InferenceUpdateOne) SetReplicas(v int32) *InferenceUpdateOne {
	_u.mutation.ResetReplicas()
	_u.mutation.SetReplicas(v)
	return _u
}

// SetNillableReplicas sets the "replicas" field if the given value is not nil.
func (_u *InferenceUpdateOne) SetNillableReplicas(v *int32) *InferenceUpdateOne {
	if v != nil {
		_u.SetReplicas(*v)
	}
	return _u
}

// AddReplicas adds value to the "replicas" field.
func (_u *InferenceUpdateOne) AddReplicas(v int32) *InferenceUpdateOne {
	_u.mutation.AddReplicas(v)
	return _u
}

// SetMinReplicas sets the "min_replicas" field.
func (_u *InferenceUpdateOne) SetMinReplicas(v int32) *InferenceUpdateOne {
	_u.mutation.ResetMinReplicas()
	_u.mutation.SetMinReplicas(v)
	return _u
}

// SetNillableMinReplicas sets the "min_replicas" field if the given value is not nil.
func (_u *InferenceUpdateOne) SetNillableMinReplicas(v *int32) *InferenceUpdateOne {
	if v != nil {
		_u.SetMinReplicas(*v)
	}
	return _u
}

// AddMinReplicas adds value to the "min_replicas" field.
func (_u *InferenceUpdateOne) AddMinReplicas(v int32) *InferenceUpdateOne {
	_u.mutation.AddMinReplicas(v)
	return _u
}

// ClearMinReplicas clears the value of the "min_replicas" field.
func (_u *InferenceUpdateOne) ClearMinReplicas() *InferenceUpdateOne {
	_u.mutation.ClearMinReplicas()
	return _u
}

// SetMaxReplicas sets the "max_replicas" field.
func (_u *InferenceUpdateOne) SetMaxReplicas(v int32) *InferenceUpdateOne {
	_u.mutation.ResetMaxReplicas()
	_u.mutation.SetMaxReplicas(v)
	return _u
}

// SetNillableMaxReplicas sets the "max_replicas" field if the given value is not nil.
func (_u *InferenceUpdateOne) SetNillableMaxReplicas(v *int32) *InferenceUpdateOne {
	if v != nil {
		_u.SetMaxReplicas(*v)
	}
	return _u
}

// AddMaxReplicas adds value to the "max_replicas" field.
func (_u *InferenceUpdateOne) AddMaxReplicas(v int32) *InferenceUpdateOne {
	_u.mutation.AddMaxReplicas(v)
	return _u
}

// ClearMaxReplicas clears the value of the "max_replicas" field.
func (_u *InferenceUpdateOne) ClearMaxReplicas() *InferenceUpdateOne {
	_u.mutation.ClearMaxReplicas()
	return _u
}

// SetPort sets the "port" field.
func (_u *InferenceUpdateOne) SetPort(v int32) *InferenceUpdateOne {
	_u.mutation.ResetPort()
	_u.mutation.SetPort(v)
	return _u
}

// SetNillablePort sets the "port" field if the given value is not nil.
func (_u *InferenceUpdateOne) SetNillablePort(v *int32) *InferenceUpdateOne {
	if v != nil {
		_u.SetPort(*v)
	}
	return _u
}

// AddPort adds value to the "port" field.
func (_u *InferenceUpdateOne) AddPort(v int32) *InferenceUpdateOne {
	_u.mutation.AddPort(v)
	return _u
}

// SetCommand sets the "command" field.
func (_u *InferenceUpdateOne) SetCommand(v []string) *InferenceUpdateOne {
	_u.mutation.SetCommand(v)
	return _u
}

// AppendCommand appends value to the "command" field.
func (_u *InferenceUpdateOne) AppendCommand(v []string) *InferenceUpdateOne {
	_u.mutation.AppendCommand(v)
	return _u
}

// ClearCommand clears the value of the "command" field.
func (_u *InferenceUpdateOne) ClearCommand() *InferenceUpdateOne {
	_u.mutation.ClearCommand()
	return _u
}

// SetArgs sets the "args" field.
func (_u *InferenceUpdateOne) SetArgs(v []string) *InferenceUpdateOne {
	_u.mutation.SetArgs(v)
	return _u
}

// AppendArgs appends value to the "args" field.
func (_u *InferenceUpdateOne) AppendArgs(v []string) *InferenceUpdateOne {
	_u.mutation.AppendArgs(v)
	return _u
}

// ClearArgs clears the value of the "args" field.
func (_u *InferenceUpdateOne) ClearArgs() *InferenceUpdateOne {
	_u.mutation.ClearArgs()
	return _u
}

// SetEnv sets the "env" field.
func (_u *InferenceUpdateOne) SetEnv(v map[string]string) *InferenceUpdateOne {
	_u.mutation.SetEnv(v)
	return _u
}

// ClearEnv clears the value of the "env" field.
func (_u *InferenceUpdateOne) ClearEnv() *InferenceUpdateOne {
	_u.mutation.ClearEnv()
	return _u
}

// SetURL sets the "url" field.
func (_u *InferenceUpdateOne) SetURL(v string) *InferenceUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *InferenceUpdateOne) SetNillableURL(v *string) *InferenceUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// ClearURL clears the value of the "url" field.
func (_u *InferenceUpdateOne) ClearURL() *InferenceUpdateOne {
	_u.mutation.ClearURL()
	return _u
}

// SetAuthToken sets the "auth_token" field.
func (_u *InferenceUpdateOne) SetAuthToken(v string) *InferenceUpdateOne {
	_u.mutation.SetAuthToken(v)
	return _u
}

// SetNillableAuthToken sets the "auth_token" field if the given value is not nil.
func (_u *InferenceUpdateOne) SetNillableAuthToken(v *string) *InferenceUpdateOne {
	if v != nil {
		_u.SetAuthToken(*v)
	}
	return _u
}

// ClearAuthToken clears the value of the "auth_token" field.
func (_u *InferenceUpdateOne) ClearAuthToken() *InferenceUpdateOne {
	_u.mutation.ClearAuthToken()
	return _u
}

// SetQuota sets the "quota" field.
func (_u *InferenceUpdateOne) SetQuota(v *servicev1.Quota) *InferenceUpdateOne {
	_u.mutation.SetQuota(v)
	return _u
}

// ClearQuota clears the value of the "quota" field.
func (_u *InferenceUpdateOne) ClearQuota() *InferenceUpdateOne {
	_u.mutation.ClearQuota()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *InferenceUpdateOne) SetStartedAt(v time.Time) *InferenceUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *InferenceUpdateOne) SetNillableStartedAt(v *time.Time) *InferenceUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *InferenceUpdateOne) ClearStartedAt() *InferenceUpdateOne {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *InferenceUpdateOne) SetFinishedAt(v time.Time) *InferenceUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *InferenceUpdateOne) SetNillableFinishedAt(v *time.Time) *InferenceUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *InferenceUpdateOne) ClearFinishedAt() *InferenceUpdateOne {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetLastActivityTime sets the "last_activity_time" field.
func (_u *InferenceUpdateOne) SetLastActivityTime(v time.Time) *InferenceUpdateOne {
	_u.mutation.SetLastActivityTime(v)
	return _u
}

// SetNillableLastActivityTime sets the "last_activity_time" field if the given value is not nil.
func (_u *InferenceUpdateOne) SetNillableLastActivityTime(v *time.Time) *InferenceUpdateOne {
	if v != nil {
		_u.SetLastActivityTime(*v)
	}
	return _u
}

// ClearLastActivityTime clears the value of the "last_activity_time" field.
func (_u *InferenceUpdateOne) ClearLastActivityTime() *InferenceUpdateOne {
	_u.mutation.ClearLastActivityTime()
	return _u
}

// SetBillingDurationSec sets the "billing_duration_sec" field.
func (_u *InferenceUpdateOne) SetBillingDurationSec(v int64) *InferenceUpdateOne {
	_u.mutation.ResetBillingDurationSec()
	_u.mutation.SetBillingDurationSec(v)
	return _u
}

// SetNillableBillingDurationSec sets the "billing_duration_sec" field if the given value is not nil.
func (_u *InferenceUpdateOne) SetNillableBillingDurationSec(v *int64) *InferenceUpdateOne {
	if v != nil {
		_u.SetBillingDurationSec(*v)
	}
	return _u
}

// AddBillingDurationSec adds value to the "billing_duration_sec" field.
func (_u *InferenceUpdateOne) AddBillingDurationSec(v int64) *InferenceUpdateOne {
	_u.mutation.AddBillingDurationSec(v)
	return _u
}

// SetUsageCPUSeconds sets the "usage_cpu_seconds" field.
func (_u *InferenceUpdateOne) SetUsageCPUSeconds(v int64) *InferenceUpdateOne {
	_u.mutation.ResetUsageCPUSeconds()
	_u.mutation.SetUsageCPUSeconds(v)
	return _u
}

// SetNillableUsageCPUSeconds sets the "usage_cpu_seconds" field if the given value is not nil.
func (_u *InferenceUpdateOne) SetNillableUsageCPUSeconds(v *int64) *InferenceUpdateOne {
	if v != nil {
		_u.SetUsageCPUSeconds(*v)
	}
	return _u
}

// AddUsageCPUSeconds adds value to the "usage_cpu_seconds" field.
func (_u *InferenceUpdateOne) AddUsageCPUSeconds(v int64) *InferenceUpdateOne {
	_u.mutation.AddUsageCPUSeconds(v)
	return _u
}

// SetUsageGpuSeconds sets the "usage_gpu_seconds" field.
func (_u *InferenceUpdateOne) SetUsageGpuSeconds(v int64) *InferenceUpdateOne {
	_u.mutation.ResetUsageGpuSeconds()
	_u.mutation.SetUsageGpuSeconds(v)
	return _u
}

// SetNillableUsageGpuSeconds sets the "usage_gpu_seconds" field if the given value is not nil.
func (_u *InferenceUpdateOne) SetNillableUsageGpuSeconds(v *int64) *InferenceUpdateOne {
	if v != nil {
		_u.SetUsageGpuSeconds(*v)
	}
	return _u
}

// AddUsageGpuSeconds adds value to the "usage_gpu_seconds" field.
func (_u *InferenceUpdateOne) AddUsageGpuSeconds(v int64) *InferenceUpdateOne {
	_u.mutation.AddUsageGpuSeconds(v)
	return _u
}

// SetUsageReplicaSeconds sets the "usage_replica_seconds" field.
func (_u *InferenceUpdateOne) SetUsageReplicaSeconds(v int64) *InferenceUpdateOne {
	_u.mutation.ResetUsageReplicaSeconds()
	_u.mutation.SetUsageReplicaSeconds(v)
	return _u
}

// SetNillableUsageReplicaSeconds sets the "usage_replica_seconds" field if the given value is not nil.
func (_u *InferenceUpdateOne) SetNillableUsageReplicaSeconds(v *int64) *InferenceUpdateOne {
	if v != nil {
		_u.SetUsageReplicaSeconds(*v)
	}
	return _u
}

// AddUsageReplicaSeconds adds value to the "usage_replica_seconds" field.
func (_u *InferenceUpdateOne) AddUsageReplicaSeconds(v int64) *InferenceUpdateOne {
	_u.mutation.AddUsageReplicaSeconds(v)
	return _u
}

// SetExpirationMinutes sets the "expiration_minutes" field.
func (_u *InferenceUpdateOne) SetExpirationMinutes(v int64) *InferenceUpdateOne {
	_u.mutation.ResetExpirationMinutes()
	_u.mutation.SetExpirationMinutes(v)
	return _u
}

// SetNillableExpirationMinutes sets the "expiration_minutes" field if the given value is not nil.
func (_u *InferenceUpdateOne) SetNillableExpirationMinutes(v *int64) *InferenceUpdateOne {
	if v != nil {
		_u.SetExpirationMinutes(*v)
	}
	return _u
}

// AddExpirationMinutes adds value to the "expiration_minutes" field.
func (_u *InferenceUpdateOne) AddExpirationMinutes(v int64) *InferenceUpdateOne {
	_u.mutation.AddExpirationMinutes(v)
	return _u
}

// Mutation returns the InferenceMutation object of the builder.
func (_u *InferenceUpdateOne) Mutation() *InferenceMutation {
	return _u.mutation
}

// Where appends a list predicates to the InferenceUpdate builder.
func (_u *InferenceUpdateOne) Where(ps ...predicate.Inference) *InferenceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InferenceUpdateOne) Select(field string, fields ...string) *InferenceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Inference entity.
func (_u *InferenceUpdateOne) Save(ctx context.Context) (*Inference, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InferenceUpdateOne) SaveX(ctx context.Context) *Inference {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InferenceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InferenceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InferenceUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := inference.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Inference.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Replicas(); ok {
		if err := inference.ReplicasValidator(v); err != nil {
			return &ValidationError{Name: "replicas", err: fmt.Errorf(`ent: validator failed for field "Inference.replicas": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Quota(); ok {
		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "quota", err: fmt.Errorf(`ent: validator failed for field "Inference.quota": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *InferenceUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *InferenceUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *InferenceUpdateOne) sqlSave(ctx context.Context) (_node *Inference, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(inference.Table, inference.Columns, sqlgraph.NewFieldSpec(inference.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Inference.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, inference.FieldID)
		for _, f := range fields {
			if !inference.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != inference.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(inference.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(inference.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(inference.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(inference.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(inference.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(inference.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(inference.FieldRemark, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(inference.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(inference.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(inference.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, inference.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(inference.FieldTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.IsEnabled(); ok {
		_spec.SetField(inference.FieldIsEnabled, field.TypeBool, value)
	}
	if _u.mutation.IsEnabledCleared() {
		_spec.ClearField(inference.FieldIsEnabled, field.TypeBool)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(inference.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(inference.FieldStatus, field.TypeEnum)
	}
	if value, ok := _u.mutation.ModelID(); ok {
		_spec.SetField(inference.FieldModelID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedModelID(); ok {
		_spec.AddField(inference.FieldModelID, field.TypeUint64, value)
	}
	if _u.mutation.ModelIDCleared() {
		_spec.ClearField(inference.FieldModelID, field.TypeUint64)
	}
	if value, ok := _u.mutation.ModelName(); ok {
		_spec.SetField(inference.FieldModelName, field.TypeString, value)
	}
	if _u.mutation.ModelNameCleared() {
		_spec.ClearField(inference.FieldModelName, field.TypeString)
	}
	if value, ok := _u.mutation.Image(); ok {
		_spec.SetField(inference.FieldImage, field.TypeString, value)
	}
	if _u.mutation.ImageCleared() {
		_spec.ClearField(inference.FieldImage, field.TypeString)
	}
	if value, ok := _u.mutation.Replicas(); ok {
		_spec.SetField(inference.FieldReplicas, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedReplicas(); ok {
		_spec.AddField(inference.FieldReplicas, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.MinReplicas(); ok {
		_spec.SetField(inference.FieldMinReplicas, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedMinReplicas(); ok {
		_spec.AddField(inference.FieldMinReplicas, field.TypeInt32, value)
	}
	if _u.mutation.MinReplicasCleared() {
		_spec.ClearField(inference.FieldMinReplicas, field.TypeInt32)
	}
	if value, ok := _u.mutation.MaxReplicas(); ok {
		_spec.SetField(inference.FieldMaxReplicas, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedMaxReplicas(); ok {
		_spec.AddField(inference.FieldMaxReplicas, field.TypeInt32, value)
	}
	if _u.mutation.MaxReplicasCleared() {
		_spec.ClearField(inference.FieldMaxReplicas, field.TypeInt32)
	}
	if value, ok := _u.mutation.Port(); ok {
		_spec.SetField(inference.FieldPort, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedPort(); ok {
		_spec.AddField(inference.FieldPort, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Command(); ok {
		_spec.SetField(inference.FieldCommand, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCommand(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, inference.FieldCommand, value)
		})
	}
	if _u.mutation.CommandCleared() {
		_spec.ClearField(inference.FieldCommand, field.TypeJSON)
	}
	if value, ok := _u.mutation.Args(); ok {
		_spec.SetField(inference.FieldArgs, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedArgs(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, inference.FieldArgs, value)
		})
	}
	if _u.mutation.ArgsCleared() {
		_spec.ClearField(inference.FieldArgs, field.TypeJSON)
	}
	if value, ok := _u.mutation.Env(); ok {
		_spec.SetField(inference.FieldEnv, field.TypeJSON, value)
	}
	if _u.mutation.EnvCleared() {
		_spec.ClearField(inference.FieldEnv, field.TypeJSON)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(inference.FieldURL, field.TypeString, value)
	}
	if _u.mutation.URLCleared() {
		_spec.ClearField(inference.FieldURL, field.TypeString)
	}
	if value, ok := _u.mutation.AuthToken(); ok {
		_spec.SetField(inference.FieldAuthToken, field.TypeString, value)
	}
	if _u.mutation.AuthTokenCleared() {
		_spec.ClearField(inference.FieldAuthToken, field.TypeString)
	}
	if value, ok := _u.mutation.Quota(); ok {
		_spec.SetField(inference.FieldQuota, field.TypeJSON, value)
	}
	if _u.mutation.QuotaCleared() {
		_spec.ClearField(inference.FieldQuota, field.TypeJSON)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(inference.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(inference.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(inference.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(inference.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastActivityTime(); ok {
		_spec.SetField(inference.FieldLastActivityTime, field.TypeTime, value)
	}
	if _u.mutation.LastActivityTimeCleared() {
		_spec.ClearField(inference.FieldLastActivityTime, field.TypeTime)
	}
	if value, ok := _u.mutation.BillingDurationSec(); ok {
		_spec.SetField(inference.FieldBillingDurationSec, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBillingDurationSec(); ok {
		_spec.AddField(inference.FieldBillingDurationSec, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UsageCPUSeconds(); ok {
		_spec.SetField(inference.FieldUsageCPUSeconds, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUsageCPUSeconds(); ok {
		_spec.AddField(inference.FieldUsageCPUSeconds, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UsageGpuSeconds(); ok {
		_spec.SetField(inference.FieldUsageGpuSeconds, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUsageGpuSeconds(); ok {
		_spec.AddField(inference.FieldUsageGpuSeconds, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UsageReplicaSeconds(); ok {
		_spec.SetField(inference.FieldUsageReplicaSeconds, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUsageReplicaSeconds(); ok {
		_spec.AddField(inference.FieldUsageReplicaSeconds, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ExpirationMinutes(); ok {
		_spec.SetField(inference.FieldExpirationMinutes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedExpirationMinutes(); ok {
		_spec.AddField(inference.FieldExpirationMinutes, field.TypeInt64, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Inference{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{inference.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
