// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-admin/app/server/service/internal/data/ent/model"
	"go-wind-admin/app/server/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// ModelUpdate is the builder for updating Model entities.
type ModelUpdate struct {
	config
	hooks     []Hook
	mutation  *ModelMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ModelUpdate builder.
func (_u *ModelUpdate) Where(ps ...predicate.Model) *ModelUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModelUpdate) SetUpdatedAt(v time.Time) *ModelUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *ModelUpdate) SetNillableUpdatedAt(v *time.Time) *ModelUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *ModelUpdate) ClearUpdatedAt() *ModelUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ModelUpdate) SetDeletedAt(v time.Time) *ModelUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ModelUpdate) SetNillableDeletedAt(v *time.Time) *ModelUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ModelUpdate) ClearDeletedAt() *ModelUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetRemark sets the "remark" field.
func (_u *ModelUpdate) SetRemark(v string) *ModelUpdate {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *ModelUpdate) SetNillableRemark(v *string) *ModelUpdate {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *ModelUpdate) ClearRemark() *ModelUpdate {
	_u.mutation.ClearRemark()
	return _u
}

// SetDescription sets the "description" field.
func (_u *ModelUpdate) SetDescription(v string) *ModelUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ModelUpdate) SetNillableDescription(v *string) *ModelUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ModelUpdate) ClearDescription() *ModelUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetTags sets the "tags" field.
func (_u *ModelUpdate) SetTags(v []string) *ModelUpdate {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *ModelUpdate) AppendTags(v []string) *ModelUpdate {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *ModelUpdate) ClearTags() *ModelUpdate {
	_u.mutation.ClearTags()
	return _u
}

// SetIsEnabled sets the "is_enabled" field.
func (_u *ModelUpdate) SetIsEnabled(v bool) *ModelUpdate {
	_u.mutation.SetIsEnabled(v)
	return _u
}

// SetNillableIsEnabled sets the "is_enabled" field if the given value is not nil.
func (_u *ModelUpdate) SetNillableIsEnabled(v *bool) *ModelUpdate {
	if v != nil {
		_u.SetIsEnabled(*v)
	}
	return _u
}

// ClearIsEnabled clears the value of the "is_enabled" field.
func (_u *ModelUpdate) ClearIsEnabled() *ModelUpdate {
	_u.mutation.ClearIsEnabled()
	return _u
}

// SetSlug sets the "slug" field.
func (_u *ModelUpdate) SetSlug(v string) *ModelUpdate {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *ModelUpdate) SetNillableSlug(v *string) *ModelUpdate {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// ClearSlug clears the value of the "slug" field.
func (_u *ModelUpdate) ClearSlug() *ModelUpdate {
	_u.mutation.ClearSlug()
	return _u
}

// SetDockerImageRef sets the "docker_image_ref" field.
func (_u *ModelUpdate) SetDockerImageRef(v string) *ModelUpdate {
	_u.mutation.SetDockerImageRef(v)
	return _u
}

// SetNillableDockerImageRef sets the "docker_image_ref" field if the given value is not nil.
func (_u *ModelUpdate) SetNillableDockerImageRef(v *string) *ModelUpdate {
	if v != nil {
		_u.SetDockerImageRef(*v)
	}
	return _u
}

// ClearDockerImageRef clears the value of the "docker_image_ref" field.
func (_u *ModelUpdate) ClearDockerImageRef() *ModelUpdate {
	_u.mutation.ClearDockerImageRef()
	return _u
}

// SetJupyterCommand sets the "jupyter_command" field.
func (_u *ModelUpdate) SetJupyterCommand(v []string) *ModelUpdate {
	_u.mutation.SetJupyterCommand(v)
	return _u
}

// AppendJupyterCommand appends value to the "jupyter_command" field.
func (_u *ModelUpdate) AppendJupyterCommand(v []string) *ModelUpdate {
	_u.mutation.AppendJupyterCommand(v)
	return _u
}

// ClearJupyterCommand clears the value of the "jupyter_command" field.
func (_u *ModelUpdate) ClearJupyterCommand() *ModelUpdate {
	_u.mutation.ClearJupyterCommand()
	return _u
}

// SetVllmCommand sets the "vllm_command" field.
func (_u *ModelUpdate) SetVllmCommand(v []string) *ModelUpdate {
	_u.mutation.SetVllmCommand(v)
	return _u
}

// AppendVllmCommand appends value to the "vllm_command" field.
func (_u *ModelUpdate) AppendVllmCommand(v []string) *ModelUpdate {
	_u.mutation.AppendVllmCommand(v)
	return _u
}

// ClearVllmCommand clears the value of the "vllm_command" field.
func (_u *ModelUpdate) ClearVllmCommand() *ModelUpdate {
	_u.mutation.ClearVllmCommand()
	return _u
}

// SetCommandMapping sets the "command_mapping" field.
func (_u *ModelUpdate) SetCommandMapping(v map[string]string) *ModelUpdate {
	_u.mutation.SetCommandMapping(v)
	return _u
}

// ClearCommandMapping clears the value of the "command_mapping" field.
func (_u *ModelUpdate) ClearCommandMapping() *ModelUpdate {
	_u.mutation.ClearCommandMapping()
	return _u
}

// SetEnv sets the "env" field.
func (_u *ModelUpdate) SetEnv(v map[string]string) *ModelUpdate {
	_u.mutation.SetEnv(v)
	return _u
}

// ClearEnv clears the value of the "env" field.
func (_u *ModelUpdate) ClearEnv() *ModelUpdate {
	_u.mutation.ClearEnv()
	return _u
}

// SetPorts sets the "ports" field.
func (_u *ModelUpdate) SetPorts(v []int) *ModelUpdate {
	_u.mutation.SetPorts(v)
	return _u
}

// AppendPorts appends value to the "ports" field.
func (_u *ModelUpdate) AppendPorts(v []int) *ModelUpdate {
	_u.mutation.AppendPorts(v)
	return _u
}

// ClearPorts clears the value of the "ports" field.
func (_u *ModelUpdate) ClearPorts() *ModelUpdate {
	_u.mutation.ClearPorts()
	return _u
}

// SetWritablePaths sets the "writable_paths" field.
func (_u *ModelUpdate) SetWritablePaths(v []string) *ModelUpdate {
	_u.mutation.SetWritablePaths(v)
	return _u
}

// AppendWritablePaths appends value to the "writable_paths" field.
func (_u *ModelUpdate) AppendWritablePaths(v []string) *ModelUpdate {
	_u.mutation.AppendWritablePaths(v)
	return _u
}

// ClearWritablePaths clears the value of the "writable_paths" field.
func (_u *ModelUpdate) ClearWritablePaths() *ModelUpdate {
	_u.mutation.ClearWritablePaths()
	return _u
}

// SetBaseFramework sets the "base_framework" field.
func (_u *ModelUpdate) SetBaseFramework(v string) *ModelUpdate {
	_u.mutation.SetBaseFramework(v)
	return _u
}

// SetNillableBaseFramework sets the "base_framework" field if the given value is not nil.
func (_u *ModelUpdate) SetNillableBaseFramework(v *string) *ModelUpdate {
	if v != nil {
		_u.SetBaseFramework(*v)
	}
	return _u
}

// ClearBaseFramework clears the value of the "base_framework" field.
func (_u *ModelUpdate) ClearBaseFramework() *ModelUpdate {
	_u.mutation.ClearBaseFramework()
	return _u
}

// SetType sets the "type" field.
func (_u *ModelUpdate) SetType(v model.Type) *ModelUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *ModelUpdate) SetNillableType(v *model.Type) *ModelUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// ClearType clears the value of the "type" field.
func (_u *ModelUpdate) ClearType() *ModelUpdate {
	_u.mutation.ClearType()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ModelUpdate) SetStatus(v model.Status) *ModelUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ModelUpdate) SetNillableStatus(v *model.Status) *ModelUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *ModelUpdate) ClearStatus() *ModelUpdate {
	_u.mutation.ClearStatus()
	return _u
}

// SetReadmeText sets the "readme_text" field.
func (_u *ModelUpdate) SetReadmeText(v string) *ModelUpdate {
	_u.mutation.SetReadmeText(v)
	return _u
}

// SetNillableReadmeText sets the "readme_text" field if the given value is not nil.
func (_u *ModelUpdate) SetNillableReadmeText(v *string) *ModelUpdate {
	if v != nil {
		_u.SetReadmeText(*v)
	}
	return _u
}

// ClearReadmeText clears the value of the "readme_text" field.
func (_u *ModelUpdate) ClearReadmeText() *ModelUpdate {
	_u.mutation.ClearReadmeText()
	return _u
}

// SetDownloads sets the "downloads" field.
func (_u *ModelUpdate) SetDownloads(v int64) *ModelUpdate {
	_u.mutation.ResetDownloads()
	_u.mutation.SetDownloads(v)
	return _u
}

// SetNillableDownloads sets the "downloads" field if the given value is not nil.
func (_u *ModelUpdate) SetNillableDownloads(v *int64) *ModelUpdate {
	if v != nil {
		_u.SetDownloads(*v)
	}
	return _u
}

// AddDownloads adds value to the "downloads" field.
func (_u *ModelUpdate) AddDownloads(v int64) *ModelUpdate {
	_u.mutation.AddDownloads(v)
	return _u
}

// ClearDownloads clears the value of the "downloads" field.
func (_u *ModelUpdate) ClearDownloads() *ModelUpdate {
	_u.mutation.ClearDownloads()
	return _u
}

// SetLikes sets the "likes" field.
func (_u *ModelUpdate) SetLikes(v int64) *ModelUpdate {
	_u.mutation.ResetLikes()
	_u.mutation.SetLikes(v)
	return _u
}

// SetNillableLikes sets the "likes" field if the given value is not nil.
func (_u *ModelUpdate) SetNillableLikes(v *int64) *ModelUpdate {
	if v != nil {
		_u.SetLikes(*v)
	}
	return _u
}

// AddLikes adds value to the "likes" field.
func (_u *ModelUpdate) AddLikes(v int64) *ModelUpdate {
	_u.mutation.AddLikes(v)
	return _u
}

// ClearLikes clears the value of the "likes" field.
func (_u *ModelUpdate) ClearLikes() *ModelUpdate {
	_u.mutation.ClearLikes()
	return _u
}

// SetLicense sets the "license" field.
func (_u *ModelUpdate) SetLicense(v string) *ModelUpdate {
	_u.mutation.SetLicense(v)
	return _u
}

// SetNillableLicense sets the "license" field if the given value is not nil.
func (_u *ModelUpdate) SetNillableLicense(v *string) *ModelUpdate {
	if v != nil {
		_u.SetLicense(*v)
	}
	return _u
}

// ClearLicense clears the value of the "license" field.
func (_u *ModelUpdate) ClearLicense() *ModelUpdate {
	_u.mutation.ClearLicense()
	return _u
}

// SetModelSize sets the "model_size" field.
func (_u *ModelUpdate) SetModelSize(v int64) *ModelUpdate {
	_u.mutation.ResetModelSize()
	_u.mutation.SetModelSize(v)
	return _u
}

// SetNillableModelSize sets the "model_size" field if the given value is not nil.
func (_u *ModelUpdate) SetNillableModelSize(v *int64) *ModelUpdate {
	if v != nil {
		_u.SetModelSize(*v)
	}
	return _u
}

// AddModelSize adds value to the "model_size" field.
func (_u *ModelUpdate) AddModelSize(v int64) *ModelUpdate {
	_u.mutation.AddModelSize(v)
	return _u
}

// ClearModelSize clears the value of the "model_size" field.
func (_u *ModelUpdate) ClearModelSize() *ModelUpdate {
	_u.mutation.ClearModelSize()
	return _u
}

// Mutation returns the ModelMutation object of the builder.
func (_u *ModelUpdate) Mutation() *ModelMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ModelUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ModelUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelUpdate) check() error {
	if v, ok := _u.mutation.Slug(); ok {
		if err := model.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Model.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DockerImageRef(); ok {
		if err := model.DockerImageRefValidator(v); err != nil {
			return &ValidationError{Name: "docker_image_ref", err: fmt.Errorf(`ent: validator failed for field "Model.docker_image_ref": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := model.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Model.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := model.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Model.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Downloads(); ok {
		if err := model.DownloadsValidator(v); err != nil {
			return &ValidationError{Name: "downloads", err: fmt.Errorf(`ent: validator failed for field "Model.downloads": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Likes(); ok {
		if err := model.LikesValidator(v); err != nil {
			return &ValidationError{Name: "likes", err: fmt.Errorf(`ent: validator failed for field "Model.likes": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ModelSize(); ok {
		if err := model.ModelSizeValidator(v); err != nil {
			return &ValidationError{Name: "model_size", err: fmt.Errorf(`ent: validator failed for field "Model.model_size": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ModelUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ModelUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ModelUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(model.Table, model.Columns, sqlgraph.NewFieldSpec(model.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(model.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(model.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(model.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(model.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(model.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(model.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(model.FieldRemark, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(model.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(model.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(model.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, model.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(model.FieldTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.IsEnabled(); ok {
		_spec.SetField(model.FieldIsEnabled, field.TypeBool, value)
	}
	if _u.mutation.IsEnabledCleared() {
		_spec.ClearField(model.FieldIsEnabled, field.TypeBool)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(model.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(model.FieldSlug, field.TypeString, value)
	}
	if _u.mutation.SlugCleared() {
		_spec.ClearField(model.FieldSlug, field.TypeString)
	}
	if value, ok := _u.mutation.DockerImageRef(); ok {
		_spec.SetField(model.FieldDockerImageRef, field.TypeString, value)
	}
	if _u.mutation.DockerImageRefCleared() {
		_spec.ClearField(model.FieldDockerImageRef, field.TypeString)
	}
	if value, ok := _u.mutation.JupyterCommand(); ok {
		_spec.SetField(model.FieldJupyterCommand, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedJupyterCommand(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, model.FieldJupyterCommand, value)
		})
	}
	if _u.mutation.JupyterCommandCleared() {
		_spec.ClearField(model.FieldJupyterCommand, field.TypeJSON)
	}
	if value, ok := _u.mutation.VllmCommand(); ok {
		_spec.SetField(model.FieldVllmCommand, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedVllmCommand(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, model.FieldVllmCommand, value)
		})
	}
	if _u.mutation.VllmCommandCleared() {
		_spec.ClearField(model.FieldVllmCommand, field.TypeJSON)
	}
	if value, ok := _u.mutation.CommandMapping(); ok {
		_spec.SetField(model.FieldCommandMapping, field.TypeJSON, value)
	}
	if _u.mutation.CommandMappingCleared() {
		_spec.ClearField(model.FieldCommandMapping, field.TypeJSON)
	}
	if value, ok := _u.mutation.Env(); ok {
		_spec.SetField(model.FieldEnv, field.TypeJSON, value)
	}
	if _u.mutation.EnvCleared() {
		_spec.ClearField(model.FieldEnv, field.TypeJSON)
	}
	if value, ok := _u.mutation.Ports(); ok {
		_spec.SetField(model.FieldPorts, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPorts(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, model.FieldPorts, value)
		})
	}
	if _u.mutation.PortsCleared() {
		_spec.ClearField(model.FieldPorts, field.TypeJSON)
	}
	if value, ok := _u.mutation.WritablePaths(); ok {
		_spec.SetField(model.FieldWritablePaths, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedWritablePaths(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, model.FieldWritablePaths, value)
		})
	}
	if _u.mutation.WritablePathsCleared() {
		_spec.ClearField(model.FieldWritablePaths, field.TypeJSON)
	}
	if value, ok := _u.mutation.BaseFramework(); ok {
		_spec.SetField(model.FieldBaseFramework, field.TypeString, value)
	}
	if _u.mutation.BaseFrameworkCleared() {
		_spec.ClearField(model.FieldBaseFramework, field.TypeString)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(model.FieldType, field.TypeEnum, value)
	}
	if _u.mutation.TypeCleared() {
		_spec.ClearField(model.FieldType, field.TypeEnum)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(model.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(model.FieldStatus, field.TypeEnum)
	}
	if value, ok := _u.mutation.ReadmeText(); ok {
		_spec.SetField(model.FieldReadmeText, field.TypeString, value)
	}
	if _u.mutation.ReadmeTextCleared() {
		_spec.ClearField(model.FieldReadmeText, field.TypeString)
	}
	if value, ok := _u.mutation.Downloads(); ok {
		_spec.SetField(model.FieldDownloads, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDownloads(); ok {
		_spec.AddField(model.FieldDownloads, field.TypeInt64, value)
	}
	if _u.mutation.DownloadsCleared() {
		_spec.ClearField(model.FieldDownloads, field.TypeInt64)
	}
	if value, ok := _u.mutation.Likes(); ok {
		_spec.SetField(model.FieldLikes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLikes(); ok {
		_spec.AddField(model.FieldLikes, field.TypeInt64, value)
	}
	if _u.mutation.LikesCleared() {
		_spec.ClearField(model.FieldLikes, field.TypeInt64)
	}
	if value, ok := _u.mutation.License(); ok {
		_spec.SetField(model.FieldLicense, field.TypeString, value)
	}
	if _u.mutation.LicenseCleared() {
		_spec.ClearField(model.FieldLicense, field.TypeString)
	}
	if value, ok := _u.mutation.ModelSize(); ok {
		_spec.SetField(model.FieldModelSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedModelSize(); ok {
		_spec.AddField(model.FieldModelSize, field.TypeInt64, value)
	}
	if _u.mutation.ModelSizeCleared() {
		_spec.ClearField(model.FieldModelSize, field.TypeInt64)
	}
	if _u.mutation.UUIDCleared() {
		_spec.ClearField(model.FieldUUID, field.TypeUUID)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{model.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ModelUpdateOne is the builder for updating a single Model entity.
type ModelUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ModelMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModelUpdateOne) SetUpdatedAt(v time.Time) *ModelUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *ModelUpdateOne) SetNillableUpdatedAt(v *time.Time) *ModelUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *ModelUpdateOne) ClearUpdatedAt() *ModelUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ModelUpdateOne) SetDeletedAt(v time.Time) *ModelUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ModelUpdateOne) SetNillableDeletedAt(v *time.Time) *ModelUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ModelUpdateOne) ClearDeletedAt() *ModelUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetRemark sets the "remark" field.
func (_u *ModelUpdateOne) SetRemark(v string) *ModelUpdateOne {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *ModelUpdateOne) SetNillableRemark(v *string) *ModelUpdateOne {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *ModelUpdateOne) ClearRemark() *ModelUpdateOne {
	_u.mutation.ClearRemark()
	return _u
}

// SetDescription sets the "description" field.
func (_u *ModelUpdateOne) SetDescription(v string) *ModelUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ModelUpdateOne) SetNillableDescription(v *string) *ModelUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ModelUpdateOne) ClearDescription() *ModelUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetTags sets the "tags" field.
func (_u *ModelUpdateOne) SetTags(v []string) *ModelUpdateOne {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *ModelUpdateOne) AppendTags(v []string) *ModelUpdateOne {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *ModelUpdateOne) ClearTags() *ModelUpdateOne {
	_u.mutation.ClearTags()
	return _u
}

// SetIsEnabled sets the "is_enabled" field.
func (_u *ModelUpdateOne) SetIsEnabled(v bool) *ModelUpdateOne {
	_u.mutation.SetIsEnabled(v)
	return _u
}

// SetNillableIsEnabled sets the "is_enabled" field if the given value is not nil.
func (_u *ModelUpdateOne) SetNillableIsEnabled(v *bool) *ModelUpdateOne {
	if v != nil {
		_u.SetIsEnabled(*v)
	}
	return _u
}

// ClearIsEnabled clears the value of the "is_enabled" field.
func (_u *ModelUpdateOne) ClearIsEnabled() *ModelUpdateOne {
	_u.mutation.ClearIsEnabled()
	return _u
}

// SetSlug sets the "slug" field.
func (_u *ModelUpdateOne) SetSlug(v string) *ModelUpdateOne {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *ModelUpdateOne) SetNillableSlug(v *string) *ModelUpdateOne {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// ClearSlug clears the value of the "slug" field.
func (_u *ModelUpdateOne) ClearSlug() *ModelUpdateOne {
	_u.mutation.ClearSlug()
	return _u
}

// SetDockerImageRef sets the "docker_image_ref" field.
func (_u *ModelUpdateOne) SetDockerImageRef(v string) *ModelUpdateOne {
	_u.mutation.SetDockerImageRef(v)
	return _u
}

// SetNillableDockerImageRef sets the "docker_image_ref" field if the given value is not nil.
func (_u *ModelUpdateOne) SetNillableDockerImageRef(v *string) *ModelUpdateOne {
	if v != nil {
		_u.SetDockerImageRef(*v)
	}
	return _u
}

// ClearDockerImageRef clears the value of the "docker_image_ref" field.
func (_u *ModelUpdateOne) ClearDockerImageRef() *ModelUpdateOne {
	_u.mutation.ClearDockerImageRef()
	return _u
}

// SetJupyterCommand sets the "jupyter_command" field.
func (_u *ModelUpdateOne) SetJupyterCommand(v []string) *ModelUpdateOne {
	_u.mutation.SetJupyterCommand(v)
	return _u
}

// AppendJupyterCommand appends value to the "jupyter_command" field.
func (_u *ModelUpdateOne) AppendJupyterCommand(v []string) *ModelUpdateOne {
	_u.mutation.AppendJupyterCommand(v)
	return _u
}

// ClearJupyterCommand clears the value of the "jupyter_command" field.
func (_u *ModelUpdateOne) ClearJupyterCommand() *ModelUpdateOne {
	_u.mutation.ClearJupyterCommand()
	return _u
}

// SetVllmCommand sets the "vllm_command" field.
func (_u *ModelUpdateOne) SetVllmCommand(v []string) *ModelUpdateOne {
	_u.mutation.SetVllmCommand(v)
	return _u
}

// AppendVllmCommand appends value to the "vllm_command" field.
func (_u *ModelUpdateOne) AppendVllmCommand(v []string) *ModelUpdateOne {
	_u.mutation.AppendVllmCommand(v)
	return _u
}

// ClearVllmCommand clears the value of the "vllm_command" field.
func (_u *ModelUpdateOne) ClearVllmCommand() *ModelUpdateOne {
	_u.mutation.ClearVllmCommand()
	return _u
}

// SetCommandMapping sets the "command_mapping" field.
func (_u *ModelUpdateOne) SetCommandMapping(v map[string]string) *ModelUpdateOne {
	_u.mutation.SetCommandMapping(v)
	return _u
}

// ClearCommandMapping clears the value of the "command_mapping" field.
func (_u *ModelUpdateOne) ClearCommandMapping() *ModelUpdateOne {
	_u.mutation.ClearCommandMapping()
	return _u
}

// SetEnv sets the "env" field.
func (_u *ModelUpdateOne) SetEnv(v map[string]string) *ModelUpdateOne {
	_u.mutation.SetEnv(v)
	return _u
}

// ClearEnv clears the value of the "env" field.
func (_u *ModelUpdateOne) ClearEnv() *ModelUpdateOne {
	_u.mutation.ClearEnv()
	return _u
}

// SetPorts sets the "ports" field.
func (_u *ModelUpdateOne) SetPorts(v []int) *ModelUpdateOne {
	_u.mutation.SetPorts(v)
	return _u
}

// AppendPorts appends value to the "ports" field.
func (_u *ModelUpdateOne) AppendPorts(v []int) *ModelUpdateOne {
	_u.mutation.AppendPorts(v)
	return _u
}

// ClearPorts clears the value of the "ports" field.
func (_u *ModelUpdateOne) ClearPorts() *ModelUpdateOne {
	_u.mutation.ClearPorts()
	return _u
}

// SetWritablePaths sets the "writable_paths" field.
func (_u *ModelUpdateOne) SetWritablePaths(v []string) *ModelUpdateOne {
	_u.mutation.SetWritablePaths(v)
	return _u
}

// AppendWritablePaths appends value to the "writable_paths" field.
func (_u *ModelUpdateOne) AppendWritablePaths(v []string) *ModelUpdateOne {
	_u.mutation.AppendWritablePaths(v)
	return _u
}

// ClearWritablePaths clears the value of the "writable_paths" field.
func (_u *ModelUpdateOne) ClearWritablePaths() *ModelUpdateOne {
	_u.mutation.ClearWritablePaths()
	return _u
}

// SetBaseFramework sets the "base_framework" field.
func (_u *ModelUpdateOne) SetBaseFramework(v string) *ModelUpdateOne {
	_u.mutation.SetBaseFramework(v)
	return _u
}

// SetNillableBaseFramework sets the "base_framework" field if the given value is not nil.
func (_u *ModelUpdateOne) SetNillableBaseFramework(v *string) *ModelUpdateOne {
	if v != nil {
		_u.SetBaseFramework(*v)
	}
	return _u
}

// ClearBaseFramework clears the value of the "base_framework" field.
func (_u *ModelUpdateOne) ClearBaseFramework() *ModelUpdateOne {
	_u.mutation.ClearBaseFramework()
	return _u
}

// SetType sets the "type" field.
func (_u *ModelUpdateOne) SetType(v model.Type) *ModelUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *ModelUpdateOne) SetNillableType(v *model.Type) *ModelUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// ClearType clears the value of the "type" field.
func (_u *ModelUpdateOne) ClearType() *ModelUpdateOne {
	_u.mutation.ClearType()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ModelUpdateOne) SetStatus(v model.Status) *ModelUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ModelUpdateOne) SetNillableStatus(v *model.Status) *ModelUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *ModelUpdateOne) ClearStatus() *ModelUpdateOne {
	_u.mutation.ClearStatus()
	return _u
}

// SetReadmeText sets the "readme_text" field.
func (_u *ModelUpdateOne) SetReadmeText(v string) *ModelUpdateOne {
	_u.mutation.SetReadmeText(v)
	return _u
}

// SetNillableReadmeText sets the "readme_text" field if the given value is not nil.
func (_u *ModelUpdateOne) SetNillableReadmeText(v *string) *ModelUpdateOne {
	if v != nil {
		_u.SetReadmeText(*v)
	}
	return _u
}

// ClearReadmeText clears the value of the "readme_text" field.
func (_u *ModelUpdateOne) ClearReadmeText() *ModelUpdateOne {
	_u.mutation.ClearReadmeText()
	return _u
}

// SetDownloads sets the "downloads" field.
func (_u *ModelUpdateOne) SetDownloads(v int64) *ModelUpdateOne {
	_u.mutation.ResetDownloads()
	_u.mutation.SetDownloads(v)
	return _u
}

// SetNillableDownloads sets the "downloads" field if the given value is not nil.
func (_u *ModelUpdateOne) SetNillableDownloads(v *int64) *ModelUpdateOne {
	if v != nil {
		_u.SetDownloads(*v)
	}
	return _u
}

// AddDownloads adds value to the "downloads" field.
func (_u *ModelUpdateOne) AddDownloads(v int64) *ModelUpdateOne {
	_u.mutation.AddDownloads(v)
	return _u
}

// ClearDownloads clears the value of the "downloads" field.
func (_u *ModelUpdateOne) ClearDownloads() *ModelUpdateOne {
	_u.mutation.ClearDownloads()
	return _u
}

// SetLikes sets the "likes" field.
func (_u *ModelUpdateOne) SetLikes(v int64) *ModelUpdateOne {
	_u.mutation.ResetLikes()
	_u.mutation.SetLikes(v)
	return _u
}

// SetNillableLikes sets the "likes" field if the given value is not nil.
func (_u *ModelUpdateOne) SetNillableLikes(v *int64) *ModelUpdateOne {
	if v != nil {
		_u.SetLikes(*v)
	}
	return _u
}

// AddLikes adds value to the "likes" field.
func (_u *ModelUpdateOne) AddLikes(v int64) *ModelUpdateOne {
	_u.mutation.AddLikes(v)
	return _u
}

// ClearLikes clears the value of the "likes" field.
func (_u *ModelUpdateOne) ClearLikes() *ModelUpdateOne {
	_u.mutation.ClearLikes()
	return _u
}

// SetLicense sets the "license" field.
func (_u *ModelUpdateOne) SetLicense(v string) *ModelUpdateOne {
	_u.mutation.SetLicense(v)
	return _u
}

// SetNillableLicense sets the "license" field if the given value is not nil.
func (_u *ModelUpdateOne) SetNillableLicense(v *string) *ModelUpdateOne {
	if v != nil {
		_u.SetLicense(*v)
	}
	return _u
}

// ClearLicense clears the value of the "license" field.
func (_u *ModelUpdateOne) ClearLicense() *ModelUpdateOne {
	_u.mutation.ClearLicense()
	return _u
}

// SetModelSize sets the "model_size" field.
func (_u *ModelUpdateOne) SetModelSize(v int64) *ModelUpdateOne {
	_u.mutation.ResetModelSize()
	_u.mutation.SetModelSize(v)
	return _u
}

// SetNillableModelSize sets the "model_size" field if the given value is not nil.
func (_u *ModelUpdateOne) SetNillableModelSize(v *int64) *ModelUpdateOne {
	if v != nil {
		_u.SetModelSize(*v)
	}
	return _u
}

// AddModelSize adds value to the "model_size" field.
func (_u *ModelUpdateOne) AddModelSize(v int64) *ModelUpdateOne {
	_u.mutation.AddModelSize(v)
	return _u
}

// ClearModelSize clears the value of the "model_size" field.
func (_u *ModelUpdateOne) ClearModelSize() *ModelUpdateOne {
	_u.mutation.ClearModelSize()
	return _u
}

// Mutation returns the ModelMutation object of the builder.
func (_u *ModelUpdateOne) Mutation() *ModelMutation {
	return _u.mutation
}

// Where appends a list predicates to the ModelUpdate builder.
func (_u *ModelUpdateOne) Where(ps ...predicate.Model) *ModelUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ModelUpdateOne) Select(field string, fields ...string) *ModelUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Model entity.
func (_u *ModelUpdateOne) Save(ctx context.Context) (*Model, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelUpdateOne) SaveX(ctx context.Context) *Model {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ModelUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelUpdateOne) check() error {
	if v, ok := _u.mutation.Slug(); ok {
		if err := model.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Model.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DockerImageRef(); ok {
		if err := model.DockerImageRefValidator(v); err != nil {
			return &ValidationError{Name: "docker_image_ref", err: fmt.Errorf(`ent: validator failed for field "Model.docker_image_ref": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := model.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Model.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := model.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Model.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Downloads(); ok {
		if err := model.DownloadsValidator(v); err != nil {
			return &ValidationError{Name: "downloads", err: fmt.Errorf(`ent: validator failed for field "Model.downloads": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Likes(); ok {
		if err := model.LikesValidator(v); err != nil {
			return &ValidationError{Name: "likes", err: fmt.Errorf(`ent: validator failed for field "Model.likes": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ModelSize(); ok {
		if err := model.ModelSizeValidator(v); err != nil {
			return &ValidationError{Name: "model_size", err: fmt.Errorf(`ent: validator failed for field "Model.model_size": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ModelUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ModelUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ModelUpdateOne) sqlSave(ctx context.Context) (_node *Model, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(model.Table, model.Columns, sqlgraph.NewFieldSpec(model.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Model.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, model.FieldID)
		for _, f := range fields {
			if !model.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != model.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(model.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(model.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(model.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(model.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(model.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(model.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(model.FieldRemark, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(model.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(model.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(model.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, model.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(model.FieldTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.IsEnabled(); ok {
		_spec.SetField(model.FieldIsEnabled, field.TypeBool, value)
	}
	if _u.mutation.IsEnabledCleared() {
		_spec.ClearField(model.FieldIsEnabled, field.TypeBool)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(model.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(model.FieldSlug, field.TypeString, value)
	}
	if _u.mutation.SlugCleared() {
		_spec.ClearField(model.FieldSlug, field.TypeString)
	}
	if value, ok := _u.mutation.DockerImageRef(); ok {
		_spec.SetField(model.FieldDockerImageRef, field.TypeString, value)
	}
	if _u.mutation.DockerImageRefCleared() {
		_spec.ClearField(model.FieldDockerImageRef, field.TypeString)
	}
	if value, ok := _u.mutation.JupyterCommand(); ok {
		_spec.SetField(model.FieldJupyterCommand, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedJupyterCommand(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, model.FieldJupyterCommand, value)
		})
	}
	if _u.mutation.JupyterCommandCleared() {
		_spec.ClearField(model.FieldJupyterCommand, field.TypeJSON)
	}
	if value, ok := _u.mutation.VllmCommand(); ok {
		_spec.SetField(model.FieldVllmCommand, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedVllmCommand(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, model.FieldVllmCommand, value)
		})
	}
	if _u.mutation.VllmCommandCleared() {
		_spec.ClearField(model.FieldVllmCommand, field.TypeJSON)
	}
	if value, ok := _u.mutation.CommandMapping(); ok {
		_spec.SetField(model.FieldCommandMapping, field.TypeJSON, value)
	}
	if _u.mutation.CommandMappingCleared() {
		_spec.ClearField(model.FieldCommandMapping, field.TypeJSON)
	}
	if value, ok := _u.mutation.Env(); ok {
		_spec.SetField(model.FieldEnv, field.TypeJSON, value)
	}
	if _u.mutation.EnvCleared() {
		_spec.ClearField(model.FieldEnv, field.TypeJSON)
	}
	if value, ok := _u.mutation.Ports(); ok {
		_spec.SetField(model.FieldPorts, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPorts(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, model.FieldPorts, value)
		})
	}
	if _u.mutation.PortsCleared() {
		_spec.ClearField(model.FieldPorts, field.TypeJSON)
	}
	if value, ok := _u.mutation.WritablePaths(); ok {
		_spec.SetField(model.FieldWritablePaths, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedWritablePaths(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, model.FieldWritablePaths, value)
		})
	}
	if _u.mutation.WritablePathsCleared() {
		_spec.ClearField(model.FieldWritablePaths, field.TypeJSON)
	}
	if value, ok := _u.mutation.BaseFramework(); ok {
		_spec.SetField(model.FieldBaseFramework, field.TypeString, value)
	}
	if _u.mutation.BaseFrameworkCleared() {
		_spec.ClearField(model.FieldBaseFramework, field.TypeString)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(model.FieldType, field.TypeEnum, value)
	}
	if _u.mutation.TypeCleared() {
		_spec.ClearField(model.FieldType, field.TypeEnum)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(model.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(model.FieldStatus, field.TypeEnum)
	}
	if value, ok := _u.mutation.ReadmeText(); ok {
		_spec.SetField(model.FieldReadmeText, field.TypeString, value)
	}
	if _u.mutation.ReadmeTextCleared() {
		_spec.ClearField(model.FieldReadmeText, field.TypeString)
	}
	if value, ok := _u.mutation.Downloads(); ok {
		_spec.SetField(model.FieldDownloads, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDownloads(); ok {
		_spec.AddField(model.FieldDownloads, field.TypeInt64, value)
	}
	if _u.mutation.DownloadsCleared() {
		_spec.ClearField(model.FieldDownloads, field.TypeInt64)
	}
	if value, ok := _u.mutation.Likes(); ok {
		_spec.SetField(model.FieldLikes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLikes(); ok {
		_spec.AddField(model.FieldLikes, field.TypeInt64, value)
	}
	if _u.mutation.LikesCleared() {
		_spec.ClearField(model.FieldLikes, field.TypeInt64)
	}
	if value, ok := _u.mutation.License(); ok {
		_spec.SetField(model.FieldLicense, field.TypeString, value)
	}
	if _u.mutation.LicenseCleared() {
		_spec.ClearField(model.FieldLicense, field.TypeString)
	}
	if value, ok := _u.mutation.ModelSize(); ok {
		_spec.SetField(model.FieldModelSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedModelSize(); ok {
		_spec.AddField(model.FieldModelSize, field.TypeInt64, value)
	}
	if _u.mutation.ModelSizeCleared() {
		_spec.ClearField(model.FieldModelSize, field.TypeInt64)
	}
	if _u.mutation.UUIDCleared() {
		_spec.ClearField(model.FieldUUID, field.TypeUUID)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Model{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{model.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
