// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"go-wind-admin/app/server/service/internal/data/ent/model"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// 模型表
type Model struct {
	config `json:"-"`
	// ID of the ent.
	// id
	ID uint64 `json:"id,omitempty"`
	// 创建时间
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// 删除时间
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// 备注
	Remark *string `json:"remark,omitempty"`
	// 描述
	Description *string `json:"description,omitempty"`
	// tags associated with the object
	Tags []string `json:"tags,omitempty"`
	// 是否启用
	IsEnabled *bool `json:"is_enabled,omitempty"`
	// 模型名称
	Name *string `json:"name,omitempty"`
	// 仓库组名称
	Slug *string `json:"slug,omitempty"`
	// 模型的镜像地址, 如 nvcr.io/nvidia/llama2:latest
	DockerImageRef *string `json:"docker_image_ref,omitempty"`
	// 命令行参数
	JupyterCommand []string `json:"jupyter_command,omitempty"`
	// 命令行参数
	VllmCommand []string `json:"vllm_command,omitempty"`
	// 命令映射
	CommandMapping map[string]string `json:"command_mapping,omitempty"`
	// 环境变量
	Env map[string]string `json:"env,omitempty"`
	// 暴露的端口号
	Ports []int `json:"ports,omitempty"`
	// 可写路径
	WritablePaths []string `json:"writable_paths,omitempty"`
	// 基础框架，如 pytorch, tensorflow, vllm
	BaseFramework *string `json:"base_framework,omitempty"`
	// 模型类型
	Type *model.Type `json:"type,omitempty"`
	// 模型状态
	Status *model.Status `json:"status,omitempty"`
	// Model Card 内容，支持 Markdown
	ReadmeText *string `json:"readme_text,omitempty"`
	// 下载次数
	Downloads int64 `json:"downloads,omitempty"`
	// 点赞数
	Likes int64 `json:"likes,omitempty"`
	// 许可证，如 MIT, Apache-2.0, Llama-Community
	License *string `json:"license,omitempty"`
	// 模型文件大小（字节）
	ModelSize *int64 `json:"model_size,omitempty"`
	// UUID
	UUID         *uuid.UUID `json:"uuid,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Model) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case model.FieldUUID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case model.FieldTags, model.FieldJupyterCommand, model.FieldVllmCommand, model.FieldCommandMapping, model.FieldEnv, model.FieldPorts, model.FieldWritablePaths:
			values[i] = new([]byte)
		case model.FieldIsEnabled:
			values[i] = new(sql.NullBool)
		case model.FieldID, model.FieldDownloads, model.FieldLikes, model.FieldModelSize:
			values[i] = new(sql.NullInt64)
		case model.FieldRemark, model.FieldDescription, model.FieldName, model.FieldSlug, model.FieldDockerImageRef, model.FieldBaseFramework, model.FieldType, model.FieldStatus, model.FieldReadmeText, model.FieldLicense:
			values[i] = new(sql.NullString)
		case model.FieldCreatedAt, model.FieldUpdatedAt, model.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Model fields.
func (_m *Model) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case model.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint64(value.Int64)
		case model.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = new(time.Time)
				*_m.CreatedAt = value.Time
			}
		case model.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = new(time.Time)
				*_m.UpdatedAt = value.Time
			}
		case model.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case model.FieldRemark:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field remark", values[i])
			} else if value.Valid {
				_m.Remark = new(string)
				*_m.Remark = value.String
			}
		case model.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = new(string)
				*_m.Description = value.String
			}
		case model.FieldTags:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field tags", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Tags); err != nil {
					return fmt.Errorf("unmarshal field tags: %w", err)
				}
			}
		case model.FieldIsEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_enabled", values[i])
			} else if value.Valid {
				_m.IsEnabled = new(bool)
				*_m.IsEnabled = value.Bool
			}
		case model.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = new(string)
				*_m.Name = value.String
			}
		case model.FieldSlug:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field slug", values[i])
			} else if value.Valid {
				_m.Slug = new(string)
				*_m.Slug = value.String
			}
		case model.FieldDockerImageRef:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field docker_image_ref", values[i])
			} else if value.Valid {
				_m.DockerImageRef = new(string)
				*_m.DockerImageRef = value.String
			}
		case model.FieldJupyterCommand:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field jupyter_command", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.JupyterCommand); err != nil {
					return fmt.Errorf("unmarshal field jupyter_command: %w", err)
				}
			}
		case model.FieldVllmCommand:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field vllm_command", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.VllmCommand); err != nil {
					return fmt.Errorf("unmarshal field vllm_command: %w", err)
				}
			}
		case model.FieldCommandMapping:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field command_mapping", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.CommandMapping); err != nil {
					return fmt.Errorf("unmarshal field command_mapping: %w", err)
				}
			}
		case model.FieldEnv:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field env", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Env); err != nil {
					return fmt.Errorf("unmarshal field env: %w", err)
				}
			}
		case model.FieldPorts:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field ports", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Ports); err != nil {
					return fmt.Errorf("unmarshal field ports: %w", err)
				}
			}
		case model.FieldWritablePaths:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field writable_paths", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.WritablePaths); err != nil {
					return fmt.Errorf("unmarshal field writable_paths: %w", err)
				}
			}
		case model.FieldBaseFramework:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field base_framework", values[i])
			} else if value.Valid {
				_m.BaseFramework = new(string)
				*_m.BaseFramework = value.String
			}
		case model.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = new(model.Type)
				*_m.Type = model.Type(value.String)
			}
		case model.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = new(model.Status)
				*_m.Status = model.Status(value.String)
			}
		case model.FieldReadmeText:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field readme_text", values[i])
			} else if value.Valid {
				_m.ReadmeText = new(string)
				*_m.ReadmeText = value.String
			}
		case model.FieldDownloads:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field downloads", values[i])
			} else if value.Valid {
				_m.Downloads = value.Int64
			}
		case model.FieldLikes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field likes", values[i])
			} else if value.Valid {
				_m.Likes = value.Int64
			}
		case model.FieldLicense:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field license", values[i])
			} else if value.Valid {
				_m.License = new(string)
				*_m.License = value.String
			}
		case model.FieldModelSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field model_size", values[i])
			} else if value.Valid {
				_m.ModelSize = new(int64)
				*_m.ModelSize = value.Int64
			}
		case model.FieldUUID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field uuid", values[i])
			} else if value.Valid {
				_m.UUID = new(uuid.UUID)
				*_m.UUID = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Model.
// This includes values selected through modifiers, order, etc.
func (_m *Model) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Model.
// Note that you need to call Model.Unwrap() before calling this method if this Model
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Model) Update() *ModelUpdateOne {
	return NewModelClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Model entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Model) Unwrap() *Model {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Model is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Model) String() string {
	var builder strings.Builder
	builder.WriteString("Model(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.CreatedAt; v != nil {
		builder.WriteString("created_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedAt; v != nil {
		builder.WriteString("updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.Remark; v != nil {
		builder.WriteString("remark=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("tags=")
	builder.WriteString(fmt.Sprintf("%v", _m.Tags))
	builder.WriteString(", ")
	if v := _m.IsEnabled; v != nil {
		builder.WriteString("is_enabled=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Name; v != nil {
		builder.WriteString("name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Slug; v != nil {
		builder.WriteString("slug=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.DockerImageRef; v != nil {
		builder.WriteString("docker_image_ref=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("jupyter_command=")
	builder.WriteString(fmt.Sprintf("%v", _m.JupyterCommand))
	builder.WriteString(", ")
	builder.WriteString("vllm_command=")
	builder.WriteString(fmt.Sprintf("%v", _m.VllmCommand))
	builder.WriteString(", ")
	builder.WriteString("command_mapping=")
	builder.WriteString(fmt.Sprintf("%v", _m.CommandMapping))
	builder.WriteString(", ")
	builder.WriteString("env=")
	builder.WriteString(fmt.Sprintf("%v", _m.Env))
	builder.WriteString(", ")
	builder.WriteString("ports=")
	builder.WriteString(fmt.Sprintf("%v", _m.Ports))
	builder.WriteString(", ")
	builder.WriteString("writable_paths=")
	builder.WriteString(fmt.Sprintf("%v", _m.WritablePaths))
	builder.WriteString(", ")
	if v := _m.BaseFramework; v != nil {
		builder.WriteString("base_framework=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Type; v != nil {
		builder.WriteString("type=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Status; v != nil {
		builder.WriteString("status=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ReadmeText; v != nil {
		builder.WriteString("readme_text=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("downloads=")
	builder.WriteString(fmt.Sprintf("%v", _m.Downloads))
	builder.WriteString(", ")
	builder.WriteString("likes=")
	builder.WriteString(fmt.Sprintf("%v", _m.Likes))
	builder.WriteString(", ")
	if v := _m.License; v != nil {
		builder.WriteString("license=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ModelSize; v != nil {
		builder.WriteString("model_size=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UUID; v != nil {
		builder.WriteString("uuid=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Models is a parsable slice of Model.
type Models []*Model
