// Code generated by ent, DO NOT EDIT.

package ent

import (
	"go-wind-admin/app/server/service/internal/data/ent/inference"
	"go-wind-admin/app/server/service/internal/data/ent/model"
	"go-wind-admin/app/server/service/internal/data/ent/sandbox"
	"go-wind-admin/app/server/service/internal/data/ent/schema"
	"go-wind-admin/app/server/service/internal/data/ent/tenant"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	inferenceMixin := schema.Inference{}.Mixin()
	inferenceMixinFields0 := inferenceMixin[0].Fields()
	_ = inferenceMixinFields0
	inferenceMixinFields4 := inferenceMixin[4].Fields()
	_ = inferenceMixinFields4
	inferenceMixinFields5 := inferenceMixin[5].Fields()
	_ = inferenceMixinFields5
	inferenceFields := schema.Inference{}.Fields()
	_ = inferenceFields
	// inferenceDescTags is the schema descriptor for tags field.
	inferenceDescTags := inferenceMixinFields4[0].Descriptor()
	// inference.DefaultTags holds the default value on creation for the tags field.
	inference.DefaultTags = inferenceDescTags.Default.([]string)
	// inferenceDescIsEnabled is the schema descriptor for is_enabled field.
	inferenceDescIsEnabled := inferenceMixinFields5[0].Descriptor()
	// inference.DefaultIsEnabled holds the default value on creation for the is_enabled field.
	inference.DefaultIsEnabled = inferenceDescIsEnabled.Default.(bool)
	// inferenceDescName is the schema descriptor for name field.
	inferenceDescName := inferenceFields[0].Descriptor()
	// inference.NameValidator is a validator for the "name" field. It is called by the builders before save.
	inference.NameValidator = inferenceDescName.Validators[0].(func(string) error)
	// inferenceDescTenantName is the schema descriptor for tenant_name field.
	inferenceDescTenantName := inferenceFields[1].Descriptor()
	// inference.TenantNameValidator is a validator for the "tenant_name" field. It is called by the builders before save.
	inference.TenantNameValidator = inferenceDescTenantName.Validators[0].(func(string) error)
	// inferenceDescReplicas is the schema descriptor for replicas field.
	inferenceDescReplicas := inferenceFields[6].Descriptor()
	// inference.DefaultReplicas holds the default value on creation for the replicas field.
	inference.DefaultReplicas = inferenceDescReplicas.Default.(int32)
	// inference.ReplicasValidator is a validator for the "replicas" field. It is called by the builders before save.
	inference.ReplicasValidator = inferenceDescReplicas.Validators[0].(func(int32) error)
	// inferenceDescMinReplicas is the schema descriptor for min_replicas field.
	inferenceDescMinReplicas := inferenceFields[7].Descriptor()
	// inference.DefaultMinReplicas holds the default value on creation for the min_replicas field.
	inference.DefaultMinReplicas = inferenceDescMinReplicas.Default.(int32)
	// inferenceDescMaxReplicas is the schema descriptor for max_replicas field.
	inferenceDescMaxReplicas := inferenceFields[8].Descriptor()
	// inference.DefaultMaxReplicas holds the default value on creation for the max_replicas field.
	inference.DefaultMaxReplicas = inferenceDescMaxReplicas.Default.(int32)
	// inferenceDescPort is the schema descriptor for port field.
	inferenceDescPort := inferenceFields[9].Descriptor()
	// inference.DefaultPort holds the default value on creation for the port field.
	inference.DefaultPort = inferenceDescPort.Default.(int32)
	// inferenceDescDeploymentName is the schema descriptor for deployment_name field.
	inferenceDescDeploymentName := inferenceFields[13].Descriptor()
	// inference.DeploymentNameValidator is a validator for the "deployment_name" field. It is called by the builders before save.
	inference.DeploymentNameValidator = inferenceDescDeploymentName.Validators[0].(func(string) error)
	// inferenceDescServiceName is the schema descriptor for service_name field.
	inferenceDescServiceName := inferenceFields[14].Descriptor()
	// inference.ServiceNameValidator is a validator for the "service_name" field. It is called by the builders before save.
	inference.ServiceNameValidator = inferenceDescServiceName.Validators[0].(func(string) error)
	// inferenceDescBillingDurationSec is the schema descriptor for billing_duration_sec field.
	inferenceDescBillingDurationSec := inferenceFields[21].Descriptor()
	// inference.DefaultBillingDurationSec holds the default value on creation for the billing_duration_sec field.
	inference.DefaultBillingDurationSec = inferenceDescBillingDurationSec.Default.(int64)
	// inferenceDescUsageCPUSeconds is the schema descriptor for usage_cpu_seconds field.
	inferenceDescUsageCPUSeconds := inferenceFields[22].Descriptor()
	// inference.DefaultUsageCPUSeconds holds the default value on creation for the usage_cpu_seconds field.
	inference.DefaultUsageCPUSeconds = inferenceDescUsageCPUSeconds.Default.(int64)
	// inferenceDescUsageGpuSeconds is the schema descriptor for usage_gpu_seconds field.
	inferenceDescUsageGpuSeconds := inferenceFields[23].Descriptor()
	// inference.DefaultUsageGpuSeconds holds the default value on creation for the usage_gpu_seconds field.
	inference.DefaultUsageGpuSeconds = inferenceDescUsageGpuSeconds.Default.(int64)
	// inferenceDescUsageReplicaSeconds is the schema descriptor for usage_replica_seconds field.
	inferenceDescUsageReplicaSeconds := inferenceFields[24].Descriptor()
	// inference.DefaultUsageReplicaSeconds holds the default value on creation for the usage_replica_seconds field.
	inference.DefaultUsageReplicaSeconds = inferenceDescUsageReplicaSeconds.Default.(int64)
	// inferenceDescExpirationMinutes is the schema descriptor for expiration_minutes field.
	inferenceDescExpirationMinutes := inferenceFields[25].Descriptor()
	// inference.DefaultExpirationMinutes holds the default value on creation for the expiration_minutes field.
	inference.DefaultExpirationMinutes = inferenceDescExpirationMinutes.Default.(int64)
	// inferenceDescID is the schema descriptor for id field.
	inferenceDescID := inferenceMixinFields0[0].Descriptor()
	// inference.IDValidator is a validator for the "id" field. It is called by the builders before save.
	inference.IDValidator = inferenceDescID.Validators[0].(func(uint64) error)
	modelMixin := schema.Model{}.Mixin()
	modelMixinFields0 := modelMixin[0].Fields()
	_ = modelMixinFields0
	modelMixinFields4 := modelMixin[4].Fields()
	_ = modelMixinFields4
	modelMixinFields5 := modelMixin[5].Fields()
	_ = modelMixinFields5
	modelFields := schema.Model{}.Fields()
	_ = modelFields
	// modelDescTags is the schema descriptor for tags field.
	modelDescTags := modelMixinFields4[0].Descriptor()
	// model.DefaultTags holds the default value on creation for the tags field.
	model.DefaultTags = modelDescTags.Default.([]string)
	// modelDescIsEnabled is the schema descriptor for is_enabled field.
	modelDescIsEnabled := modelMixinFields5[0].Descriptor()
	// model.DefaultIsEnabled holds the default value on creation for the is_enabled field.
	model.DefaultIsEnabled = modelDescIsEnabled.Default.(bool)
	// modelDescName is the schema descriptor for name field.
	modelDescName := modelFields[0].Descriptor()
	// model.NameValidator is a validator for the "name" field. It is called by the builders before save.
	model.NameValidator = func() func(string) error {
		validators := modelDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// modelDescSlug is the schema descriptor for slug field.
	modelDescSlug := modelFields[1].Descriptor()
	// model.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	model.SlugValidator = modelDescSlug.Validators[0].(func(string) error)
	// modelDescDockerImageRef is the schema descriptor for docker_image_ref field.
	modelDescDockerImageRef := modelFields[2].Descriptor()
	// model.DockerImageRefValidator is a validator for the "docker_image_ref" field. It is called by the builders before save.
	model.DockerImageRefValidator = modelDescDockerImageRef.Validators[0].(func(string) error)
	// modelDescJupyterCommand is the schema descriptor for jupyter_command field.
	modelDescJupyterCommand := modelFields[3].Descriptor()
	// model.DefaultJupyterCommand holds the default value on creation for the jupyter_command field.
	model.DefaultJupyterCommand = modelDescJupyterCommand.Default.([]string)
	// modelDescVllmCommand is the schema descriptor for vllm_command field.
	modelDescVllmCommand := modelFields[4].Descriptor()
	// model.DefaultVllmCommand holds the default value on creation for the vllm_command field.
	model.DefaultVllmCommand = modelDescVllmCommand.Default.([]string)
	// modelDescCommandMapping is the schema descriptor for command_mapping field.
	modelDescCommandMapping := modelFields[5].Descriptor()
	// model.DefaultCommandMapping holds the default value on creation for the command_mapping field.
	model.DefaultCommandMapping = modelDescCommandMapping.Default.(map[string]string)
	// modelDescEnv is the schema descriptor for env field.
	modelDescEnv := modelFields[6].Descriptor()
	// model.DefaultEnv holds the default value on creation for the env field.
	model.DefaultEnv = modelDescEnv.Default.(map[string]string)
	// modelDescPorts is the schema descriptor for ports field.
	modelDescPorts := modelFields[7].Descriptor()
	// model.DefaultPorts holds the default value on creation for the ports field.
	model.DefaultPorts = modelDescPorts.Default.([]int)
	// modelDescWritablePaths is the schema descriptor for writable_paths field.
	modelDescWritablePaths := modelFields[8].Descriptor()
	// model.DefaultWritablePaths holds the default value on creation for the writable_paths field.
	model.DefaultWritablePaths = modelDescWritablePaths.Default.([]string)
	// modelDescDownloads is the schema descriptor for downloads field.
	modelDescDownloads := modelFields[13].Descriptor()
	// model.DefaultDownloads holds the default value on creation for the downloads field.
	model.DefaultDownloads = modelDescDownloads.Default.(int64)
	// model.DownloadsValidator is a validator for the "downloads" field. It is called by the builders before save.
	model.DownloadsValidator = modelDescDownloads.Validators[0].(func(int64) error)
	// modelDescLikes is the schema descriptor for likes field.
	modelDescLikes := modelFields[14].Descriptor()
	// model.DefaultLikes holds the default value on creation for the likes field.
	model.DefaultLikes = modelDescLikes.Default.(int64)
	// model.LikesValidator is a validator for the "likes" field. It is called by the builders before save.
	model.LikesValidator = modelDescLikes.Validators[0].(func(int64) error)
	// modelDescLicense is the schema descriptor for license field.
	modelDescLicense := modelFields[15].Descriptor()
	// model.DefaultLicense holds the default value on creation for the license field.
	model.DefaultLicense = modelDescLicense.Default.(string)
	// modelDescModelSize is the schema descriptor for model_size field.
	modelDescModelSize := modelFields[16].Descriptor()
	// model.ModelSizeValidator is a validator for the "model_size" field. It is called by the builders before save.
	model.ModelSizeValidator = modelDescModelSize.Validators[0].(func(int64) error)
	// modelDescUUID is the schema descriptor for uuid field.
	modelDescUUID := modelFields[17].Descriptor()
	// model.DefaultUUID holds the default value on creation for the uuid field.
	model.DefaultUUID = modelDescUUID.Default.(func() uuid.UUID)
	// modelDescID is the schema descriptor for id field.
	modelDescID := modelMixinFields0[0].Descriptor()
	// model.IDValidator is a validator for the "id" field. It is called by the builders before save.
	model.IDValidator = modelDescID.Validators[0].(func(uint64) error)
	sandboxMixin := schema.Sandbox{}.Mixin()
	sandboxMixinFields0 := sandboxMixin[0].Fields()
	_ = sandboxMixinFields0
	sandboxMixinFields4 := sandboxMixin[4].Fields()
	_ = sandboxMixinFields4
	sandboxMixinFields5 := sandboxMixin[5].Fields()
	_ = sandboxMixinFields5
	sandboxFields := schema.Sandbox{}.Fields()
	_ = sandboxFields
	// sandboxDescTags is the schema descriptor for tags field.
	sandboxDescTags := sandboxMixinFields4[0].Descriptor()
	// sandbox.DefaultTags holds the default value on creation for the tags field.
	sandbox.DefaultTags = sandboxDescTags.Default.([]string)
	// sandboxDescIsEnabled is the schema descriptor for is_enabled field.
	sandboxDescIsEnabled := sandboxMixinFields5[0].Descriptor()
	// sandbox.DefaultIsEnabled holds the default value on creation for the is_enabled field.
	sandbox.DefaultIsEnabled = sandboxDescIsEnabled.Default.(bool)
	// sandboxDescName is the schema descriptor for name field.
	sandboxDescName := sandboxFields[0].Descriptor()
	// sandbox.NameValidator is a validator for the "name" field. It is called by the builders before save.
	sandbox.NameValidator = sandboxDescName.Validators[0].(func(string) error)
	// sandboxDescTenantName is the schema descriptor for tenant_name field.
	sandboxDescTenantName := sandboxFields[2].Descriptor()
	// sandbox.TenantNameValidator is a validator for the "tenant_name" field. It is called by the builders before save.
	sandbox.TenantNameValidator = sandboxDescTenantName.Validators[0].(func(string) error)
	// sandboxDescCommandMapping is the schema descriptor for command_mapping field.
	sandboxDescCommandMapping := sandboxFields[3].Descriptor()
	// sandbox.DefaultCommandMapping holds the default value on creation for the command_mapping field.
	sandbox.DefaultCommandMapping = sandboxDescCommandMapping.Default.(map[string]string)
	// sandboxDescEnv is the schema descriptor for env field.
	sandboxDescEnv := sandboxFields[4].Descriptor()
	// sandbox.DefaultEnv holds the default value on creation for the env field.
	sandbox.DefaultEnv = sandboxDescEnv.Default.(map[string]string)
	// sandboxDescDeploymentName is the schema descriptor for deployment_name field.
	sandboxDescDeploymentName := sandboxFields[5].Descriptor()
	// sandbox.DeploymentNameValidator is a validator for the "deployment_name" field. It is called by the builders before save.
	sandbox.DeploymentNameValidator = sandboxDescDeploymentName.Validators[0].(func(string) error)
	// sandboxDescURL is the schema descriptor for url field.
	sandboxDescURL := sandboxFields[6].Descriptor()
	// sandbox.URLValidator is a validator for the "url" field. It is called by the builders before save.
	sandbox.URLValidator = sandboxDescURL.Validators[0].(func(string) error)
	// sandboxDescBillingDurationSec is the schema descriptor for billing_duration_sec field.
	sandboxDescBillingDurationSec := sandboxFields[13].Descriptor()
	// sandbox.DefaultBillingDurationSec holds the default value on creation for the billing_duration_sec field.
	sandbox.DefaultBillingDurationSec = sandboxDescBillingDurationSec.Default.(int64)
	// sandboxDescExpirationMinutes is the schema descriptor for expiration_minutes field.
	sandboxDescExpirationMinutes := sandboxFields[14].Descriptor()
	// sandbox.DefaultExpirationMinutes holds the default value on creation for the expiration_minutes field.
	sandbox.DefaultExpirationMinutes = sandboxDescExpirationMinutes.Default.(int64)
	// sandboxDescID is the schema descriptor for id field.
	sandboxDescID := sandboxMixinFields0[0].Descriptor()
	// sandbox.IDValidator is a validator for the "id" field. It is called by the builders before save.
	sandbox.IDValidator = sandboxDescID.Validators[0].(func(uint64) error)
	tenantMixin := schema.Tenant{}.Mixin()
	tenantMixinFields0 := tenantMixin[0].Fields()
	_ = tenantMixinFields0
	tenantMixinFields4 := tenantMixin[4].Fields()
	_ = tenantMixinFields4
	tenantMixinFields5 := tenantMixin[5].Fields()
	_ = tenantMixinFields5
	tenantFields := schema.Tenant{}.Fields()
	_ = tenantFields
	// tenantDescTags is the schema descriptor for tags field.
	tenantDescTags := tenantMixinFields4[0].Descriptor()
	// tenant.DefaultTags holds the default value on creation for the tags field.
	tenant.DefaultTags = tenantDescTags.Default.([]string)
	// tenantDescIsEnabled is the schema descriptor for is_enabled field.
	tenantDescIsEnabled := tenantMixinFields5[0].Descriptor()
	// tenant.DefaultIsEnabled holds the default value on creation for the is_enabled field.
	tenant.DefaultIsEnabled = tenantDescIsEnabled.Default.(bool)
	// tenantDescName is the schema descriptor for name field.
	tenantDescName := tenantFields[0].Descriptor()
	// tenant.NameValidator is a validator for the "name" field. It is called by the builders before save.
	tenant.NameValidator = tenantDescName.Validators[0].(func(string) error)
	// tenantDescID is the schema descriptor for id field.
	tenantDescID := tenantMixinFields0[0].Descriptor()
	// tenant.IDValidator is a validator for the "id" field. It is called by the builders before save.
	tenant.IDValidator = tenantDescID.Validators[0].(func(uint64) error)
}
