// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	servicev1 "go-wind-admin/api/gen/go/tenant/service/v1"
	"go-wind-admin/app/server/service/internal/data/ent/sandbox"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// 沙箱表
type Sandbox struct {
	config `json:"-"`
	// ID of the ent.
	// id
	ID uint64 `json:"id,omitempty"`
	// 创建时间
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// 删除时间
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// 备注
	Remark *string `json:"remark,omitempty"`
	// 描述
	Description *string `json:"description,omitempty"`
	// tags associated with the object
	Tags []string `json:"tags,omitempty"`
	// 是否启用
	IsEnabled *bool `json:"is_enabled,omitempty"`
	// 沙箱名
	Name *string `json:"name,omitempty"`
	// 状态
	Status *sandbox.Status `json:"status,omitempty"`
	// 租户名
	TenantName *string `json:"tenant_name,omitempty"`
	// 命令映射
	CommandMapping map[string]string `json:"command_mapping,omitempty"`
	// 环境变量
	Env map[string]string `json:"env,omitempty"`
	// 部署名
	DeploymentName *string `json:"deployment_name,omitempty"`
	// 域名
	URL *string `json:"url,omitempty"`
	// 访问密码
	Password *string `json:"password,omitempty"`
	// 关联的模型ID
	ModelID *uint64 `json:"model_id,omitempty"`
	// 关联的模型名称
	ModelName *string `json:"model_name,omitempty"`
	// 资源配额
	Quota *servicev1.Quota `json:"quota,omitempty"`
	// 开始运行时间
	StartedAt time.Time `json:"started_at,omitempty"`
	// 结束时间
	FinishedAt time.Time `json:"finished_at,omitempty"`
	// 计费时长(秒)
	BillingDurationSec int64 `json:"billing_duration_sec,omitempty"`
	// 自动过期时长(分钟)
	ExpirationMinutes int64 `json:"expiration_minutes,omitempty"`
	selectValues      sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Sandbox) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sandbox.FieldTags, sandbox.FieldCommandMapping, sandbox.FieldEnv, sandbox.FieldQuota:
			values[i] = new([]byte)
		case sandbox.FieldIsEnabled:
			values[i] = new(sql.NullBool)
		case sandbox.FieldID, sandbox.FieldModelID, sandbox.FieldBillingDurationSec, sandbox.FieldExpirationMinutes:
			values[i] = new(sql.NullInt64)
		case sandbox.FieldRemark, sandbox.FieldDescription, sandbox.FieldName, sandbox.FieldStatus, sandbox.FieldTenantName, sandbox.FieldDeploymentName, sandbox.FieldURL, sandbox.FieldPassword, sandbox.FieldModelName:
			values[i] = new(sql.NullString)
		case sandbox.FieldCreatedAt, sandbox.FieldUpdatedAt, sandbox.FieldDeletedAt, sandbox.FieldStartedAt, sandbox.FieldFinishedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Sandbox fields.
func (_m *Sandbox) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sandbox.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint64(value.Int64)
		case sandbox.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = new(time.Time)
				*_m.CreatedAt = value.Time
			}
		case sandbox.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = new(time.Time)
				*_m.UpdatedAt = value.Time
			}
		case sandbox.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case sandbox.FieldRemark:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field remark", values[i])
			} else if value.Valid {
				_m.Remark = new(string)
				*_m.Remark = value.String
			}
		case sandbox.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = new(string)
				*_m.Description = value.String
			}
		case sandbox.FieldTags:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field tags", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Tags); err != nil {
					return fmt.Errorf("unmarshal field tags: %w", err)
				}
			}
		case sandbox.FieldIsEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_enabled", values[i])
			} else if value.Valid {
				_m.IsEnabled = new(bool)
				*_m.IsEnabled = value.Bool
			}
		case sandbox.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = new(string)
				*_m.Name = value.String
			}
		case sandbox.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = new(sandbox.Status)
				*_m.Status = sandbox.Status(value.String)
			}
		case sandbox.FieldTenantName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_name", values[i])
			} else if value.Valid {
				_m.TenantName = new(string)
				*_m.TenantName = value.String
			}
		case sandbox.FieldCommandMapping:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field command_mapping", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.CommandMapping); err != nil {
					return fmt.Errorf("unmarshal field command_mapping: %w", err)
				}
			}
		case sandbox.FieldEnv:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field env", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Env); err != nil {
					return fmt.Errorf("unmarshal field env: %w", err)
				}
			}
		case sandbox.FieldDeploymentName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field deployment_name", values[i])
			} else if value.Valid {
				_m.DeploymentName = new(string)
				*_m.DeploymentName = value.String
			}
		case sandbox.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				_m.URL = new(string)
				*_m.URL = value.String
			}
		case sandbox.FieldPassword:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password", values[i])
			} else if value.Valid {
				_m.Password = new(string)
				*_m.Password = value.String
			}
		case sandbox.FieldModelID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field model_id", values[i])
			} else if value.Valid {
				_m.ModelID = new(uint64)
				*_m.ModelID = uint64(value.Int64)
			}
		case sandbox.FieldModelName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_name", values[i])
			} else if value.Valid {
				_m.ModelName = new(string)
				*_m.ModelName = value.String
			}
		case sandbox.FieldQuota:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field quota", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Quota); err != nil {
					return fmt.Errorf("unmarshal field quota: %w", err)
				}
			}
		case sandbox.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = value.Time
			}
		case sandbox.FieldFinishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field finished_at", values[i])
			} else if value.Valid {
				_m.FinishedAt = value.Time
			}
		case sandbox.FieldBillingDurationSec:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field billing_duration_sec", values[i])
			} else if value.Valid {
				_m.BillingDurationSec = value.Int64
			}
		case sandbox.FieldExpirationMinutes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field expiration_minutes", values[i])
			} else if value.Valid {
				_m.ExpirationMinutes = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Sandbox.
// This includes values selected through modifiers, order, etc.
func (_m *Sandbox) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Sandbox.
// Note that you need to call Sandbox.Unwrap() before calling this method if this Sandbox
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Sandbox) Update() *SandboxUpdateOne {
	return NewSandboxClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Sandbox entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Sandbox) Unwrap() *Sandbox {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Sandbox is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Sandbox) String() string {
	var builder strings.Builder
	builder.WriteString("Sandbox(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.CreatedAt; v != nil {
		builder.WriteString("created_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedAt; v != nil {
		builder.WriteString("updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.Remark; v != nil {
		builder.WriteString("remark=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("tags=")
	builder.WriteString(fmt.Sprintf("%v", _m.Tags))
	builder.WriteString(", ")
	if v := _m.IsEnabled; v != nil {
		builder.WriteString("is_enabled=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Name; v != nil {
		builder.WriteString("name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Status; v != nil {
		builder.WriteString("status=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.TenantName; v != nil {
		builder.WriteString("tenant_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("command_mapping=")
	builder.WriteString(fmt.Sprintf("%v", _m.CommandMapping))
	builder.WriteString(", ")
	builder.WriteString("env=")
	builder.WriteString(fmt.Sprintf("%v", _m.Env))
	builder.WriteString(", ")
	if v := _m.DeploymentName; v != nil {
		builder.WriteString("deployment_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.URL; v != nil {
		builder.WriteString("url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Password; v != nil {
		builder.WriteString("password=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ModelID; v != nil {
		builder.WriteString("model_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ModelName; v != nil {
		builder.WriteString("model_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("quota=")
	builder.WriteString(fmt.Sprintf("%v", _m.Quota))
	builder.WriteString(", ")
	builder.WriteString("started_at=")
	builder.WriteString(_m.StartedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("finished_at=")
	builder.WriteString(_m.FinishedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("billing_duration_sec=")
	builder.WriteString(fmt.Sprintf("%v", _m.BillingDurationSec))
	builder.WriteString(", ")
	builder.WriteString("expiration_minutes=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExpirationMinutes))
	builder.WriteByte(')')
	return builder.String()
}

// Sandboxes is a parsable slice of Sandbox.
type Sandboxes []*Sandbox
