// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// InferencesColumns holds the columns for the "inferences" table.
	InferencesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true, Comment: "id"},
		{Name: "created_at", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "remark", Type: field.TypeString, Nullable: true, Comment: "备注"},
		{Name: "description", Type: field.TypeString, Nullable: true, Comment: "描述"},
		{Name: "tags", Type: field.TypeJSON, Nullable: true, Comment: "tags associated with the object"},
		{Name: "is_enabled", Type: field.TypeBool, Nullable: true, Comment: "是否启用", Default: true},
		{Name: "name", Type: field.TypeString, Comment: "推理服务名称"},
		{Name: "tenant_name", Type: field.TypeString, Comment: "租户名"},
		{Name: "status", Type: field.TypeEnum, Nullable: true, Comment: "状态", Enums: []string{"UNSPECIFIED", "CREATING", "RUNNING", "STOPPED", "RESTARTING", "SCALING", "ERROR", "DELETING"}, Default: "UNSPECIFIED"},
		{Name: "model_id", Type: field.TypeUint64, Nullable: true, Comment: "关联的模型ID"},
		{Name: "model_name", Type: field.TypeString, Nullable: true, Comment: "模型名称快照"},
		{Name: "image", Type: field.TypeString, Nullable: true, Comment: "镜像地址(允许覆盖模型默认镜像)"},
		{Name: "replicas", Type: field.TypeInt32, Comment: "当前期望副本数", Default: 1},
		{Name: "min_replicas", Type: field.TypeInt32, Nullable: true, Comment: "HPA最小副本数(0表示不启用HPA)", Default: 0},
		{Name: "max_replicas", Type: field.TypeInt32, Nullable: true, Comment: "HPA最大副本数", Default: 0},
		{Name: "port", Type: field.TypeInt32, Comment: "服务监听端口", Default: 8000},
		{Name: "command", Type: field.TypeJSON, Nullable: true, Comment: "启动命令(覆盖默认)"},
		{Name: "args", Type: field.TypeJSON, Nullable: true, Comment: "启动参数"},
		{Name: "env", Type: field.TypeJSON, Nullable: true, Comment: "环境变量"},
		{Name: "deployment_name", Type: field.TypeString, Comment: "K8s Deployment名称"},
		{Name: "service_name", Type: field.TypeString, Comment: "K8s Service名称"},
		{Name: "url", Type: field.TypeString, Nullable: true, Comment: "访问域名"},
		{Name: "auth_token", Type: field.TypeString, Nullable: true, Comment: "API访问令牌(Bearer Token)"},
		{Name: "quota", Type: field.TypeJSON, Nullable: true, Comment: "单副本资源配额"},
		{Name: "started_at", Type: field.TypeTime, Nullable: true, Comment: "最近一次启动时间"},
		{Name: "finished_at", Type: field.TypeTime, Nullable: true, Comment: "最近一次停止时间"},
		{Name: "last_activity_time", Type: field.TypeTime, Nullable: true, Comment: "最近一次活跃时间(心跳/扩缩容)"},
		{Name: "billing_duration_sec", Type: field.TypeInt64, Comment: "服务累计在线时长(秒)", Default: 0},
		{Name: "usage_cpu_seconds", Type: field.TypeInt64, Comment: "累计CPU使用量(核*秒)", Default: 0},
		{Name: "usage_gpu_seconds", Type: field.TypeInt64, Comment: "累计GPU使用量(卡*秒)", Default: 0},
		{Name: "usage_replica_seconds", Type: field.TypeInt64, Comment: "累计副本运行时长(个*秒)", Default: 0},
		{Name: "expiration_minutes", Type: field.TypeInt64, Comment: "自动过期时长(分钟)，0为不过期", Default: 0},
	}
	// InferencesTable holds the schema information for the "inferences" table.
	InferencesTable = &schema.Table{
		Name:       "inferences",
		Comment:    "推理服务表",
		Columns:    InferencesColumns,
		PrimaryKey: []*schema.Column{InferencesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "uk_inference_name",
				Unique:  true,
				Columns: []*schema.Column{InferencesColumns[9], InferencesColumns[8]},
			},
			{
				Name:    "uk_inference_deployment",
				Unique:  true,
				Columns: []*schema.Column{InferencesColumns[9], InferencesColumns[21]},
			},
		},
	}
	// ModelsColumns holds the columns for the "models" table.
	ModelsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true, Comment: "id"},
		{Name: "created_at", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "remark", Type: field.TypeString, Nullable: true, Comment: "备注"},
		{Name: "description", Type: field.TypeString, Nullable: true, Comment: "描述"},
		{Name: "tags", Type: field.TypeJSON, Nullable: true, Comment: "tags associated with the object"},
		{Name: "is_enabled", Type: field.TypeBool, Nullable: true, Comment: "是否启用", Default: true},
		{Name: "name", Type: field.TypeString, Unique: true, Nullable: true, Size: 255, Comment: "模型名称"},
		{Name: "slug", Type: field.TypeString, Unique: true, Nullable: true, Comment: "仓库组名称"},
		{Name: "docker_image_ref", Type: field.TypeString, Nullable: true, Comment: "模型的镜像地址, 如 nvcr.io/nvidia/llama2:latest"},
		{Name: "jupyter_command", Type: field.TypeJSON, Nullable: true, Comment: "命令行参数"},
		{Name: "vllm_command", Type: field.TypeJSON, Nullable: true, Comment: "命令行参数"},
		{Name: "command_mapping", Type: field.TypeJSON, Nullable: true, Comment: "命令映射"},
		{Name: "env", Type: field.TypeJSON, Nullable: true, Comment: "环境变量"},
		{Name: "ports", Type: field.TypeJSON, Nullable: true, Comment: "暴露的端口号"},
		{Name: "writable_paths", Type: field.TypeJSON, Nullable: true, Comment: "可写路径"},
		{Name: "base_framework", Type: field.TypeString, Nullable: true, Comment: "基础框架，如 pytorch, tensorflow, vllm"},
		{Name: "type", Type: field.TypeEnum, Nullable: true, Comment: "模型类型", Enums: []string{"CUSTOM", "NIM", "HF", "ONLY_IMAGE"}, Default: "CUSTOM"},
		{Name: "status", Type: field.TypeEnum, Nullable: true, Comment: "模型状态", Enums: []string{"NOT_CACHED", "CACHING", "READY"}, Default: "NOT_CACHED"},
		{Name: "readme_text", Type: field.TypeString, Nullable: true, Size: 2147483647, Comment: "Model Card 内容，支持 Markdown"},
		{Name: "downloads", Type: field.TypeInt64, Nullable: true, Comment: "下载次数", Default: 0},
		{Name: "likes", Type: field.TypeInt64, Nullable: true, Comment: "点赞数", Default: 0},
		{Name: "license", Type: field.TypeString, Nullable: true, Comment: "许可证，如 MIT, Apache-2.0, Llama-Community", Default: "MIT"},
		{Name: "model_size", Type: field.TypeInt64, Nullable: true, Comment: "模型文件大小（字节）"},
		{Name: "uuid", Type: field.TypeUUID, Unique: true, Nullable: true, Comment: "UUID"},
	}
	// ModelsTable holds the schema information for the "models" table.
	ModelsTable = &schema.Table{
		Name:       "models",
		Comment:    "模型表",
		Columns:    ModelsColumns,
		PrimaryKey: []*schema.Column{ModelsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "idx_models_name",
				Unique:  false,
				Columns: []*schema.Column{ModelsColumns[8]},
			},
		},
	}
	// SandboxesColumns holds the columns for the "sandboxes" table.
	SandboxesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true, Comment: "id"},
		{Name: "created_at", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "remark", Type: field.TypeString, Nullable: true, Comment: "备注"},
		{Name: "description", Type: field.TypeString, Nullable: true, Comment: "描述"},
		{Name: "tags", Type: field.TypeJSON, Nullable: true, Comment: "tags associated with the object"},
		{Name: "is_enabled", Type: field.TypeBool, Nullable: true, Comment: "是否启用", Default: true},
		{Name: "name", Type: field.TypeString, Comment: "沙箱名"},
		{Name: "status", Type: field.TypeEnum, Nullable: true, Comment: "状态", Enums: []string{"UNSPECIFIED", "CREATING", "RUNNING", "STOPPED", "RESTARTING", "ERROR", "DELETING"}, Default: "UNSPECIFIED"},
		{Name: "tenant_name", Type: field.TypeString, Comment: "租户名"},
		{Name: "command_mapping", Type: field.TypeJSON, Nullable: true, Comment: "命令映射"},
		{Name: "env", Type: field.TypeJSON, Nullable: true, Comment: "环境变量"},
		{Name: "deployment_name", Type: field.TypeString, Comment: "部署名"},
		{Name: "url", Type: field.TypeString, Nullable: true, Comment: "域名"},
		{Name: "password", Type: field.TypeString, Nullable: true, Comment: "访问密码"},
		{Name: "model_id", Type: field.TypeUint64, Nullable: true, Comment: "关联的模型ID"},
		{Name: "model_name", Type: field.TypeString, Nullable: true, Comment: "关联的模型名称"},
		{Name: "quota", Type: field.TypeJSON, Nullable: true, Comment: "资源配额"},
		{Name: "started_at", Type: field.TypeTime, Nullable: true, Comment: "开始运行时间"},
		{Name: "finished_at", Type: field.TypeTime, Nullable: true, Comment: "结束时间"},
		{Name: "billing_duration_sec", Type: field.TypeInt64, Comment: "计费时长(秒)", Default: 0},
		{Name: "expiration_minutes", Type: field.TypeInt64, Comment: "自动过期时长(分钟)", Default: 0},
	}
	// SandboxesTable holds the schema information for the "sandboxes" table.
	SandboxesTable = &schema.Table{
		Name:       "sandboxes",
		Comment:    "沙箱表",
		Columns:    SandboxesColumns,
		PrimaryKey: []*schema.Column{SandboxesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "idx_sandbox_name",
				Unique:  false,
				Columns: []*schema.Column{SandboxesColumns[8]},
			},
			{
				Name:    "uk_tenant_deployment",
				Unique:  true,
				Columns: []*schema.Column{SandboxesColumns[10], SandboxesColumns[13]},
			},
		},
	}
	// TenantsColumns holds the columns for the "tenants" table.
	TenantsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true, Comment: "id"},
		{Name: "created_at", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "remark", Type: field.TypeString, Nullable: true, Comment: "备注"},
		{Name: "description", Type: field.TypeString, Nullable: true, Comment: "描述"},
		{Name: "tags", Type: field.TypeJSON, Nullable: true, Comment: "tags associated with the object"},
		{Name: "is_enabled", Type: field.TypeBool, Nullable: true, Comment: "是否启用", Default: true},
		{Name: "name", Type: field.TypeString, Comment: "租户名"},
	}
	// TenantsTable holds the schema information for the "tenants" table.
	TenantsTable = &schema.Table{
		Name:       "tenants",
		Comment:    "租户表",
		Columns:    TenantsColumns,
		PrimaryKey: []*schema.Column{TenantsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "idx_tenant_name",
				Unique:  false,
				Columns: []*schema.Column{TenantsColumns[8]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		InferencesTable,
		ModelsTable,
		SandboxesTable,
		TenantsTable,
	}
)

func init() {
	InferencesTable.Annotation = &entsql.Annotation{
		Table:     "inferences",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_bin",
	}
	ModelsTable.Annotation = &entsql.Annotation{
		Table:     "models",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_bin",
	}
	SandboxesTable.Annotation = &entsql.Annotation{
		Table:     "sandboxes",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_bin",
	}
	TenantsTable.Annotation = &entsql.Annotation{
		Table:     "tenants",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_bin",
	}
}
