// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Inference is the predicate function for inference builders.
type Inference func(*sql.Selector)

// Model is the predicate function for model builders.
type Model func(*sql.Selector)

// Sandbox is the predicate function for sandbox builders.
type Sandbox func(*sql.Selector)

// Tenant is the predicate function for tenant builders.
type Tenant func(*sql.Selector)
