// Code generated by ent, DO NOT EDIT.

package sandbox

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the sandbox type in the database.
	Label = "sandbox"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldRemark holds the string denoting the remark field in the database.
	FieldRemark = "remark"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldTags holds the string denoting the tags field in the database.
	FieldTags = "tags"
	// FieldIsEnabled holds the string denoting the is_enabled field in the database.
	FieldIsEnabled = "is_enabled"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldTenantName holds the string denoting the tenant_name field in the database.
	FieldTenantName = "tenant_name"
	// FieldCommandMapping holds the string denoting the command_mapping field in the database.
	FieldCommandMapping = "command_mapping"
	// FieldEnv holds the string denoting the env field in the database.
	FieldEnv = "env"
	// FieldDeploymentName holds the string denoting the deployment_name field in the database.
	FieldDeploymentName = "deployment_name"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// FieldModelID holds the string denoting the model_id field in the database.
	FieldModelID = "model_id"
	// FieldModelName holds the string denoting the model_name field in the database.
	FieldModelName = "model_name"
	// FieldQuota holds the string denoting the quota field in the database.
	FieldQuota = "quota"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldFinishedAt holds the string denoting the finished_at field in the database.
	FieldFinishedAt = "finished_at"
	// FieldBillingDurationSec holds the string denoting the billing_duration_sec field in the database.
	FieldBillingDurationSec = "billing_duration_sec"
	// FieldExpirationMinutes holds the string denoting the expiration_minutes field in the database.
	FieldExpirationMinutes = "expiration_minutes"
	// Table holds the table name of the sandbox in the database.
	Table = "sandboxes"
)

// Columns holds all SQL columns for sandbox fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldRemark,
	FieldDescription,
	FieldTags,
	FieldIsEnabled,
	FieldName,
	FieldStatus,
	FieldTenantName,
	FieldCommandMapping,
	FieldEnv,
	FieldDeploymentName,
	FieldURL,
	FieldPassword,
	FieldModelID,
	FieldModelName,
	FieldQuota,
	FieldStartedAt,
	FieldFinishedAt,
	FieldBillingDurationSec,
	FieldExpirationMinutes,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultTags holds the default value on creation for the "tags" field.
	DefaultTags []string
	// DefaultIsEnabled holds the default value on creation for the "is_enabled" field.
	DefaultIsEnabled bool
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// TenantNameValidator is a validator for the "tenant_name" field. It is called by the builders before save.
	TenantNameValidator func(string) error
	// DefaultCommandMapping holds the default value on creation for the "command_mapping" field.
	DefaultCommandMapping map[string]string
	// DefaultEnv holds the default value on creation for the "env" field.
	DefaultEnv map[string]string
	// DeploymentNameValidator is a validator for the "deployment_name" field. It is called by the builders before save.
	DeploymentNameValidator func(string) error
	// URLValidator is a validator for the "url" field. It is called by the builders before save.
	URLValidator func(string) error
	// DefaultBillingDurationSec holds the default value on creation for the "billing_duration_sec" field.
	DefaultBillingDurationSec int64
	// DefaultExpirationMinutes holds the default value on creation for the "expiration_minutes" field.
	DefaultExpirationMinutes int64
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(uint64) error
)

// Status defines the type for the "status" enum field.
type Status string

// StatusUnspecified is the default value of the Status enum.
const DefaultStatus = StatusUnspecified

// Status values.
const (
	StatusUnspecified Status = "UNSPECIFIED"
	StatusCreating    Status = "CREATING"
	StatusRunning     Status = "RUNNING"
	StatusStopped     Status = "STOPPED"
	StatusRestarting  Status = "RESTARTING"
	StatusError       Status = "ERROR"
	StatusDeleting    Status = "DELETING"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusUnspecified, StatusCreating, StatusRunning, StatusStopped, StatusRestarting, StatusError, StatusDeleting:
		return nil
	default:
		return fmt.Errorf("sandbox: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Sandbox queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByRemark orders the results by the remark field.
func ByRemark(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemark, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByIsEnabled orders the results by the is_enabled field.
func ByIsEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsEnabled, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByTenantName orders the results by the tenant_name field.
func ByTenantName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantName, opts...).ToFunc()
}

// ByDeploymentName orders the results by the deployment_name field.
func ByDeploymentName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeploymentName, opts...).ToFunc()
}

// ByURL orders the results by the url field.
func ByURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldURL, opts...).ToFunc()
}

// ByPassword orders the results by the password field.
func ByPassword(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPassword, opts...).ToFunc()
}

// ByModelID orders the results by the model_id field.
func ByModelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelID, opts...).ToFunc()
}

// ByModelName orders the results by the model_name field.
func ByModelName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelName, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByFinishedAt orders the results by the finished_at field.
func ByFinishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinishedAt, opts...).ToFunc()
}

// ByBillingDurationSec orders the results by the billing_duration_sec field.
func ByBillingDurationSec(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBillingDurationSec, opts...).ToFunc()
}

// ByExpirationMinutes orders the results by the expiration_minutes field.
func ByExpirationMinutes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpirationMinutes, opts...).ToFunc()
}
