// Code generated by ent, DO NOT EDIT.

package sandbox

import (
	"go-wind-admin/app/server/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id uint64) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint64) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint64) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint64) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint64) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint64) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint64) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint64) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint64) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldEQ(FieldDeletedAt, v))
}

// Remark applies equality check predicate on the "remark" field. It's identical to RemarkEQ.
func Remark(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldEQ(FieldRemark, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldEQ(FieldDescription, v))
}

// IsEnabled applies equality check predicate on the "is_enabled" field. It's identical to IsEnabledEQ.
func IsEnabled(v bool) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldEQ(FieldIsEnabled, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldEQ(FieldName, v))
}

// TenantName applies equality check predicate on the "tenant_name" field. It's identical to TenantNameEQ.
func TenantName(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldEQ(FieldTenantName, v))
}

// DeploymentName applies equality check predicate on the "deployment_name" field. It's identical to DeploymentNameEQ.
func DeploymentName(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldEQ(FieldDeploymentName, v))
}

// URL applies equality check predicate on the "url" field. It's identical to URLEQ.
func URL(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldEQ(FieldURL, v))
}

// Password applies equality check predicate on the "password" field. It's identical to PasswordEQ.
func Password(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldEQ(FieldPassword, v))
}

// ModelID applies equality check predicate on the "model_id" field. It's identical to ModelIDEQ.
func ModelID(v uint64) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldEQ(FieldModelID, v))
}

// ModelName applies equality check predicate on the "model_name" field. It's identical to ModelNameEQ.
func ModelName(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldEQ(FieldModelName, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldEQ(FieldStartedAt, v))
}

// FinishedAt applies equality check predicate on the "finished_at" field. It's identical to FinishedAtEQ.
func FinishedAt(v time.Time) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldEQ(FieldFinishedAt, v))
}

// BillingDurationSec applies equality check predicate on the "billing_duration_sec" field. It's identical to BillingDurationSecEQ.
func BillingDurationSec(v int64) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldEQ(FieldBillingDurationSec, v))
}

// ExpirationMinutes applies equality check predicate on the "expiration_minutes" field. It's identical to ExpirationMinutesEQ.
func ExpirationMinutes(v int64) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldEQ(FieldExpirationMinutes, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.Sandbox {
	return predicate.Sandbox(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.Sandbox {
	return predicate.Sandbox(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.Sandbox {
	return predicate.Sandbox(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.Sandbox {
	return predicate.Sandbox(sql.FieldNotNull(FieldUpdatedAt))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.Sandbox {
	return predicate.Sandbox(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.Sandbox {
	return predicate.Sandbox(sql.FieldNotNull(FieldDeletedAt))
}

// RemarkEQ applies the EQ predicate on the "remark" field.
func RemarkEQ(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldEQ(FieldRemark, v))
}

// RemarkNEQ applies the NEQ predicate on the "remark" field.
func RemarkNEQ(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldNEQ(FieldRemark, v))
}

// RemarkIn applies the In predicate on the "remark" field.
func RemarkIn(vs ...string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldIn(FieldRemark, vs...))
}

// RemarkNotIn applies the NotIn predicate on the "remark" field.
func RemarkNotIn(vs ...string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldNotIn(FieldRemark, vs...))
}

// RemarkGT applies the GT predicate on the "remark" field.
func RemarkGT(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldGT(FieldRemark, v))
}

// RemarkGTE applies the GTE predicate on the "remark" field.
func RemarkGTE(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldGTE(FieldRemark, v))
}

// RemarkLT applies the LT predicate on the "remark" field.
func RemarkLT(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldLT(FieldRemark, v))
}

// RemarkLTE applies the LTE predicate on the "remark" field.
func RemarkLTE(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldLTE(FieldRemark, v))
}

// RemarkContains applies the Contains predicate on the "remark" field.
func RemarkContains(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldContains(FieldRemark, v))
}

// RemarkHasPrefix applies the HasPrefix predicate on the "remark" field.
func RemarkHasPrefix(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldHasPrefix(FieldRemark, v))
}

// RemarkHasSuffix applies the HasSuffix predicate on the "remark" field.
func RemarkHasSuffix(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldHasSuffix(FieldRemark, v))
}

// RemarkIsNil applies the IsNil predicate on the "remark" field.
func RemarkIsNil() predicate.Sandbox {
	return predicate.Sandbox(sql.FieldIsNull(FieldRemark))
}

// RemarkNotNil applies the NotNil predicate on the "remark" field.
func RemarkNotNil() predicate.Sandbox {
	return predicate.Sandbox(sql.FieldNotNull(FieldRemark))
}

// RemarkEqualFold applies the EqualFold predicate on the "remark" field.
func RemarkEqualFold(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldEqualFold(FieldRemark, v))
}

// RemarkContainsFold applies the ContainsFold predicate on the "remark" field.
func RemarkContainsFold(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldContainsFold(FieldRemark, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Sandbox {
	return predicate.Sandbox(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Sandbox {
	return predicate.Sandbox(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldContainsFold(FieldDescription, v))
}

// TagsIsNil applies the IsNil predicate on the "tags" field.
func TagsIsNil() predicate.Sandbox {
	return predicate.Sandbox(sql.FieldIsNull(FieldTags))
}

// TagsNotNil applies the NotNil predicate on the "tags" field.
func TagsNotNil() predicate.Sandbox {
	return predicate.Sandbox(sql.FieldNotNull(FieldTags))
}

// IsEnabledEQ applies the EQ predicate on the "is_enabled" field.
func IsEnabledEQ(v bool) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldEQ(FieldIsEnabled, v))
}

// IsEnabledNEQ applies the NEQ predicate on the "is_enabled" field.
func IsEnabledNEQ(v bool) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldNEQ(FieldIsEnabled, v))
}

// IsEnabledIsNil applies the IsNil predicate on the "is_enabled" field.
func IsEnabledIsNil() predicate.Sandbox {
	return predicate.Sandbox(sql.FieldIsNull(FieldIsEnabled))
}

// IsEnabledNotNil applies the NotNil predicate on the "is_enabled" field.
func IsEnabledNotNil() predicate.Sandbox {
	return predicate.Sandbox(sql.FieldNotNull(FieldIsEnabled))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldContainsFold(FieldName, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusIsNil applies the IsNil predicate on the "status" field.
func StatusIsNil() predicate.Sandbox {
	return predicate.Sandbox(sql.FieldIsNull(FieldStatus))
}

// StatusNotNil applies the NotNil predicate on the "status" field.
func StatusNotNil() predicate.Sandbox {
	return predicate.Sandbox(sql.FieldNotNull(FieldStatus))
}

// TenantNameEQ applies the EQ predicate on the "tenant_name" field.
func TenantNameEQ(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldEQ(FieldTenantName, v))
}

// TenantNameNEQ applies the NEQ predicate on the "tenant_name" field.
func TenantNameNEQ(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldNEQ(FieldTenantName, v))
}

// TenantNameIn applies the In predicate on the "tenant_name" field.
func TenantNameIn(vs ...string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldIn(FieldTenantName, vs...))
}

// TenantNameNotIn applies the NotIn predicate on the "tenant_name" field.
func TenantNameNotIn(vs ...string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldNotIn(FieldTenantName, vs...))
}

// TenantNameGT applies the GT predicate on the "tenant_name" field.
func TenantNameGT(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldGT(FieldTenantName, v))
}

// TenantNameGTE applies the GTE predicate on the "tenant_name" field.
func TenantNameGTE(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldGTE(FieldTenantName, v))
}

// TenantNameLT applies the LT predicate on the "tenant_name" field.
func TenantNameLT(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldLT(FieldTenantName, v))
}

// TenantNameLTE applies the LTE predicate on the "tenant_name" field.
func TenantNameLTE(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldLTE(FieldTenantName, v))
}

// TenantNameContains applies the Contains predicate on the "tenant_name" field.
func TenantNameContains(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldContains(FieldTenantName, v))
}

// TenantNameHasPrefix applies the HasPrefix predicate on the "tenant_name" field.
func TenantNameHasPrefix(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldHasPrefix(FieldTenantName, v))
}

// TenantNameHasSuffix applies the HasSuffix predicate on the "tenant_name" field.
func TenantNameHasSuffix(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldHasSuffix(FieldTenantName, v))
}

// TenantNameEqualFold applies the EqualFold predicate on the "tenant_name" field.
func TenantNameEqualFold(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldEqualFold(FieldTenantName, v))
}

// TenantNameContainsFold applies the ContainsFold predicate on the "tenant_name" field.
func TenantNameContainsFold(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldContainsFold(FieldTenantName, v))
}

// CommandMappingIsNil applies the IsNil predicate on the "command_mapping" field.
func CommandMappingIsNil() predicate.Sandbox {
	return predicate.Sandbox(sql.FieldIsNull(FieldCommandMapping))
}

// CommandMappingNotNil applies the NotNil predicate on the "command_mapping" field.
func CommandMappingNotNil() predicate.Sandbox {
	return predicate.Sandbox(sql.FieldNotNull(FieldCommandMapping))
}

// EnvIsNil applies the IsNil predicate on the "env" field.
func EnvIsNil() predicate.Sandbox {
	return predicate.Sandbox(sql.FieldIsNull(FieldEnv))
}

// EnvNotNil applies the NotNil predicate on the "env" field.
func EnvNotNil() predicate.Sandbox {
	return predicate.Sandbox(sql.FieldNotNull(FieldEnv))
}

// DeploymentNameEQ applies the EQ predicate on the "deployment_name" field.
func DeploymentNameEQ(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldEQ(FieldDeploymentName, v))
}

// DeploymentNameNEQ applies the NEQ predicate on the "deployment_name" field.
func DeploymentNameNEQ(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldNEQ(FieldDeploymentName, v))
}

// DeploymentNameIn applies the In predicate on the "deployment_name" field.
func DeploymentNameIn(vs ...string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldIn(FieldDeploymentName, vs...))
}

// DeploymentNameNotIn applies the NotIn predicate on the "deployment_name" field.
func DeploymentNameNotIn(vs ...string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldNotIn(FieldDeploymentName, vs...))
}

// DeploymentNameGT applies the GT predicate on the "deployment_name" field.
func DeploymentNameGT(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldGT(FieldDeploymentName, v))
}

// DeploymentNameGTE applies the GTE predicate on the "deployment_name" field.
func DeploymentNameGTE(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldGTE(FieldDeploymentName, v))
}

// DeploymentNameLT applies the LT predicate on the "deployment_name" field.
func DeploymentNameLT(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldLT(FieldDeploymentName, v))
}

// DeploymentNameLTE applies the LTE predicate on the "deployment_name" field.
func DeploymentNameLTE(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldLTE(FieldDeploymentName, v))
}

// DeploymentNameContains applies the Contains predicate on the "deployment_name" field.
func DeploymentNameContains(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldContains(FieldDeploymentName, v))
}

// DeploymentNameHasPrefix applies the HasPrefix predicate on the "deployment_name" field.
func DeploymentNameHasPrefix(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldHasPrefix(FieldDeploymentName, v))
}

// DeploymentNameHasSuffix applies the HasSuffix predicate on the "deployment_name" field.
func DeploymentNameHasSuffix(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldHasSuffix(FieldDeploymentName, v))
}

// DeploymentNameEqualFold applies the EqualFold predicate on the "deployment_name" field.
func DeploymentNameEqualFold(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldEqualFold(FieldDeploymentName, v))
}

// DeploymentNameContainsFold applies the ContainsFold predicate on the "deployment_name" field.
func DeploymentNameContainsFold(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldContainsFold(FieldDeploymentName, v))
}

// URLEQ applies the EQ predicate on the "url" field.
func URLEQ(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldEQ(FieldURL, v))
}

// URLNEQ applies the NEQ predicate on the "url" field.
func URLNEQ(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldNEQ(FieldURL, v))
}

// URLIn applies the In predicate on the "url" field.
func URLIn(vs ...string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldIn(FieldURL, vs...))
}

// URLNotIn applies the NotIn predicate on the "url" field.
func URLNotIn(vs ...string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldNotIn(FieldURL, vs...))
}

// URLGT applies the GT predicate on the "url" field.
func URLGT(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldGT(FieldURL, v))
}

// URLGTE applies the GTE predicate on the "url" field.
func URLGTE(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldGTE(FieldURL, v))
}

// URLLT applies the LT predicate on the "url" field.
func URLLT(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldLT(FieldURL, v))
}

// URLLTE applies the LTE predicate on the "url" field.
func URLLTE(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldLTE(FieldURL, v))
}

// URLContains applies the Contains predicate on the "url" field.
func URLContains(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldContains(FieldURL, v))
}

// URLHasPrefix applies the HasPrefix predicate on the "url" field.
func URLHasPrefix(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldHasPrefix(FieldURL, v))
}

// URLHasSuffix applies the HasSuffix predicate on the "url" field.
func URLHasSuffix(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldHasSuffix(FieldURL, v))
}

// URLIsNil applies the IsNil predicate on the "url" field.
func URLIsNil() predicate.Sandbox {
	return predicate.Sandbox(sql.FieldIsNull(FieldURL))
}

// URLNotNil applies the NotNil predicate on the "url" field.
func URLNotNil() predicate.Sandbox {
	return predicate.Sandbox(sql.FieldNotNull(FieldURL))
}

// URLEqualFold applies the EqualFold predicate on the "url" field.
func URLEqualFold(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldEqualFold(FieldURL, v))
}

// URLContainsFold applies the ContainsFold predicate on the "url" field.
func URLContainsFold(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldContainsFold(FieldURL, v))
}

// PasswordEQ applies the EQ predicate on the "password" field.
func PasswordEQ(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldEQ(FieldPassword, v))
}

// PasswordNEQ applies the NEQ predicate on the "password" field.
func PasswordNEQ(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldNEQ(FieldPassword, v))
}

// PasswordIn applies the In predicate on the "password" field.
func PasswordIn(vs ...string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldIn(FieldPassword, vs...))
}

// PasswordNotIn applies the NotIn predicate on the "password" field.
func PasswordNotIn(vs ...string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldNotIn(FieldPassword, vs...))
}

// PasswordGT applies the GT predicate on the "password" field.
func PasswordGT(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldGT(FieldPassword, v))
}

// PasswordGTE applies the GTE predicate on the "password" field.
func PasswordGTE(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldGTE(FieldPassword, v))
}

// PasswordLT applies the LT predicate on the "password" field.
func PasswordLT(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldLT(FieldPassword, v))
}

// PasswordLTE applies the LTE predicate on the "password" field.
func PasswordLTE(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldLTE(FieldPassword, v))
}

// PasswordContains applies the Contains predicate on the "password" field.
func PasswordContains(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldContains(FieldPassword, v))
}

// PasswordHasPrefix applies the HasPrefix predicate on the "password" field.
func PasswordHasPrefix(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldHasPrefix(FieldPassword, v))
}

// PasswordHasSuffix applies the HasSuffix predicate on the "password" field.
func PasswordHasSuffix(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldHasSuffix(FieldPassword, v))
}

// PasswordIsNil applies the IsNil predicate on the "password" field.
func PasswordIsNil() predicate.Sandbox {
	return predicate.Sandbox(sql.FieldIsNull(FieldPassword))
}

// PasswordNotNil applies the NotNil predicate on the "password" field.
func PasswordNotNil() predicate.Sandbox {
	return predicate.Sandbox(sql.FieldNotNull(FieldPassword))
}

// PasswordEqualFold applies the EqualFold predicate on the "password" field.
func PasswordEqualFold(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldEqualFold(FieldPassword, v))
}

// PasswordContainsFold applies the ContainsFold predicate on the "password" field.
func PasswordContainsFold(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldContainsFold(FieldPassword, v))
}

// ModelIDEQ applies the EQ predicate on the "model_id" field.
func ModelIDEQ(v uint64) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldEQ(FieldModelID, v))
}

// ModelIDNEQ applies the NEQ predicate on the "model_id" field.
func ModelIDNEQ(v uint64) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldNEQ(FieldModelID, v))
}

// ModelIDIn applies the In predicate on the "model_id" field.
func ModelIDIn(vs ...uint64) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldIn(FieldModelID, vs...))
}

// ModelIDNotIn applies the NotIn predicate on the "model_id" field.
func ModelIDNotIn(vs ...uint64) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldNotIn(FieldModelID, vs...))
}

// ModelIDGT applies the GT predicate on the "model_id" field.
func ModelIDGT(v uint64) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldGT(FieldModelID, v))
}

// ModelIDGTE applies the GTE predicate on the "model_id" field.
func ModelIDGTE(v uint64) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldGTE(FieldModelID, v))
}

// ModelIDLT applies the LT predicate on the "model_id" field.
func ModelIDLT(v uint64) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldLT(FieldModelID, v))
}

// ModelIDLTE applies the LTE predicate on the "model_id" field.
func ModelIDLTE(v uint64) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldLTE(FieldModelID, v))
}

// ModelIDIsNil applies the IsNil predicate on the "model_id" field.
func ModelIDIsNil() predicate.Sandbox {
	return predicate.Sandbox(sql.FieldIsNull(FieldModelID))
}

// ModelIDNotNil applies the NotNil predicate on the "model_id" field.
func ModelIDNotNil() predicate.Sandbox {
	return predicate.Sandbox(sql.FieldNotNull(FieldModelID))
}

// ModelNameEQ applies the EQ predicate on the "model_name" field.
func ModelNameEQ(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldEQ(FieldModelName, v))
}

// ModelNameNEQ applies the NEQ predicate on the "model_name" field.
func ModelNameNEQ(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldNEQ(FieldModelName, v))
}

// ModelNameIn applies the In predicate on the "model_name" field.
func ModelNameIn(vs ...string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldIn(FieldModelName, vs...))
}

// ModelNameNotIn applies the NotIn predicate on the "model_name" field.
func ModelNameNotIn(vs ...string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldNotIn(FieldModelName, vs...))
}

// ModelNameGT applies the GT predicate on the "model_name" field.
func ModelNameGT(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldGT(FieldModelName, v))
}

// ModelNameGTE applies the GTE predicate on the "model_name" field.
func ModelNameGTE(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldGTE(FieldModelName, v))
}

// ModelNameLT applies the LT predicate on the "model_name" field.
func ModelNameLT(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldLT(FieldModelName, v))
}

// ModelNameLTE applies the LTE predicate on the "model_name" field.
func ModelNameLTE(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldLTE(FieldModelName, v))
}

// ModelNameContains applies the Contains predicate on the "model_name" field.
func ModelNameContains(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldContains(FieldModelName, v))
}

// ModelNameHasPrefix applies the HasPrefix predicate on the "model_name" field.
func ModelNameHasPrefix(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldHasPrefix(FieldModelName, v))
}

// ModelNameHasSuffix applies the HasSuffix predicate on the "model_name" field.
func ModelNameHasSuffix(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldHasSuffix(FieldModelName, v))
}

// ModelNameIsNil applies the IsNil predicate on the "model_name" field.
func ModelNameIsNil() predicate.Sandbox {
	return predicate.Sandbox(sql.FieldIsNull(FieldModelName))
}

// ModelNameNotNil applies the NotNil predicate on the "model_name" field.
func ModelNameNotNil() predicate.Sandbox {
	return predicate.Sandbox(sql.FieldNotNull(FieldModelName))
}

// ModelNameEqualFold applies the EqualFold predicate on the "model_name" field.
func ModelNameEqualFold(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldEqualFold(FieldModelName, v))
}

// ModelNameContainsFold applies the ContainsFold predicate on the "model_name" field.
func ModelNameContainsFold(v string) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldContainsFold(FieldModelName, v))
}

// QuotaIsNil applies the IsNil predicate on the "quota" field.
func QuotaIsNil() predicate.Sandbox {
	return predicate.Sandbox(sql.FieldIsNull(FieldQuota))
}

// QuotaNotNil applies the NotNil predicate on the "quota" field.
func QuotaNotNil() predicate.Sandbox {
	return predicate.Sandbox(sql.FieldNotNull(FieldQuota))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldLTE(FieldStartedAt, v))
}

// StartedAtIsNil applies the IsNil predicate on the "started_at" field.
func StartedAtIsNil() predicate.Sandbox {
	return predicate.Sandbox(sql.FieldIsNull(FieldStartedAt))
}

// StartedAtNotNil applies the NotNil predicate on the "started_at" field.
func StartedAtNotNil() predicate.Sandbox {
	return predicate.Sandbox(sql.FieldNotNull(FieldStartedAt))
}

// FinishedAtEQ applies the EQ predicate on the "finished_at" field.
func FinishedAtEQ(v time.Time) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldEQ(FieldFinishedAt, v))
}

// FinishedAtNEQ applies the NEQ predicate on the "finished_at" field.
func FinishedAtNEQ(v time.Time) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldNEQ(FieldFinishedAt, v))
}

// FinishedAtIn applies the In predicate on the "finished_at" field.
func FinishedAtIn(vs ...time.Time) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldIn(FieldFinishedAt, vs...))
}

// FinishedAtNotIn applies the NotIn predicate on the "finished_at" field.
func FinishedAtNotIn(vs ...time.Time) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldNotIn(FieldFinishedAt, vs...))
}

// FinishedAtGT applies the GT predicate on the "finished_at" field.
func FinishedAtGT(v time.Time) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldGT(FieldFinishedAt, v))
}

// FinishedAtGTE applies the GTE predicate on the "finished_at" field.
func FinishedAtGTE(v time.Time) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldGTE(FieldFinishedAt, v))
}

// FinishedAtLT applies the LT predicate on the "finished_at" field.
func FinishedAtLT(v time.Time) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldLT(FieldFinishedAt, v))
}

// FinishedAtLTE applies the LTE predicate on the "finished_at" field.
func FinishedAtLTE(v time.Time) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldLTE(FieldFinishedAt, v))
}

// FinishedAtIsNil applies the IsNil predicate on the "finished_at" field.
func FinishedAtIsNil() predicate.Sandbox {
	return predicate.Sandbox(sql.FieldIsNull(FieldFinishedAt))
}

// FinishedAtNotNil applies the NotNil predicate on the "finished_at" field.
func FinishedAtNotNil() predicate.Sandbox {
	return predicate.Sandbox(sql.FieldNotNull(FieldFinishedAt))
}

// BillingDurationSecEQ applies the EQ predicate on the "billing_duration_sec" field.
func BillingDurationSecEQ(v int64) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldEQ(FieldBillingDurationSec, v))
}

// BillingDurationSecNEQ applies the NEQ predicate on the "billing_duration_sec" field.
func BillingDurationSecNEQ(v int64) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldNEQ(FieldBillingDurationSec, v))
}

// BillingDurationSecIn applies the In predicate on the "billing_duration_sec" field.
func BillingDurationSecIn(vs ...int64) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldIn(FieldBillingDurationSec, vs...))
}

// BillingDurationSecNotIn applies the NotIn predicate on the "billing_duration_sec" field.
func BillingDurationSecNotIn(vs ...int64) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldNotIn(FieldBillingDurationSec, vs...))
}

// BillingDurationSecGT applies the GT predicate on the "billing_duration_sec" field.
func BillingDurationSecGT(v int64) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldGT(FieldBillingDurationSec, v))
}

// BillingDurationSecGTE applies the GTE predicate on the "billing_duration_sec" field.
func BillingDurationSecGTE(v int64) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldGTE(FieldBillingDurationSec, v))
}

// BillingDurationSecLT applies the LT predicate on the "billing_duration_sec" field.
func BillingDurationSecLT(v int64) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldLT(FieldBillingDurationSec, v))
}

// BillingDurationSecLTE applies the LTE predicate on the "billing_duration_sec" field.
func BillingDurationSecLTE(v int64) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldLTE(FieldBillingDurationSec, v))
}

// ExpirationMinutesEQ applies the EQ predicate on the "expiration_minutes" field.
func ExpirationMinutesEQ(v int64) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldEQ(FieldExpirationMinutes, v))
}

// ExpirationMinutesNEQ applies the NEQ predicate on the "expiration_minutes" field.
func ExpirationMinutesNEQ(v int64) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldNEQ(FieldExpirationMinutes, v))
}

// ExpirationMinutesIn applies the In predicate on the "expiration_minutes" field.
func ExpirationMinutesIn(vs ...int64) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldIn(FieldExpirationMinutes, vs...))
}

// ExpirationMinutesNotIn applies the NotIn predicate on the "expiration_minutes" field.
func ExpirationMinutesNotIn(vs ...int64) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldNotIn(FieldExpirationMinutes, vs...))
}

// ExpirationMinutesGT applies the GT predicate on the "expiration_minutes" field.
func ExpirationMinutesGT(v int64) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldGT(FieldExpirationMinutes, v))
}

// ExpirationMinutesGTE applies the GTE predicate on the "expiration_minutes" field.
func ExpirationMinutesGTE(v int64) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldGTE(FieldExpirationMinutes, v))
}

// ExpirationMinutesLT applies the LT predicate on the "expiration_minutes" field.
func ExpirationMinutesLT(v int64) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldLT(FieldExpirationMinutes, v))
}

// ExpirationMinutesLTE applies the LTE predicate on the "expiration_minutes" field.
func ExpirationMinutesLTE(v int64) predicate.Sandbox {
	return predicate.Sandbox(sql.FieldLTE(FieldExpirationMinutes, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Sandbox) predicate.Sandbox {
	return predicate.Sandbox(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Sandbox) predicate.Sandbox {
	return predicate.Sandbox(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Sandbox) predicate.Sandbox {
	return predicate.Sandbox(sql.NotPredicates(p))
}
