// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/tx7do/kratos-bootstrap/bootstrap"
	"go-wind-admin/app/server/service/internal/biz"
	"go-wind-admin/app/server/service/internal/data"
	"go-wind-admin/app/server/service/internal/server"
	"go-wind-admin/app/server/service/internal/service"
)

// Injectors from wire.go:

// initApp 初始化 kratos 应用的 Wire provider 入口。
// initApp initializes the Wire provider entry for the kratos application.
//
// 参数 / Parameters:
//   - *bootstrap.Context: 引导上下文 / *bootstrap.Context: bootstrap context
//
// 返回 / Returns:
//   - *kratos.App: 已构建的应用实例 / *kratos.App: constructed application instance
//   - func(): 应用关闭时的清理函数 / func(): cleanup function to run on shutdown
//   - error: 构建过程中可能发生的错误 / error: possible construction error
func initApp(context *bootstrap.Context) (*kratos.App, func(), error) {
	v := server.NewRestMiddleware(context)
	entClient, cleanup, err := data.NewEntClient(context)
	if err != nil {
		return nil, nil, err
	}
	modelRepo := data.NewModelRepo(context, entClient)
	confv1Bootstrap := data.NewBootstrapConfig(context)
	clientWithResponses, err := data.NewLakeFSClient(context, confv1Bootstrap)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	minIOClient := data.NewMinIoClient(context)
	modelRegistryService := service.NewRegistryService(context, clientWithResponses, minIOClient, confv1Bootstrap)
	modelService := service.NewModelService(context, modelRepo, modelRegistryService)
	sandboxRepo := data.NewSandboxRepo(context, entClient)
	kubernetesInterface, err := data.NewKubeClient(confv1Bootstrap)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	versionedInterface, err := data.NewKueueClient(confv1Bootstrap)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	kueueController := biz.NewKueueController(context, kubernetesInterface, versionedInterface)
	appController := biz.NewAppController(context, kubernetesInterface)
	client := data.NewTemporalClient(confv1Bootstrap)
	sandboxService := service.NewSandboxService(context, sandboxRepo, modelRepo, kueueController, appController, client)
	tenantService := service.NewTenantService(context, kueueController)
	httpServer, err := server.NewRestServer(context, v, modelService, sandboxService, tenantService)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	sseServer := server.NewSseServer(context)
	grpcServer, err := server.NewGrpcServer(context, v, modelService, tenantService)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	app := newApp(context, httpServer, sseServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
