// Code generated by ent, DO NOT EDIT.

package inference

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the inference type in the database.
	Label = "inference"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldRemark holds the string denoting the remark field in the database.
	FieldRemark = "remark"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldTags holds the string denoting the tags field in the database.
	FieldTags = "tags"
	// FieldIsEnabled holds the string denoting the is_enabled field in the database.
	FieldIsEnabled = "is_enabled"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldTenantName holds the string denoting the tenant_name field in the database.
	FieldTenantName = "tenant_name"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldModelID holds the string denoting the model_id field in the database.
	FieldModelID = "model_id"
	// FieldModelName holds the string denoting the model_name field in the database.
	FieldModelName = "model_name"
	// FieldImage holds the string denoting the image field in the database.
	FieldImage = "image"
	// FieldReplicas holds the string denoting the replicas field in the database.
	FieldReplicas = "replicas"
	// FieldMinReplicas holds the string denoting the min_replicas field in the database.
	FieldMinReplicas = "min_replicas"
	// FieldMaxReplicas holds the string denoting the max_replicas field in the database.
	FieldMaxReplicas = "max_replicas"
	// FieldPort holds the string denoting the port field in the database.
	FieldPort = "port"
	// FieldCommand holds the string denoting the command field in the database.
	FieldCommand = "command"
	// FieldArgs holds the string denoting the args field in the database.
	FieldArgs = "args"
	// FieldEnv holds the string denoting the env field in the database.
	FieldEnv = "env"
	// FieldDeploymentName holds the string denoting the deployment_name field in the database.
	FieldDeploymentName = "deployment_name"
	// FieldServiceName holds the string denoting the service_name field in the database.
	FieldServiceName = "service_name"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// FieldAuthToken holds the string denoting the auth_token field in the database.
	FieldAuthToken = "auth_token"
	// FieldQuota holds the string denoting the quota field in the database.
	FieldQuota = "quota"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldFinishedAt holds the string denoting the finished_at field in the database.
	FieldFinishedAt = "finished_at"
	// FieldLastActivityTime holds the string denoting the last_activity_time field in the database.
	FieldLastActivityTime = "last_activity_time"
	// FieldBillingDurationSec holds the string denoting the billing_duration_sec field in the database.
	FieldBillingDurationSec = "billing_duration_sec"
	// FieldUsageCPUSeconds holds the string denoting the usage_cpu_seconds field in the database.
	FieldUsageCPUSeconds = "usage_cpu_seconds"
	// FieldUsageGpuSeconds holds the string denoting the usage_gpu_seconds field in the database.
	FieldUsageGpuSeconds = "usage_gpu_seconds"
	// FieldUsageReplicaSeconds holds the string denoting the usage_replica_seconds field in the database.
	FieldUsageReplicaSeconds = "usage_replica_seconds"
	// FieldExpirationMinutes holds the string denoting the expiration_minutes field in the database.
	FieldExpirationMinutes = "expiration_minutes"
	// Table holds the table name of the inference in the database.
	Table = "inferences"
)

// Columns holds all SQL columns for inference fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldRemark,
	FieldDescription,
	FieldTags,
	FieldIsEnabled,
	FieldName,
	FieldTenantName,
	FieldStatus,
	FieldModelID,
	FieldModelName,
	FieldImage,
	FieldReplicas,
	FieldMinReplicas,
	FieldMaxReplicas,
	FieldPort,
	FieldCommand,
	FieldArgs,
	FieldEnv,
	FieldDeploymentName,
	FieldServiceName,
	FieldURL,
	FieldAuthToken,
	FieldQuota,
	FieldStartedAt,
	FieldFinishedAt,
	FieldLastActivityTime,
	FieldBillingDurationSec,
	FieldUsageCPUSeconds,
	FieldUsageGpuSeconds,
	FieldUsageReplicaSeconds,
	FieldExpirationMinutes,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultTags holds the default value on creation for the "tags" field.
	DefaultTags []string
	// DefaultIsEnabled holds the default value on creation for the "is_enabled" field.
	DefaultIsEnabled bool
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// TenantNameValidator is a validator for the "tenant_name" field. It is called by the builders before save.
	TenantNameValidator func(string) error
	// DefaultReplicas holds the default value on creation for the "replicas" field.
	DefaultReplicas int32
	// ReplicasValidator is a validator for the "replicas" field. It is called by the builders before save.
	ReplicasValidator func(int32) error
	// DefaultMinReplicas holds the default value on creation for the "min_replicas" field.
	DefaultMinReplicas int32
	// DefaultMaxReplicas holds the default value on creation for the "max_replicas" field.
	DefaultMaxReplicas int32
	// DefaultPort holds the default value on creation for the "port" field.
	DefaultPort int32
	// DeploymentNameValidator is a validator for the "deployment_name" field. It is called by the builders before save.
	DeploymentNameValidator func(string) error
	// ServiceNameValidator is a validator for the "service_name" field. It is called by the builders before save.
	ServiceNameValidator func(string) error
	// DefaultBillingDurationSec holds the default value on creation for the "billing_duration_sec" field.
	DefaultBillingDurationSec int64
	// DefaultUsageCPUSeconds holds the default value on creation for the "usage_cpu_seconds" field.
	DefaultUsageCPUSeconds int64
	// DefaultUsageGpuSeconds holds the default value on creation for the "usage_gpu_seconds" field.
	DefaultUsageGpuSeconds int64
	// DefaultUsageReplicaSeconds holds the default value on creation for the "usage_replica_seconds" field.
	DefaultUsageReplicaSeconds int64
	// DefaultExpirationMinutes holds the default value on creation for the "expiration_minutes" field.
	DefaultExpirationMinutes int64
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(uint64) error
)

// Status defines the type for the "status" enum field.
type Status string

// StatusUnspecified is the default value of the Status enum.
const DefaultStatus = StatusUnspecified

// Status values.
const (
	StatusUnspecified Status = "UNSPECIFIED"
	StatusCreating    Status = "CREATING"
	StatusRunning     Status = "RUNNING"
	StatusStopped     Status = "STOPPED"
	StatusRestarting  Status = "RESTARTING"
	StatusScaling     Status = "SCALING"
	StatusError       Status = "ERROR"
	StatusDeleting    Status = "DELETING"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusUnspecified, StatusCreating, StatusRunning, StatusStopped, StatusRestarting, StatusScaling, StatusError, StatusDeleting:
		return nil
	default:
		return fmt.Errorf("inference: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Inference queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByRemark orders the results by the remark field.
func ByRemark(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemark, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByIsEnabled orders the results by the is_enabled field.
func ByIsEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsEnabled, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByTenantName orders the results by the tenant_name field.
func ByTenantName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantName, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByModelID orders the results by the model_id field.
func ByModelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelID, opts...).ToFunc()
}

// ByModelName orders the results by the model_name field.
func ByModelName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelName, opts...).ToFunc()
}

// ByImage orders the results by the image field.
func ByImage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImage, opts...).ToFunc()
}

// ByReplicas orders the results by the replicas field.
func ByReplicas(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReplicas, opts...).ToFunc()
}

// ByMinReplicas orders the results by the min_replicas field.
func ByMinReplicas(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMinReplicas, opts...).ToFunc()
}

// ByMaxReplicas orders the results by the max_replicas field.
func ByMaxReplicas(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxReplicas, opts...).ToFunc()
}

// ByPort orders the results by the port field.
func ByPort(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPort, opts...).ToFunc()
}

// ByDeploymentName orders the results by the deployment_name field.
func ByDeploymentName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeploymentName, opts...).ToFunc()
}

// ByServiceName orders the results by the service_name field.
func ByServiceName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldServiceName, opts...).ToFunc()
}

// ByURL orders the results by the url field.
func ByURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldURL, opts...).ToFunc()
}

// ByAuthToken orders the results by the auth_token field.
func ByAuthToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthToken, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByFinishedAt orders the results by the finished_at field.
func ByFinishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinishedAt, opts...).ToFunc()
}

// ByLastActivityTime orders the results by the last_activity_time field.
func ByLastActivityTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastActivityTime, opts...).ToFunc()
}

// ByBillingDurationSec orders the results by the billing_duration_sec field.
func ByBillingDurationSec(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBillingDurationSec, opts...).ToFunc()
}

// ByUsageCPUSeconds orders the results by the usage_cpu_seconds field.
func ByUsageCPUSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsageCPUSeconds, opts...).ToFunc()
}

// ByUsageGpuSeconds orders the results by the usage_gpu_seconds field.
func ByUsageGpuSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsageGpuSeconds, opts...).ToFunc()
}

// ByUsageReplicaSeconds orders the results by the usage_replica_seconds field.
func ByUsageReplicaSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsageReplicaSeconds, opts...).ToFunc()
}

// ByExpirationMinutes orders the results by the expiration_minutes field.
func ByExpirationMinutes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpirationMinutes, opts...).ToFunc()
}
