// Code generated by ent, DO NOT EDIT.

package inference

import (
	"go-wind-admin/app/server/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id uint64) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint64) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint64) predicate.Inference {
	return predicate.Inference(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint64) predicate.Inference {
	return predicate.Inference(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint64) predicate.Inference {
	return predicate.Inference(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint64) predicate.Inference {
	return predicate.Inference(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint64) predicate.Inference {
	return predicate.Inference(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint64) predicate.Inference {
	return predicate.Inference(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint64) predicate.Inference {
	return predicate.Inference(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldDeletedAt, v))
}

// Remark applies equality check predicate on the "remark" field. It's identical to RemarkEQ.
func Remark(v string) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldRemark, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldDescription, v))
}

// IsEnabled applies equality check predicate on the "is_enabled" field. It's identical to IsEnabledEQ.
func IsEnabled(v bool) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldIsEnabled, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldName, v))
}

// TenantName applies equality check predicate on the "tenant_name" field. It's identical to TenantNameEQ.
func TenantName(v string) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldTenantName, v))
}

// ModelID applies equality check predicate on the "model_id" field. It's identical to ModelIDEQ.
func ModelID(v uint64) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldModelID, v))
}

// ModelName applies equality check predicate on the "model_name" field. It's identical to ModelNameEQ.
func ModelName(v string) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldModelName, v))
}

// Image applies equality check predicate on the "image" field. It's identical to ImageEQ.
func Image(v string) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldImage, v))
}

// Replicas applies equality check predicate on the "replicas" field. It's identical to ReplicasEQ.
func Replicas(v int32) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldReplicas, v))
}

// MinReplicas applies equality check predicate on the "min_replicas" field. It's identical to MinReplicasEQ.
func MinReplicas(v int32) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldMinReplicas, v))
}

// MaxReplicas applies equality check predicate on the "max_replicas" field. It's identical to MaxReplicasEQ.
func MaxReplicas(v int32) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldMaxReplicas, v))
}

// Port applies equality check predicate on the "port" field. It's identical to PortEQ.
func Port(v int32) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldPort, v))
}

// DeploymentName applies equality check predicate on the "deployment_name" field. It's identical to DeploymentNameEQ.
func DeploymentName(v string) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldDeploymentName, v))
}

// ServiceName applies equality check predicate on the "service_name" field. It's identical to ServiceNameEQ.
func ServiceName(v string) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldServiceName, v))
}

// URL applies equality check predicate on the "url" field. It's identical to URLEQ.
func URL(v string) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldURL, v))
}

// AuthToken applies equality check predicate on the "auth_token" field. It's identical to AuthTokenEQ.
func AuthToken(v string) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldAuthToken, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldStartedAt, v))
}

// FinishedAt applies equality check predicate on the "finished_at" field. It's identical to FinishedAtEQ.
func FinishedAt(v time.Time) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldFinishedAt, v))
}

// LastActivityTime applies equality check predicate on the "last_activity_time" field. It's identical to LastActivityTimeEQ.
func LastActivityTime(v time.Time) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldLastActivityTime, v))
}

// BillingDurationSec applies equality check predicate on the "billing_duration_sec" field. It's identical to BillingDurationSecEQ.
func BillingDurationSec(v int64) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldBillingDurationSec, v))
}

// UsageCPUSeconds applies equality check predicate on the "usage_cpu_seconds" field. It's identical to UsageCPUSecondsEQ.
func UsageCPUSeconds(v int64) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldUsageCPUSeconds, v))
}

// UsageGpuSeconds applies equality check predicate on the "usage_gpu_seconds" field. It's identical to UsageGpuSecondsEQ.
func UsageGpuSeconds(v int64) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldUsageGpuSeconds, v))
}

// UsageReplicaSeconds applies equality check predicate on the "usage_replica_seconds" field. It's identical to UsageReplicaSecondsEQ.
func UsageReplicaSeconds(v int64) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldUsageReplicaSeconds, v))
}

// ExpirationMinutes applies equality check predicate on the "expiration_minutes" field. It's identical to ExpirationMinutesEQ.
func ExpirationMinutes(v int64) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldExpirationMinutes, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Inference {
	return predicate.Inference(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Inference {
	return predicate.Inference(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Inference {
	return predicate.Inference(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Inference {
	return predicate.Inference(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Inference {
	return predicate.Inference(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Inference {
	return predicate.Inference(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Inference {
	return predicate.Inference(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.Inference {
	return predicate.Inference(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.Inference {
	return predicate.Inference(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Inference {
	return predicate.Inference(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Inference {
	return predicate.Inference(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Inference {
	return predicate.Inference(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Inference {
	return predicate.Inference(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Inference {
	return predicate.Inference(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Inference {
	return predicate.Inference(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Inference {
	return predicate.Inference(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.Inference {
	return predicate.Inference(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.Inference {
	return predicate.Inference(sql.FieldNotNull(FieldUpdatedAt))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.Inference {
	return predicate.Inference(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.Inference {
	return predicate.Inference(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.Inference {
	return predicate.Inference(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.Inference {
	return predicate.Inference(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.Inference {
	return predicate.Inference(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.Inference {
	return predicate.Inference(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.Inference {
	return predicate.Inference(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.Inference {
	return predicate.Inference(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.Inference {
	return predicate.Inference(sql.FieldNotNull(FieldDeletedAt))
}

// RemarkEQ applies the EQ predicate on the "remark" field.
func RemarkEQ(v string) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldRemark, v))
}

// RemarkNEQ applies the NEQ predicate on the "remark" field.
func RemarkNEQ(v string) predicate.Inference {
	return predicate.Inference(sql.FieldNEQ(FieldRemark, v))
}

// RemarkIn applies the In predicate on the "remark" field.
func RemarkIn(vs ...string) predicate.Inference {
	return predicate.Inference(sql.FieldIn(FieldRemark, vs...))
}

// RemarkNotIn applies the NotIn predicate on the "remark" field.
func RemarkNotIn(vs ...string) predicate.Inference {
	return predicate.Inference(sql.FieldNotIn(FieldRemark, vs...))
}

// RemarkGT applies the GT predicate on the "remark" field.
func RemarkGT(v string) predicate.Inference {
	return predicate.Inference(sql.FieldGT(FieldRemark, v))
}

// RemarkGTE applies the GTE predicate on the "remark" field.
func RemarkGTE(v string) predicate.Inference {
	return predicate.Inference(sql.FieldGTE(FieldRemark, v))
}

// RemarkLT applies the LT predicate on the "remark" field.
func RemarkLT(v string) predicate.Inference {
	return predicate.Inference(sql.FieldLT(FieldRemark, v))
}

// RemarkLTE applies the LTE predicate on the "remark" field.
func RemarkLTE(v string) predicate.Inference {
	return predicate.Inference(sql.FieldLTE(FieldRemark, v))
}

// RemarkContains applies the Contains predicate on the "remark" field.
func RemarkContains(v string) predicate.Inference {
	return predicate.Inference(sql.FieldContains(FieldRemark, v))
}

// RemarkHasPrefix applies the HasPrefix predicate on the "remark" field.
func RemarkHasPrefix(v string) predicate.Inference {
	return predicate.Inference(sql.FieldHasPrefix(FieldRemark, v))
}

// RemarkHasSuffix applies the HasSuffix predicate on the "remark" field.
func RemarkHasSuffix(v string) predicate.Inference {
	return predicate.Inference(sql.FieldHasSuffix(FieldRemark, v))
}

// RemarkIsNil applies the IsNil predicate on the "remark" field.
func RemarkIsNil() predicate.Inference {
	return predicate.Inference(sql.FieldIsNull(FieldRemark))
}

// RemarkNotNil applies the NotNil predicate on the "remark" field.
func RemarkNotNil() predicate.Inference {
	return predicate.Inference(sql.FieldNotNull(FieldRemark))
}

// RemarkEqualFold applies the EqualFold predicate on the "remark" field.
func RemarkEqualFold(v string) predicate.Inference {
	return predicate.Inference(sql.FieldEqualFold(FieldRemark, v))
}

// RemarkContainsFold applies the ContainsFold predicate on the "remark" field.
func RemarkContainsFold(v string) predicate.Inference {
	return predicate.Inference(sql.FieldContainsFold(FieldRemark, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Inference {
	return predicate.Inference(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Inference {
	return predicate.Inference(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Inference {
	return predicate.Inference(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Inference {
	return predicate.Inference(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Inference {
	return predicate.Inference(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Inference {
	return predicate.Inference(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Inference {
	return predicate.Inference(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Inference {
	return predicate.Inference(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Inference {
	return predicate.Inference(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Inference {
	return predicate.Inference(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Inference {
	return predicate.Inference(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Inference {
	return predicate.Inference(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Inference {
	return predicate.Inference(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Inference {
	return predicate.Inference(sql.FieldContainsFold(FieldDescription, v))
}

// TagsIsNil applies the IsNil predicate on the "tags" field.
func TagsIsNil() predicate.Inference {
	return predicate.Inference(sql.FieldIsNull(FieldTags))
}

// TagsNotNil applies the NotNil predicate on the "tags" field.
func TagsNotNil() predicate.Inference {
	return predicate.Inference(sql.FieldNotNull(FieldTags))
}

// IsEnabledEQ applies the EQ predicate on the "is_enabled" field.
func IsEnabledEQ(v bool) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldIsEnabled, v))
}

// IsEnabledNEQ applies the NEQ predicate on the "is_enabled" field.
func IsEnabledNEQ(v bool) predicate.Inference {
	return predicate.Inference(sql.FieldNEQ(FieldIsEnabled, v))
}

// IsEnabledIsNil applies the IsNil predicate on the "is_enabled" field.
func IsEnabledIsNil() predicate.Inference {
	return predicate.Inference(sql.FieldIsNull(FieldIsEnabled))
}

// IsEnabledNotNil applies the NotNil predicate on the "is_enabled" field.
func IsEnabledNotNil() predicate.Inference {
	return predicate.Inference(sql.FieldNotNull(FieldIsEnabled))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Inference {
	return predicate.Inference(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Inference {
	return predicate.Inference(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Inference {
	return predicate.Inference(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Inference {
	return predicate.Inference(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Inference {
	return predicate.Inference(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Inference {
	return predicate.Inference(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Inference {
	return predicate.Inference(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Inference {
	return predicate.Inference(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Inference {
	return predicate.Inference(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Inference {
	return predicate.Inference(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Inference {
	return predicate.Inference(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Inference {
	return predicate.Inference(sql.FieldContainsFold(FieldName, v))
}

// TenantNameEQ applies the EQ predicate on the "tenant_name" field.
func TenantNameEQ(v string) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldTenantName, v))
}

// TenantNameNEQ applies the NEQ predicate on the "tenant_name" field.
func TenantNameNEQ(v string) predicate.Inference {
	return predicate.Inference(sql.FieldNEQ(FieldTenantName, v))
}

// TenantNameIn applies the In predicate on the "tenant_name" field.
func TenantNameIn(vs ...string) predicate.Inference {
	return predicate.Inference(sql.FieldIn(FieldTenantName, vs...))
}

// TenantNameNotIn applies the NotIn predicate on the "tenant_name" field.
func TenantNameNotIn(vs ...string) predicate.Inference {
	return predicate.Inference(sql.FieldNotIn(FieldTenantName, vs...))
}

// TenantNameGT applies the GT predicate on the "tenant_name" field.
func TenantNameGT(v string) predicate.Inference {
	return predicate.Inference(sql.FieldGT(FieldTenantName, v))
}

// TenantNameGTE applies the GTE predicate on the "tenant_name" field.
func TenantNameGTE(v string) predicate.Inference {
	return predicate.Inference(sql.FieldGTE(FieldTenantName, v))
}

// TenantNameLT applies the LT predicate on the "tenant_name" field.
func TenantNameLT(v string) predicate.Inference {
	return predicate.Inference(sql.FieldLT(FieldTenantName, v))
}

// TenantNameLTE applies the LTE predicate on the "tenant_name" field.
func TenantNameLTE(v string) predicate.Inference {
	return predicate.Inference(sql.FieldLTE(FieldTenantName, v))
}

// TenantNameContains applies the Contains predicate on the "tenant_name" field.
func TenantNameContains(v string) predicate.Inference {
	return predicate.Inference(sql.FieldContains(FieldTenantName, v))
}

// TenantNameHasPrefix applies the HasPrefix predicate on the "tenant_name" field.
func TenantNameHasPrefix(v string) predicate.Inference {
	return predicate.Inference(sql.FieldHasPrefix(FieldTenantName, v))
}

// TenantNameHasSuffix applies the HasSuffix predicate on the "tenant_name" field.
func TenantNameHasSuffix(v string) predicate.Inference {
	return predicate.Inference(sql.FieldHasSuffix(FieldTenantName, v))
}

// TenantNameEqualFold applies the EqualFold predicate on the "tenant_name" field.
func TenantNameEqualFold(v string) predicate.Inference {
	return predicate.Inference(sql.FieldEqualFold(FieldTenantName, v))
}

// TenantNameContainsFold applies the ContainsFold predicate on the "tenant_name" field.
func TenantNameContainsFold(v string) predicate.Inference {
	return predicate.Inference(sql.FieldContainsFold(FieldTenantName, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Inference {
	return predicate.Inference(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Inference {
	return predicate.Inference(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Inference {
	return predicate.Inference(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusIsNil applies the IsNil predicate on the "status" field.
func StatusIsNil() predicate.Inference {
	return predicate.Inference(sql.FieldIsNull(FieldStatus))
}

// StatusNotNil applies the NotNil predicate on the "status" field.
func StatusNotNil() predicate.Inference {
	return predicate.Inference(sql.FieldNotNull(FieldStatus))
}

// ModelIDEQ applies the EQ predicate on the "model_id" field.
func ModelIDEQ(v uint64) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldModelID, v))
}

// ModelIDNEQ applies the NEQ predicate on the "model_id" field.
func ModelIDNEQ(v uint64) predicate.Inference {
	return predicate.Inference(sql.FieldNEQ(FieldModelID, v))
}

// ModelIDIn applies the In predicate on the "model_id" field.
func ModelIDIn(vs ...uint64) predicate.Inference {
	return predicate.Inference(sql.FieldIn(FieldModelID, vs...))
}

// ModelIDNotIn applies the NotIn predicate on the "model_id" field.
func ModelIDNotIn(vs ...uint64) predicate.Inference {
	return predicate.Inference(sql.FieldNotIn(FieldModelID, vs...))
}

// ModelIDGT applies the GT predicate on the "model_id" field.
func ModelIDGT(v uint64) predicate.Inference {
	return predicate.Inference(sql.FieldGT(FieldModelID, v))
}

// ModelIDGTE applies the GTE predicate on the "model_id" field.
func ModelIDGTE(v uint64) predicate.Inference {
	return predicate.Inference(sql.FieldGTE(FieldModelID, v))
}

// ModelIDLT applies the LT predicate on the "model_id" field.
func ModelIDLT(v uint64) predicate.Inference {
	return predicate.Inference(sql.FieldLT(FieldModelID, v))
}

// ModelIDLTE applies the LTE predicate on the "model_id" field.
func ModelIDLTE(v uint64) predicate.Inference {
	return predicate.Inference(sql.FieldLTE(FieldModelID, v))
}

// ModelIDIsNil applies the IsNil predicate on the "model_id" field.
func ModelIDIsNil() predicate.Inference {
	return predicate.Inference(sql.FieldIsNull(FieldModelID))
}

// ModelIDNotNil applies the NotNil predicate on the "model_id" field.
func ModelIDNotNil() predicate.Inference {
	return predicate.Inference(sql.FieldNotNull(FieldModelID))
}

// ModelNameEQ applies the EQ predicate on the "model_name" field.
func ModelNameEQ(v string) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldModelName, v))
}

// ModelNameNEQ applies the NEQ predicate on the "model_name" field.
func ModelNameNEQ(v string) predicate.Inference {
	return predicate.Inference(sql.FieldNEQ(FieldModelName, v))
}

// ModelNameIn applies the In predicate on the "model_name" field.
func ModelNameIn(vs ...string) predicate.Inference {
	return predicate.Inference(sql.FieldIn(FieldModelName, vs...))
}

// ModelNameNotIn applies the NotIn predicate on the "model_name" field.
func ModelNameNotIn(vs ...string) predicate.Inference {
	return predicate.Inference(sql.FieldNotIn(FieldModelName, vs...))
}

// ModelNameGT applies the GT predicate on the "model_name" field.
func ModelNameGT(v string) predicate.Inference {
	return predicate.Inference(sql.FieldGT(FieldModelName, v))
}

// ModelNameGTE applies the GTE predicate on the "model_name" field.
func ModelNameGTE(v string) predicate.Inference {
	return predicate.Inference(sql.FieldGTE(FieldModelName, v))
}

// ModelNameLT applies the LT predicate on the "model_name" field.
func ModelNameLT(v string) predicate.Inference {
	return predicate.Inference(sql.FieldLT(FieldModelName, v))
}

// ModelNameLTE applies the LTE predicate on the "model_name" field.
func ModelNameLTE(v string) predicate.Inference {
	return predicate.Inference(sql.FieldLTE(FieldModelName, v))
}

// ModelNameContains applies the Contains predicate on the "model_name" field.
func ModelNameContains(v string) predicate.Inference {
	return predicate.Inference(sql.FieldContains(FieldModelName, v))
}

// ModelNameHasPrefix applies the HasPrefix predicate on the "model_name" field.
func ModelNameHasPrefix(v string) predicate.Inference {
	return predicate.Inference(sql.FieldHasPrefix(FieldModelName, v))
}

// ModelNameHasSuffix applies the HasSuffix predicate on the "model_name" field.
func ModelNameHasSuffix(v string) predicate.Inference {
	return predicate.Inference(sql.FieldHasSuffix(FieldModelName, v))
}

// ModelNameIsNil applies the IsNil predicate on the "model_name" field.
func ModelNameIsNil() predicate.Inference {
	return predicate.Inference(sql.FieldIsNull(FieldModelName))
}

// ModelNameNotNil applies the NotNil predicate on the "model_name" field.
func ModelNameNotNil() predicate.Inference {
	return predicate.Inference(sql.FieldNotNull(FieldModelName))
}

// ModelNameEqualFold applies the EqualFold predicate on the "model_name" field.
func ModelNameEqualFold(v string) predicate.Inference {
	return predicate.Inference(sql.FieldEqualFold(FieldModelName, v))
}

// ModelNameContainsFold applies the ContainsFold predicate on the "model_name" field.
func ModelNameContainsFold(v string) predicate.Inference {
	return predicate.Inference(sql.FieldContainsFold(FieldModelName, v))
}

// ImageEQ applies the EQ predicate on the "image" field.
func ImageEQ(v string) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldImage, v))
}

// ImageNEQ applies the NEQ predicate on the "image" field.
func ImageNEQ(v string) predicate.Inference {
	return predicate.Inference(sql.FieldNEQ(FieldImage, v))
}

// ImageIn applies the In predicate on the "image" field.
func ImageIn(vs ...string) predicate.Inference {
	return predicate.Inference(sql.FieldIn(FieldImage, vs...))
}

// ImageNotIn applies the NotIn predicate on the "image" field.
func ImageNotIn(vs ...string) predicate.Inference {
	return predicate.Inference(sql.FieldNotIn(FieldImage, vs...))
}

// ImageGT applies the GT predicate on the "image" field.
func ImageGT(v string) predicate.Inference {
	return predicate.Inference(sql.FieldGT(FieldImage, v))
}

// ImageGTE applies the GTE predicate on the "image" field.
func ImageGTE(v string) predicate.Inference {
	return predicate.Inference(sql.FieldGTE(FieldImage, v))
}

// ImageLT applies the LT predicate on the "image" field.
func ImageLT(v string) predicate.Inference {
	return predicate.Inference(sql.FieldLT(FieldImage, v))
}

// ImageLTE applies the LTE predicate on the "image" field.
func ImageLTE(v string) predicate.Inference {
	return predicate.Inference(sql.FieldLTE(FieldImage, v))
}

// ImageContains applies the Contains predicate on the "image" field.
func ImageContains(v string) predicate.Inference {
	return predicate.Inference(sql.FieldContains(FieldImage, v))
}

// ImageHasPrefix applies the HasPrefix predicate on the "image" field.
func ImageHasPrefix(v string) predicate.Inference {
	return predicate.Inference(sql.FieldHasPrefix(FieldImage, v))
}

// ImageHasSuffix applies the HasSuffix predicate on the "image" field.
func ImageHasSuffix(v string) predicate.Inference {
	return predicate.Inference(sql.FieldHasSuffix(FieldImage, v))
}

// ImageIsNil applies the IsNil predicate on the "image" field.
func ImageIsNil() predicate.Inference {
	return predicate.Inference(sql.FieldIsNull(FieldImage))
}

// ImageNotNil applies the NotNil predicate on the "image" field.
func ImageNotNil() predicate.Inference {
	return predicate.Inference(sql.FieldNotNull(FieldImage))
}

// ImageEqualFold applies the EqualFold predicate on the "image" field.
func ImageEqualFold(v string) predicate.Inference {
	return predicate.Inference(sql.FieldEqualFold(FieldImage, v))
}

// ImageContainsFold applies the ContainsFold predicate on the "image" field.
func ImageContainsFold(v string) predicate.Inference {
	return predicate.Inference(sql.FieldContainsFold(FieldImage, v))
}

// ReplicasEQ applies the EQ predicate on the "replicas" field.
func ReplicasEQ(v int32) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldReplicas, v))
}

// ReplicasNEQ applies the NEQ predicate on the "replicas" field.
func ReplicasNEQ(v int32) predicate.Inference {
	return predicate.Inference(sql.FieldNEQ(FieldReplicas, v))
}

// ReplicasIn applies the In predicate on the "replicas" field.
func ReplicasIn(vs ...int32) predicate.Inference {
	return predicate.Inference(sql.FieldIn(FieldReplicas, vs...))
}

// ReplicasNotIn applies the NotIn predicate on the "replicas" field.
func ReplicasNotIn(vs ...int32) predicate.Inference {
	return predicate.Inference(sql.FieldNotIn(FieldReplicas, vs...))
}

// ReplicasGT applies the GT predicate on the "replicas" field.
func ReplicasGT(v int32) predicate.Inference {
	return predicate.Inference(sql.FieldGT(FieldReplicas, v))
}

// ReplicasGTE applies the GTE predicate on the "replicas" field.
func ReplicasGTE(v int32) predicate.Inference {
	return predicate.Inference(sql.FieldGTE(FieldReplicas, v))
}

// ReplicasLT applies the LT predicate on the "replicas" field.
func ReplicasLT(v int32) predicate.Inference {
	return predicate.Inference(sql.FieldLT(FieldReplicas, v))
}

// ReplicasLTE applies the LTE predicate on the "replicas" field.
func ReplicasLTE(v int32) predicate.Inference {
	return predicate.Inference(sql.FieldLTE(FieldReplicas, v))
}

// MinReplicasEQ applies the EQ predicate on the "min_replicas" field.
func MinReplicasEQ(v int32) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldMinReplicas, v))
}

// MinReplicasNEQ applies the NEQ predicate on the "min_replicas" field.
func MinReplicasNEQ(v int32) predicate.Inference {
	return predicate.Inference(sql.FieldNEQ(FieldMinReplicas, v))
}

// MinReplicasIn applies the In predicate on the "min_replicas" field.
func MinReplicasIn(vs ...int32) predicate.Inference {
	return predicate.Inference(sql.FieldIn(FieldMinReplicas, vs...))
}

// MinReplicasNotIn applies the NotIn predicate on the "min_replicas" field.
func MinReplicasNotIn(vs ...int32) predicate.Inference {
	return predicate.Inference(sql.FieldNotIn(FieldMinReplicas, vs...))
}

// MinReplicasGT applies the GT predicate on the "min_replicas" field.
func MinReplicasGT(v int32) predicate.Inference {
	return predicate.Inference(sql.FieldGT(FieldMinReplicas, v))
}

// MinReplicasGTE applies the GTE predicate on the "min_replicas" field.
func MinReplicasGTE(v int32) predicate.Inference {
	return predicate.Inference(sql.FieldGTE(FieldMinReplicas, v))
}

// MinReplicasLT applies the LT predicate on the "min_replicas" field.
func MinReplicasLT(v int32) predicate.Inference {
	return predicate.Inference(sql.FieldLT(FieldMinReplicas, v))
}

// MinReplicasLTE applies the LTE predicate on the "min_replicas" field.
func MinReplicasLTE(v int32) predicate.Inference {
	return predicate.Inference(sql.FieldLTE(FieldMinReplicas, v))
}

// MinReplicasIsNil applies the IsNil predicate on the "min_replicas" field.
func MinReplicasIsNil() predicate.Inference {
	return predicate.Inference(sql.FieldIsNull(FieldMinReplicas))
}

// MinReplicasNotNil applies the NotNil predicate on the "min_replicas" field.
func MinReplicasNotNil() predicate.Inference {
	return predicate.Inference(sql.FieldNotNull(FieldMinReplicas))
}

// MaxReplicasEQ applies the EQ predicate on the "max_replicas" field.
func MaxReplicasEQ(v int32) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldMaxReplicas, v))
}

// MaxReplicasNEQ applies the NEQ predicate on the "max_replicas" field.
func MaxReplicasNEQ(v int32) predicate.Inference {
	return predicate.Inference(sql.FieldNEQ(FieldMaxReplicas, v))
}

// MaxReplicasIn applies the In predicate on the "max_replicas" field.
func MaxReplicasIn(vs ...int32) predicate.Inference {
	return predicate.Inference(sql.FieldIn(FieldMaxReplicas, vs...))
}

// MaxReplicasNotIn applies the NotIn predicate on the "max_replicas" field.
func MaxReplicasNotIn(vs ...int32) predicate.Inference {
	return predicate.Inference(sql.FieldNotIn(FieldMaxReplicas, vs...))
}

// MaxReplicasGT applies the GT predicate on the "max_replicas" field.
func MaxReplicasGT(v int32) predicate.Inference {
	return predicate.Inference(sql.FieldGT(FieldMaxReplicas, v))
}

// MaxReplicasGTE applies the GTE predicate on the "max_replicas" field.
func MaxReplicasGTE(v int32) predicate.Inference {
	return predicate.Inference(sql.FieldGTE(FieldMaxReplicas, v))
}

// MaxReplicasLT applies the LT predicate on the "max_replicas" field.
func MaxReplicasLT(v int32) predicate.Inference {
	return predicate.Inference(sql.FieldLT(FieldMaxReplicas, v))
}

// MaxReplicasLTE applies the LTE predicate on the "max_replicas" field.
func MaxReplicasLTE(v int32) predicate.Inference {
	return predicate.Inference(sql.FieldLTE(FieldMaxReplicas, v))
}

// MaxReplicasIsNil applies the IsNil predicate on the "max_replicas" field.
func MaxReplicasIsNil() predicate.Inference {
	return predicate.Inference(sql.FieldIsNull(FieldMaxReplicas))
}

// MaxReplicasNotNil applies the NotNil predicate on the "max_replicas" field.
func MaxReplicasNotNil() predicate.Inference {
	return predicate.Inference(sql.FieldNotNull(FieldMaxReplicas))
}

// PortEQ applies the EQ predicate on the "port" field.
func PortEQ(v int32) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldPort, v))
}

// PortNEQ applies the NEQ predicate on the "port" field.
func PortNEQ(v int32) predicate.Inference {
	return predicate.Inference(sql.FieldNEQ(FieldPort, v))
}

// PortIn applies the In predicate on the "port" field.
func PortIn(vs ...int32) predicate.Inference {
	return predicate.Inference(sql.FieldIn(FieldPort, vs...))
}

// PortNotIn applies the NotIn predicate on the "port" field.
func PortNotIn(vs ...int32) predicate.Inference {
	return predicate.Inference(sql.FieldNotIn(FieldPort, vs...))
}

// PortGT applies the GT predicate on the "port" field.
func PortGT(v int32) predicate.Inference {
	return predicate.Inference(sql.FieldGT(FieldPort, v))
}

// PortGTE applies the GTE predicate on the "port" field.
func PortGTE(v int32) predicate.Inference {
	return predicate.Inference(sql.FieldGTE(FieldPort, v))
}

// PortLT applies the LT predicate on the "port" field.
func PortLT(v int32) predicate.Inference {
	return predicate.Inference(sql.FieldLT(FieldPort, v))
}

// PortLTE applies the LTE predicate on the "port" field.
func PortLTE(v int32) predicate.Inference {
	return predicate.Inference(sql.FieldLTE(FieldPort, v))
}

// CommandIsNil applies the IsNil predicate on the "command" field.
func CommandIsNil() predicate.Inference {
	return predicate.Inference(sql.FieldIsNull(FieldCommand))
}

// CommandNotNil applies the NotNil predicate on the "command" field.
func CommandNotNil() predicate.Inference {
	return predicate.Inference(sql.FieldNotNull(FieldCommand))
}

// ArgsIsNil applies the IsNil predicate on the "args" field.
func ArgsIsNil() predicate.Inference {
	return predicate.Inference(sql.FieldIsNull(FieldArgs))
}

// ArgsNotNil applies the NotNil predicate on the "args" field.
func ArgsNotNil() predicate.Inference {
	return predicate.Inference(sql.FieldNotNull(FieldArgs))
}

// EnvIsNil applies the IsNil predicate on the "env" field.
func EnvIsNil() predicate.Inference {
	return predicate.Inference(sql.FieldIsNull(FieldEnv))
}

// EnvNotNil applies the NotNil predicate on the "env" field.
func EnvNotNil() predicate.Inference {
	return predicate.Inference(sql.FieldNotNull(FieldEnv))
}

// DeploymentNameEQ applies the EQ predicate on the "deployment_name" field.
func DeploymentNameEQ(v string) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldDeploymentName, v))
}

// DeploymentNameNEQ applies the NEQ predicate on the "deployment_name" field.
func DeploymentNameNEQ(v string) predicate.Inference {
	return predicate.Inference(sql.FieldNEQ(FieldDeploymentName, v))
}

// DeploymentNameIn applies the In predicate on the "deployment_name" field.
func DeploymentNameIn(vs ...string) predicate.Inference {
	return predicate.Inference(sql.FieldIn(FieldDeploymentName, vs...))
}

// DeploymentNameNotIn applies the NotIn predicate on the "deployment_name" field.
func DeploymentNameNotIn(vs ...string) predicate.Inference {
	return predicate.Inference(sql.FieldNotIn(FieldDeploymentName, vs...))
}

// DeploymentNameGT applies the GT predicate on the "deployment_name" field.
func DeploymentNameGT(v string) predicate.Inference {
	return predicate.Inference(sql.FieldGT(FieldDeploymentName, v))
}

// DeploymentNameGTE applies the GTE predicate on the "deployment_name" field.
func DeploymentNameGTE(v string) predicate.Inference {
	return predicate.Inference(sql.FieldGTE(FieldDeploymentName, v))
}

// DeploymentNameLT applies the LT predicate on the "deployment_name" field.
func DeploymentNameLT(v string) predicate.Inference {
	return predicate.Inference(sql.FieldLT(FieldDeploymentName, v))
}

// DeploymentNameLTE applies the LTE predicate on the "deployment_name" field.
func DeploymentNameLTE(v string) predicate.Inference {
	return predicate.Inference(sql.FieldLTE(FieldDeploymentName, v))
}

// DeploymentNameContains applies the Contains predicate on the "deployment_name" field.
func DeploymentNameContains(v string) predicate.Inference {
	return predicate.Inference(sql.FieldContains(FieldDeploymentName, v))
}

// DeploymentNameHasPrefix applies the HasPrefix predicate on the "deployment_name" field.
func DeploymentNameHasPrefix(v string) predicate.Inference {
	return predicate.Inference(sql.FieldHasPrefix(FieldDeploymentName, v))
}

// DeploymentNameHasSuffix applies the HasSuffix predicate on the "deployment_name" field.
func DeploymentNameHasSuffix(v string) predicate.Inference {
	return predicate.Inference(sql.FieldHasSuffix(FieldDeploymentName, v))
}

// DeploymentNameEqualFold applies the EqualFold predicate on the "deployment_name" field.
func DeploymentNameEqualFold(v string) predicate.Inference {
	return predicate.Inference(sql.FieldEqualFold(FieldDeploymentName, v))
}

// DeploymentNameContainsFold applies the ContainsFold predicate on the "deployment_name" field.
func DeploymentNameContainsFold(v string) predicate.Inference {
	return predicate.Inference(sql.FieldContainsFold(FieldDeploymentName, v))
}

// ServiceNameEQ applies the EQ predicate on the "service_name" field.
func ServiceNameEQ(v string) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldServiceName, v))
}

// ServiceNameNEQ applies the NEQ predicate on the "service_name" field.
func ServiceNameNEQ(v string) predicate.Inference {
	return predicate.Inference(sql.FieldNEQ(FieldServiceName, v))
}

// ServiceNameIn applies the In predicate on the "service_name" field.
func ServiceNameIn(vs ...string) predicate.Inference {
	return predicate.Inference(sql.FieldIn(FieldServiceName, vs...))
}

// ServiceNameNotIn applies the NotIn predicate on the "service_name" field.
func ServiceNameNotIn(vs ...string) predicate.Inference {
	return predicate.Inference(sql.FieldNotIn(FieldServiceName, vs...))
}

// ServiceNameGT applies the GT predicate on the "service_name" field.
func ServiceNameGT(v string) predicate.Inference {
	return predicate.Inference(sql.FieldGT(FieldServiceName, v))
}

// ServiceNameGTE applies the GTE predicate on the "service_name" field.
func ServiceNameGTE(v string) predicate.Inference {
	return predicate.Inference(sql.FieldGTE(FieldServiceName, v))
}

// ServiceNameLT applies the LT predicate on the "service_name" field.
func ServiceNameLT(v string) predicate.Inference {
	return predicate.Inference(sql.FieldLT(FieldServiceName, v))
}

// ServiceNameLTE applies the LTE predicate on the "service_name" field.
func ServiceNameLTE(v string) predicate.Inference {
	return predicate.Inference(sql.FieldLTE(FieldServiceName, v))
}

// ServiceNameContains applies the Contains predicate on the "service_name" field.
func ServiceNameContains(v string) predicate.Inference {
	return predicate.Inference(sql.FieldContains(FieldServiceName, v))
}

// ServiceNameHasPrefix applies the HasPrefix predicate on the "service_name" field.
func ServiceNameHasPrefix(v string) predicate.Inference {
	return predicate.Inference(sql.FieldHasPrefix(FieldServiceName, v))
}

// ServiceNameHasSuffix applies the HasSuffix predicate on the "service_name" field.
func ServiceNameHasSuffix(v string) predicate.Inference {
	return predicate.Inference(sql.FieldHasSuffix(FieldServiceName, v))
}

// ServiceNameEqualFold applies the EqualFold predicate on the "service_name" field.
func ServiceNameEqualFold(v string) predicate.Inference {
	return predicate.Inference(sql.FieldEqualFold(FieldServiceName, v))
}

// ServiceNameContainsFold applies the ContainsFold predicate on the "service_name" field.
func ServiceNameContainsFold(v string) predicate.Inference {
	return predicate.Inference(sql.FieldContainsFold(FieldServiceName, v))
}

// URLEQ applies the EQ predicate on the "url" field.
func URLEQ(v string) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldURL, v))
}

// URLNEQ applies the NEQ predicate on the "url" field.
func URLNEQ(v string) predicate.Inference {
	return predicate.Inference(sql.FieldNEQ(FieldURL, v))
}

// URLIn applies the In predicate on the "url" field.
func URLIn(vs ...string) predicate.Inference {
	return predicate.Inference(sql.FieldIn(FieldURL, vs...))
}

// URLNotIn applies the NotIn predicate on the "url" field.
func URLNotIn(vs ...string) predicate.Inference {
	return predicate.Inference(sql.FieldNotIn(FieldURL, vs...))
}

// URLGT applies the GT predicate on the "url" field.
func URLGT(v string) predicate.Inference {
	return predicate.Inference(sql.FieldGT(FieldURL, v))
}

// URLGTE applies the GTE predicate on the "url" field.
func URLGTE(v string) predicate.Inference {
	return predicate.Inference(sql.FieldGTE(FieldURL, v))
}

// URLLT applies the LT predicate on the "url" field.
func URLLT(v string) predicate.Inference {
	return predicate.Inference(sql.FieldLT(FieldURL, v))
}

// URLLTE applies the LTE predicate on the "url" field.
func URLLTE(v string) predicate.Inference {
	return predicate.Inference(sql.FieldLTE(FieldURL, v))
}

// URLContains applies the Contains predicate on the "url" field.
func URLContains(v string) predicate.Inference {
	return predicate.Inference(sql.FieldContains(FieldURL, v))
}

// URLHasPrefix applies the HasPrefix predicate on the "url" field.
func URLHasPrefix(v string) predicate.Inference {
	return predicate.Inference(sql.FieldHasPrefix(FieldURL, v))
}

// URLHasSuffix applies the HasSuffix predicate on the "url" field.
func URLHasSuffix(v string) predicate.Inference {
	return predicate.Inference(sql.FieldHasSuffix(FieldURL, v))
}

// URLIsNil applies the IsNil predicate on the "url" field.
func URLIsNil() predicate.Inference {
	return predicate.Inference(sql.FieldIsNull(FieldURL))
}

// URLNotNil applies the NotNil predicate on the "url" field.
func URLNotNil() predicate.Inference {
	return predicate.Inference(sql.FieldNotNull(FieldURL))
}

// URLEqualFold applies the EqualFold predicate on the "url" field.
func URLEqualFold(v string) predicate.Inference {
	return predicate.Inference(sql.FieldEqualFold(FieldURL, v))
}

// URLContainsFold applies the ContainsFold predicate on the "url" field.
func URLContainsFold(v string) predicate.Inference {
	return predicate.Inference(sql.FieldContainsFold(FieldURL, v))
}

// AuthTokenEQ applies the EQ predicate on the "auth_token" field.
func AuthTokenEQ(v string) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldAuthToken, v))
}

// AuthTokenNEQ applies the NEQ predicate on the "auth_token" field.
func AuthTokenNEQ(v string) predicate.Inference {
	return predicate.Inference(sql.FieldNEQ(FieldAuthToken, v))
}

// AuthTokenIn applies the In predicate on the "auth_token" field.
func AuthTokenIn(vs ...string) predicate.Inference {
	return predicate.Inference(sql.FieldIn(FieldAuthToken, vs...))
}

// AuthTokenNotIn applies the NotIn predicate on the "auth_token" field.
func AuthTokenNotIn(vs ...string) predicate.Inference {
	return predicate.Inference(sql.FieldNotIn(FieldAuthToken, vs...))
}

// AuthTokenGT applies the GT predicate on the "auth_token" field.
func AuthTokenGT(v string) predicate.Inference {
	return predicate.Inference(sql.FieldGT(FieldAuthToken, v))
}

// AuthTokenGTE applies the GTE predicate on the "auth_token" field.
func AuthTokenGTE(v string) predicate.Inference {
	return predicate.Inference(sql.FieldGTE(FieldAuthToken, v))
}

// AuthTokenLT applies the LT predicate on the "auth_token" field.
func AuthTokenLT(v string) predicate.Inference {
	return predicate.Inference(sql.FieldLT(FieldAuthToken, v))
}

// AuthTokenLTE applies the LTE predicate on the "auth_token" field.
func AuthTokenLTE(v string) predicate.Inference {
	return predicate.Inference(sql.FieldLTE(FieldAuthToken, v))
}

// AuthTokenContains applies the Contains predicate on the "auth_token" field.
func AuthTokenContains(v string) predicate.Inference {
	return predicate.Inference(sql.FieldContains(FieldAuthToken, v))
}

// AuthTokenHasPrefix applies the HasPrefix predicate on the "auth_token" field.
func AuthTokenHasPrefix(v string) predicate.Inference {
	return predicate.Inference(sql.FieldHasPrefix(FieldAuthToken, v))
}

// AuthTokenHasSuffix applies the HasSuffix predicate on the "auth_token" field.
func AuthTokenHasSuffix(v string) predicate.Inference {
	return predicate.Inference(sql.FieldHasSuffix(FieldAuthToken, v))
}

// AuthTokenIsNil applies the IsNil predicate on the "auth_token" field.
func AuthTokenIsNil() predicate.Inference {
	return predicate.Inference(sql.FieldIsNull(FieldAuthToken))
}

// AuthTokenNotNil applies the NotNil predicate on the "auth_token" field.
func AuthTokenNotNil() predicate.Inference {
	return predicate.Inference(sql.FieldNotNull(FieldAuthToken))
}

// AuthTokenEqualFold applies the EqualFold predicate on the "auth_token" field.
func AuthTokenEqualFold(v string) predicate.Inference {
	return predicate.Inference(sql.FieldEqualFold(FieldAuthToken, v))
}

// AuthTokenContainsFold applies the ContainsFold predicate on the "auth_token" field.
func AuthTokenContainsFold(v string) predicate.Inference {
	return predicate.Inference(sql.FieldContainsFold(FieldAuthToken, v))
}

// QuotaIsNil applies the IsNil predicate on the "quota" field.
func QuotaIsNil() predicate.Inference {
	return predicate.Inference(sql.FieldIsNull(FieldQuota))
}

// QuotaNotNil applies the NotNil predicate on the "quota" field.
func QuotaNotNil() predicate.Inference {
	return predicate.Inference(sql.FieldNotNull(FieldQuota))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.Inference {
	return predicate.Inference(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.Inference {
	return predicate.Inference(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.Inference {
	return predicate.Inference(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.Inference {
	return predicate.Inference(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.Inference {
	return predicate.Inference(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.Inference {
	return predicate.Inference(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.Inference {
	return predicate.Inference(sql.FieldLTE(FieldStartedAt, v))
}

// StartedAtIsNil applies the IsNil predicate on the "started_at" field.
func StartedAtIsNil() predicate.Inference {
	return predicate.Inference(sql.FieldIsNull(FieldStartedAt))
}

// StartedAtNotNil applies the NotNil predicate on the "started_at" field.
func StartedAtNotNil() predicate.Inference {
	return predicate.Inference(sql.FieldNotNull(FieldStartedAt))
}

// FinishedAtEQ applies the EQ predicate on the "finished_at" field.
func FinishedAtEQ(v time.Time) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldFinishedAt, v))
}

// FinishedAtNEQ applies the NEQ predicate on the "finished_at" field.
func FinishedAtNEQ(v time.Time) predicate.Inference {
	return predicate.Inference(sql.FieldNEQ(FieldFinishedAt, v))
}

// FinishedAtIn applies the In predicate on the "finished_at" field.
func FinishedAtIn(vs ...time.Time) predicate.Inference {
	return predicate.Inference(sql.FieldIn(FieldFinishedAt, vs...))
}

// FinishedAtNotIn applies the NotIn predicate on the "finished_at" field.
func FinishedAtNotIn(vs ...time.Time) predicate.Inference {
	return predicate.Inference(sql.FieldNotIn(FieldFinishedAt, vs...))
}

// FinishedAtGT applies the GT predicate on the "finished_at" field.
func FinishedAtGT(v time.Time) predicate.Inference {
	return predicate.Inference(sql.FieldGT(FieldFinishedAt, v))
}

// FinishedAtGTE applies the GTE predicate on the "finished_at" field.
func FinishedAtGTE(v time.Time) predicate.Inference {
	return predicate.Inference(sql.FieldGTE(FieldFinishedAt, v))
}

// FinishedAtLT applies the LT predicate on the "finished_at" field.
func FinishedAtLT(v time.Time) predicate.Inference {
	return predicate.Inference(sql.FieldLT(FieldFinishedAt, v))
}

// FinishedAtLTE applies the LTE predicate on the "finished_at" field.
func FinishedAtLTE(v time.Time) predicate.Inference {
	return predicate.Inference(sql.FieldLTE(FieldFinishedAt, v))
}

// FinishedAtIsNil applies the IsNil predicate on the "finished_at" field.
func FinishedAtIsNil() predicate.Inference {
	return predicate.Inference(sql.FieldIsNull(FieldFinishedAt))
}

// FinishedAtNotNil applies the NotNil predicate on the "finished_at" field.
func FinishedAtNotNil() predicate.Inference {
	return predicate.Inference(sql.FieldNotNull(FieldFinishedAt))
}

// LastActivityTimeEQ applies the EQ predicate on the "last_activity_time" field.
func LastActivityTimeEQ(v time.Time) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldLastActivityTime, v))
}

// LastActivityTimeNEQ applies the NEQ predicate on the "last_activity_time" field.
func LastActivityTimeNEQ(v time.Time) predicate.Inference {
	return predicate.Inference(sql.FieldNEQ(FieldLastActivityTime, v))
}

// LastActivityTimeIn applies the In predicate on the "last_activity_time" field.
func LastActivityTimeIn(vs ...time.Time) predicate.Inference {
	return predicate.Inference(sql.FieldIn(FieldLastActivityTime, vs...))
}

// LastActivityTimeNotIn applies the NotIn predicate on the "last_activity_time" field.
func LastActivityTimeNotIn(vs ...time.Time) predicate.Inference {
	return predicate.Inference(sql.FieldNotIn(FieldLastActivityTime, vs...))
}

// LastActivityTimeGT applies the GT predicate on the "last_activity_time" field.
func LastActivityTimeGT(v time.Time) predicate.Inference {
	return predicate.Inference(sql.FieldGT(FieldLastActivityTime, v))
}

// LastActivityTimeGTE applies the GTE predicate on the "last_activity_time" field.
func LastActivityTimeGTE(v time.Time) predicate.Inference {
	return predicate.Inference(sql.FieldGTE(FieldLastActivityTime, v))
}

// LastActivityTimeLT applies the LT predicate on the "last_activity_time" field.
func LastActivityTimeLT(v time.Time) predicate.Inference {
	return predicate.Inference(sql.FieldLT(FieldLastActivityTime, v))
}

// LastActivityTimeLTE applies the LTE predicate on the "last_activity_time" field.
func LastActivityTimeLTE(v time.Time) predicate.Inference {
	return predicate.Inference(sql.FieldLTE(FieldLastActivityTime, v))
}

// LastActivityTimeIsNil applies the IsNil predicate on the "last_activity_time" field.
func LastActivityTimeIsNil() predicate.Inference {
	return predicate.Inference(sql.FieldIsNull(FieldLastActivityTime))
}

// LastActivityTimeNotNil applies the NotNil predicate on the "last_activity_time" field.
func LastActivityTimeNotNil() predicate.Inference {
	return predicate.Inference(sql.FieldNotNull(FieldLastActivityTime))
}

// BillingDurationSecEQ applies the EQ predicate on the "billing_duration_sec" field.
func BillingDurationSecEQ(v int64) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldBillingDurationSec, v))
}

// BillingDurationSecNEQ applies the NEQ predicate on the "billing_duration_sec" field.
func BillingDurationSecNEQ(v int64) predicate.Inference {
	return predicate.Inference(sql.FieldNEQ(FieldBillingDurationSec, v))
}

// BillingDurationSecIn applies the In predicate on the "billing_duration_sec" field.
func BillingDurationSecIn(vs ...int64) predicate.Inference {
	return predicate.Inference(sql.FieldIn(FieldBillingDurationSec, vs...))
}

// BillingDurationSecNotIn applies the NotIn predicate on the "billing_duration_sec" field.
func BillingDurationSecNotIn(vs ...int64) predicate.Inference {
	return predicate.Inference(sql.FieldNotIn(FieldBillingDurationSec, vs...))
}

// BillingDurationSecGT applies the GT predicate on the "billing_duration_sec" field.
func BillingDurationSecGT(v int64) predicate.Inference {
	return predicate.Inference(sql.FieldGT(FieldBillingDurationSec, v))
}

// BillingDurationSecGTE applies the GTE predicate on the "billing_duration_sec" field.
func BillingDurationSecGTE(v int64) predicate.Inference {
	return predicate.Inference(sql.FieldGTE(FieldBillingDurationSec, v))
}

// BillingDurationSecLT applies the LT predicate on the "billing_duration_sec" field.
func BillingDurationSecLT(v int64) predicate.Inference {
	return predicate.Inference(sql.FieldLT(FieldBillingDurationSec, v))
}

// BillingDurationSecLTE applies the LTE predicate on the "billing_duration_sec" field.
func BillingDurationSecLTE(v int64) predicate.Inference {
	return predicate.Inference(sql.FieldLTE(FieldBillingDurationSec, v))
}

// UsageCPUSecondsEQ applies the EQ predicate on the "usage_cpu_seconds" field.
func UsageCPUSecondsEQ(v int64) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldUsageCPUSeconds, v))
}

// UsageCPUSecondsNEQ applies the NEQ predicate on the "usage_cpu_seconds" field.
func UsageCPUSecondsNEQ(v int64) predicate.Inference {
	return predicate.Inference(sql.FieldNEQ(FieldUsageCPUSeconds, v))
}

// UsageCPUSecondsIn applies the In predicate on the "usage_cpu_seconds" field.
func UsageCPUSecondsIn(vs ...int64) predicate.Inference {
	return predicate.Inference(sql.FieldIn(FieldUsageCPUSeconds, vs...))
}

// UsageCPUSecondsNotIn applies the NotIn predicate on the "usage_cpu_seconds" field.
func UsageCPUSecondsNotIn(vs ...int64) predicate.Inference {
	return predicate.Inference(sql.FieldNotIn(FieldUsageCPUSeconds, vs...))
}

// UsageCPUSecondsGT applies the GT predicate on the "usage_cpu_seconds" field.
func UsageCPUSecondsGT(v int64) predicate.Inference {
	return predicate.Inference(sql.FieldGT(FieldUsageCPUSeconds, v))
}

// UsageCPUSecondsGTE applies the GTE predicate on the "usage_cpu_seconds" field.
func UsageCPUSecondsGTE(v int64) predicate.Inference {
	return predicate.Inference(sql.FieldGTE(FieldUsageCPUSeconds, v))
}

// UsageCPUSecondsLT applies the LT predicate on the "usage_cpu_seconds" field.
func UsageCPUSecondsLT(v int64) predicate.Inference {
	return predicate.Inference(sql.FieldLT(FieldUsageCPUSeconds, v))
}

// UsageCPUSecondsLTE applies the LTE predicate on the "usage_cpu_seconds" field.
func UsageCPUSecondsLTE(v int64) predicate.Inference {
	return predicate.Inference(sql.FieldLTE(FieldUsageCPUSeconds, v))
}

// UsageGpuSecondsEQ applies the EQ predicate on the "usage_gpu_seconds" field.
func UsageGpuSecondsEQ(v int64) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldUsageGpuSeconds, v))
}

// UsageGpuSecondsNEQ applies the NEQ predicate on the "usage_gpu_seconds" field.
func UsageGpuSecondsNEQ(v int64) predicate.Inference {
	return predicate.Inference(sql.FieldNEQ(FieldUsageGpuSeconds, v))
}

// UsageGpuSecondsIn applies the In predicate on the "usage_gpu_seconds" field.
func UsageGpuSecondsIn(vs ...int64) predicate.Inference {
	return predicate.Inference(sql.FieldIn(FieldUsageGpuSeconds, vs...))
}

// UsageGpuSecondsNotIn applies the NotIn predicate on the "usage_gpu_seconds" field.
func UsageGpuSecondsNotIn(vs ...int64) predicate.Inference {
	return predicate.Inference(sql.FieldNotIn(FieldUsageGpuSeconds, vs...))
}

// UsageGpuSecondsGT applies the GT predicate on the "usage_gpu_seconds" field.
func UsageGpuSecondsGT(v int64) predicate.Inference {
	return predicate.Inference(sql.FieldGT(FieldUsageGpuSeconds, v))
}

// UsageGpuSecondsGTE applies the GTE predicate on the "usage_gpu_seconds" field.
func UsageGpuSecondsGTE(v int64) predicate.Inference {
	return predicate.Inference(sql.FieldGTE(FieldUsageGpuSeconds, v))
}

// UsageGpuSecondsLT applies the LT predicate on the "usage_gpu_seconds" field.
func UsageGpuSecondsLT(v int64) predicate.Inference {
	return predicate.Inference(sql.FieldLT(FieldUsageGpuSeconds, v))
}

// UsageGpuSecondsLTE applies the LTE predicate on the "usage_gpu_seconds" field.
func UsageGpuSecondsLTE(v int64) predicate.Inference {
	return predicate.Inference(sql.FieldLTE(FieldUsageGpuSeconds, v))
}

// UsageReplicaSecondsEQ applies the EQ predicate on the "usage_replica_seconds" field.
func UsageReplicaSecondsEQ(v int64) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldUsageReplicaSeconds, v))
}

// UsageReplicaSecondsNEQ applies the NEQ predicate on the "usage_replica_seconds" field.
func UsageReplicaSecondsNEQ(v int64) predicate.Inference {
	return predicate.Inference(sql.FieldNEQ(FieldUsageReplicaSeconds, v))
}

// UsageReplicaSecondsIn applies the In predicate on the "usage_replica_seconds" field.
func UsageReplicaSecondsIn(vs ...int64) predicate.Inference {
	return predicate.Inference(sql.FieldIn(FieldUsageReplicaSeconds, vs...))
}

// UsageReplicaSecondsNotIn applies the NotIn predicate on the "usage_replica_seconds" field.
func UsageReplicaSecondsNotIn(vs ...int64) predicate.Inference {
	return predicate.Inference(sql.FieldNotIn(FieldUsageReplicaSeconds, vs...))
}

// UsageReplicaSecondsGT applies the GT predicate on the "usage_replica_seconds" field.
func UsageReplicaSecondsGT(v int64) predicate.Inference {
	return predicate.Inference(sql.FieldGT(FieldUsageReplicaSeconds, v))
}

// UsageReplicaSecondsGTE applies the GTE predicate on the "usage_replica_seconds" field.
func UsageReplicaSecondsGTE(v int64) predicate.Inference {
	return predicate.Inference(sql.FieldGTE(FieldUsageReplicaSeconds, v))
}

// UsageReplicaSecondsLT applies the LT predicate on the "usage_replica_seconds" field.
func UsageReplicaSecondsLT(v int64) predicate.Inference {
	return predicate.Inference(sql.FieldLT(FieldUsageReplicaSeconds, v))
}

// UsageReplicaSecondsLTE applies the LTE predicate on the "usage_replica_seconds" field.
func UsageReplicaSecondsLTE(v int64) predicate.Inference {
	return predicate.Inference(sql.FieldLTE(FieldUsageReplicaSeconds, v))
}

// ExpirationMinutesEQ applies the EQ predicate on the "expiration_minutes" field.
func ExpirationMinutesEQ(v int64) predicate.Inference {
	return predicate.Inference(sql.FieldEQ(FieldExpirationMinutes, v))
}

// ExpirationMinutesNEQ applies the NEQ predicate on the "expiration_minutes" field.
func ExpirationMinutesNEQ(v int64) predicate.Inference {
	return predicate.Inference(sql.FieldNEQ(FieldExpirationMinutes, v))
}

// ExpirationMinutesIn applies the In predicate on the "expiration_minutes" field.
func ExpirationMinutesIn(vs ...int64) predicate.Inference {
	return predicate.Inference(sql.FieldIn(FieldExpirationMinutes, vs...))
}

// ExpirationMinutesNotIn applies the NotIn predicate on the "expiration_minutes" field.
func ExpirationMinutesNotIn(vs ...int64) predicate.Inference {
	return predicate.Inference(sql.FieldNotIn(FieldExpirationMinutes, vs...))
}

// ExpirationMinutesGT applies the GT predicate on the "expiration_minutes" field.
func ExpirationMinutesGT(v int64) predicate.Inference {
	return predicate.Inference(sql.FieldGT(FieldExpirationMinutes, v))
}

// ExpirationMinutesGTE applies the GTE predicate on the "expiration_minutes" field.
func ExpirationMinutesGTE(v int64) predicate.Inference {
	return predicate.Inference(sql.FieldGTE(FieldExpirationMinutes, v))
}

// ExpirationMinutesLT applies the LT predicate on the "expiration_minutes" field.
func ExpirationMinutesLT(v int64) predicate.Inference {
	return predicate.Inference(sql.FieldLT(FieldExpirationMinutes, v))
}

// ExpirationMinutesLTE applies the LTE predicate on the "expiration_minutes" field.
func ExpirationMinutesLTE(v int64) predicate.Inference {
	return predicate.Inference(sql.FieldLTE(FieldExpirationMinutes, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Inference) predicate.Inference {
	return predicate.Inference(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Inference) predicate.Inference {
	return predicate.Inference(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Inference) predicate.Inference {
	return predicate.Inference(sql.NotPredicates(p))
}
